//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by CodeSmith Template.
//
//     Creater: Administrator
//     Date:    2015/3/9
//     Time:    14:14
//     Version: 4.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

/// <summary>
/// CodeSmith自动生成的实体
/// </summary>
namespace ZNLCRM.Entity.DBModel
{
    using System;
    using MySoft.Data;
    using ZNLCRM.Utility;
    using ZNLFrame.Entity;
    /// <summary>
    /// 表名：ORD_PurchaseOrder 主键列：POGuid
    /// </summary>
    [SerializableAttribute()]
    public partial class ORD_PurchaseOrder : BaseEntity
    {
        #region Private Properties

        private Int32? _POID;
        private Guid? _POGuid;
        private Guid? _GCompanyID;
        private String _BillType;
        private String _BillNo;
        private DateTime? _PODate;
        private String _PONumber;
        private Int32? _SupplierID;
        private String _SupplierName;
        private String _Address;
        private String _Contact;
        private String _Telephone;
        private Int32? _PurOrgID;
        private Int32? _PurDeptID;
        private Int32? _BuyerID;
        private String _BuyerName;
        private String _ClearingForm;
        private Int32? _ClearFormDay;
        private String _Currency;
        private Decimal? _TaxRate;
        private Decimal? _TaxAmount;
        private Decimal? _Amount;
        private DateTime? _NeedPayAmtDate;
        private String _InvType;
        private Boolean? _IsInvoiced;
        private String _InvoiceType;
        private String _PickEmpName;
        private String _TransportCompany;
        private String _ShippingNo;
        private String _FreightClearForm;
        private Decimal? _Freight;
        private DateTime? _NeedDeliveryDate;
        private DateTime? _NeedShipmentDate;
        private String _Remark;
        private String _StkInOccStatus;
        private String _StkInStatus;
        private String _StkOutStatus;
        private String _ReturnOccStatus;
        private String _ReturnStatus;
        private String _PaymentStatus;
        private String _Status;
        private String _ApproveStatus;
        private String _ConEntry;
        private Int32? _CreatedEmpID;
        private String _CreatedEmpName;
        private DateTime? _CreatedTime;
        private Int32? _UpdatedEmpID;
        private String _UpdatedEmpName;
        private DateTime? _UpdatedTime;
        private Boolean? _IsCancel;
        private Boolean? _IsDeleted;

        #endregion

        #region Public Properties

        /// <summary>
        /// POGUID.
        /// </summary>
        public Guid? POGuid
        {
            get
            {
                return _POGuid;
            }
            set
            {
                this.OnPropertyValueChange(_.POGuid, _POGuid, value);
                this._POGuid = value;
            }
        }

        /// <summary>
        /// 采购单ID.
        /// </summary>
        public Int32? POID
        {
            get
            {
                return this._POID;
            }
            set
            {
                this.OnPropertyValueChange(_.POID, _POID, value);
                this._POID = value;
            }
        }

        /// <summary>
        /// 所属公司GUID.
        /// </summary>
        public Guid? GCompanyID
        {
            get
            {
                return this._GCompanyID;
            }
            set
            {
                this.OnPropertyValueChange(_.GCompanyID, _GCompanyID, value);
                this._GCompanyID = value;
            }
        }

        /// <summary>
        /// 单据类型.
        /// </summary>
        public String BillType
        {
            get
            {
                return this._BillType;
            }
            set
            {
                this.OnPropertyValueChange(_.BillType, _BillType, value);
                this._BillType = value.SubStr(20);
            }
        }

        /// <summary>
        /// 单据编号.
        /// </summary>
        public String BillNo
        {
            get
            {
                return this._BillNo;
            }
            set
            {
                this.OnPropertyValueChange(_.BillNo, _BillNo, value);
                this._BillNo = value.SubStr(20);
            }
        }

        /// <summary>
        /// 采购合同日期.
        /// </summary>
        public DateTime? PODate
        {
            get
            {
                return this._PODate;
            }
            set
            {
                this.OnPropertyValueChange(_.PODate, _PODate, value);
                this._PODate = value;
            }
        }

        /// <summary>
        /// 采购PO号码.
        /// </summary>
        public String PONumber
        {
            get
            {
                return this._PONumber;
            }
            set
            {
                this.OnPropertyValueChange(_.PONumber, _PONumber, value);
                this._PONumber = value.SubStr(50);
            }
        }

        /// <summary>
        /// 供应商ID.
        /// </summary>
        public Int32? SupplierID
        {
            get
            {
                return this._SupplierID;
            }
            set
            {
                this.OnPropertyValueChange(_.SupplierID, _SupplierID, value);
                this._SupplierID = value;
            }
        }

        /// <summary>
        /// 供应商名称.
        /// </summary>
        public String SupplierName
        {
            get
            {
                return this._SupplierName;
            }
            set
            {
                this.OnPropertyValueChange(_.SupplierName, _SupplierName, value);
                this._SupplierName = value.SubStr(200);
            }
        }

        /// <summary>
        /// 供应商地址.
        /// </summary>
        public String Address
        {
            get
            {
                return this._Address;
            }
            set
            {
                this.OnPropertyValueChange(_.Address, _Address, value);
                this._Address = value.SubStr(200);
            }
        }

        /// <summary>
        /// 供应商联系人.
        /// </summary>
        public String Contact
        {
            get
            {
                return this._Contact;
            }
            set
            {
                this.OnPropertyValueChange(_.Contact, _Contact, value);
                this._Contact = value.SubStr(50);
            }
        }

        /// <summary>
        /// 联系电话（电话or手机） .
        /// </summary>
        public String Telephone
        {
            get
            {
                return this._Telephone;
            }
            set
            {
                this.OnPropertyValueChange(_.Telephone, _Telephone, value);
                this._Telephone = value.SubStr(50);
            }
        }

        /// <summary>
        /// 采购机构ID.
        /// </summary>
        public Int32? PurOrgID
        {
            get
            {
                return this._PurOrgID;
            }
            set
            {
                this.OnPropertyValueChange(_.PurOrgID, _PurOrgID, value);
                this._PurOrgID = value;
            }
        }

        /// <summary>
        /// 采购部门ID.
        /// </summary>
        public Int32? PurDeptID
        {
            get
            {
                return this._PurDeptID;
            }
            set
            {
                this.OnPropertyValueChange(_.PurDeptID, _PurDeptID, value);
                this._PurDeptID = value;
            }
        }

        /// <summary>
        /// 采购员ID.
        /// </summary>
        public Int32? BuyerID
        {
            get
            {
                return this._BuyerID;
            }
            set
            {
                this.OnPropertyValueChange(_.BuyerID, _BuyerID, value);
                this._BuyerID = value;
            }
        }

        /// <summary>
        /// 采购员.
        /// </summary>
        public String BuyerName
        {
            get
            {
                return this._BuyerName;
            }
            set
            {
                this.OnPropertyValueChange(_.BuyerName, _BuyerName, value);
                this._BuyerName = value.SubStr(50);
            }
        }

        /// <summary>
        /// 结算方式.
        /// </summary>
        public String ClearingForm
        {
            get
            {
                return this._ClearingForm;
            }
            set
            {
                this.OnPropertyValueChange(_.ClearingForm, _ClearingForm, value);
                this._ClearingForm = value.SubStr(20);
            }
        }

        /// <summary>
        /// 结算天数.
        /// </summary>
        public Int32? ClearFormDay
        {
            get
            {
                return this._ClearFormDay;
            }
            set
            {
                this.OnPropertyValueChange(_.ClearFormDay, _ClearFormDay, value);
                this._ClearFormDay = value;
            }
        }

        /// <summary>
        /// 币种.
        /// </summary>
        public String Currency
        {
            get
            {
                return this._Currency;
            }
            set
            {
                this.OnPropertyValueChange(_.Currency, _Currency, value);
                this._Currency = value.SubStr(10);
            }
        }

        /// <summary>
        /// 税率.
        /// </summary>
        public Decimal? TaxRate
        {
            get
            {
                return this._TaxRate;
            }
            set
            {
                this.OnPropertyValueChange(_.TaxRate, _TaxRate, value);
                this._TaxRate = value;
            }
        }

        /// <summary>
        /// 税金总金额.
        /// </summary>
        public Decimal? TaxAmount
        {
            get
            {
                return this._TaxAmount;
            }
            set
            {
                this.OnPropertyValueChange(_.TaxAmount, _TaxAmount, value);
                this._TaxAmount = value;
            }
        }

        /// <summary>
        /// 订单总金额.
        /// </summary>
        public Decimal? Amount
        {
            get
            {
                return this._Amount;
            }
            set
            {
                this.OnPropertyValueChange(_.Amount, _Amount, value);
                this._Amount = value;
            }
        }

        /// <summary>
        /// 应付款日期.
        /// </summary>
        public DateTime? NeedPayAmtDate
        {
            get
            {
                return this._NeedPayAmtDate;
            }
            set
            {
                this.OnPropertyValueChange(_.NeedPayAmtDate, _NeedPayAmtDate, value);
                this._NeedPayAmtDate = value;
            }
        }

        /// <summary>
        /// 库存类型.
        /// </summary>
        public String InvType
        {
            get
            {
                return this._InvType;
            }
            set
            {
                this.OnPropertyValueChange(_.InvType, _InvType, value);
                this._InvType = value.SubStr(50);
            }
        }

        /// <summary>
        /// 是否开票.
        /// </summary>
        public Boolean? IsInvoiced
        {
            get
            {
                return this._IsInvoiced;
            }
            set
            {
                this.OnPropertyValueChange(_.IsInvoiced, _IsInvoiced, value);
                this._IsInvoiced = value;
            }
        }

        /// <summary>
        /// 开票类型.
        /// </summary>
        public String InvoiceType
        {
            get
            {
                return this._InvoiceType;
            }
            set
            {
                this.OnPropertyValueChange(_.InvoiceType, _InvoiceType, value);
                this._InvoiceType = value.SubStr(50);
            }
        }

        /// <summary>
        /// 拿货人.
        /// </summary>
        public String PickEmpName
        {
            get
            {
                return this._PickEmpName;
            }
            set
            {
                this.OnPropertyValueChange(_.PickEmpName, _PickEmpName, value);
                this._PickEmpName = value.SubStr(50);
            }
        }

        /// <summary>
        /// 货运公司.
        /// </summary>
        public String TransportCompany
        {
            get
            {
                return this._TransportCompany;
            }
            set
            {
                this.OnPropertyValueChange(_.TransportCompany, _TransportCompany, value);
                this._TransportCompany = value.SubStr(50);
            }
        }

        /// <summary>
        /// 货运单号.
        /// </summary>
        public String ShippingNo
        {
            get
            {
                return this._ShippingNo;
            }
            set
            {
                this.OnPropertyValueChange(_.ShippingNo, _ShippingNo, value);
                this._ShippingNo = value.SubStr(100);
            }
        }

        /// <summary>
        /// 运费结算.
        /// </summary>
        public String FreightClearForm
        {
            get
            {
                return this._FreightClearForm;
            }
            set
            {
                this.OnPropertyValueChange(_.FreightClearForm, _FreightClearForm, value);
                this._FreightClearForm = value.SubStr(50);
            }
        }

        /// <summary>
        /// 运费金额.
        /// </summary>
        public Decimal? Freight
        {
            get
            {
                return this._Freight;
            }
            set
            {
                this.OnPropertyValueChange(_.Freight, _Freight, value);
                this._Freight = value;
            }
        }

        /// <summary>
        /// 应到货日期.
        /// </summary>
        public DateTime? NeedDeliveryDate
        {
            get
            {
                return this._NeedDeliveryDate;
            }
            set
            {
                this.OnPropertyValueChange(_.NeedDeliveryDate, _NeedDeliveryDate, value);
                this._NeedDeliveryDate = value;
            }
        }

        /// <summary>
        /// 销售应发货日期.
        /// </summary>
        public DateTime? NeedShipmentDate
        {
            get
            {
                return this._NeedShipmentDate;
            }
            set
            {
                this.OnPropertyValueChange(_.NeedShipmentDate, _NeedShipmentDate, value);
                this._NeedShipmentDate = value;
            }
        }

        /// <summary>
        /// 备注.
        /// </summary>
        public String Remark
        {
            get
            {
                return this._Remark;
            }
            set
            {
                this.OnPropertyValueChange(_.Remark, _Remark, value);
                this._Remark = value.SubStr(200);
            }
        }

        /// <summary>
        /// 占有状态(入库单提交时回写).
        /// </summary>
        public String StkInOccStatus
        {
            get
            {
                return this._StkInOccStatus;
            }
            set
            {
                this.OnPropertyValueChange(_.StkInOccStatus, _StkInOccStatus, value);
                this._StkInOccStatus = value.SubStr(10);
            }
        }

        /// <summary>
        /// 入库状态.
        /// </summary>
        public String StkInStatus
        {
            get
            {
                return this._StkInStatus;
            }
            set
            {
                this.OnPropertyValueChange(_.StkInStatus, _StkInStatus, value);
                this._StkInStatus = value.SubStr(10);
            }
        }

        /// <summary>
        /// 出库状态.
        /// </summary>
        public String StkOutStatus
        {
            get
            {
                return this._StkOutStatus;
            }
            set
            {
                this.OnPropertyValueChange(_.StkOutStatus, _StkOutStatus, value);
                this._StkOutStatus = value.SubStr(10);
            }
        }

        /// <summary>
        /// 退货占有状态.
        /// </summary>
        public String ReturnOccStatus
        {
            get
            {
                return this._ReturnOccStatus;
            }
            set
            {
                this.OnPropertyValueChange(_.ReturnOccStatus, _ReturnOccStatus, value);
                this._ReturnOccStatus = value.SubStr(10);
            }
        }

        /// <summary>
        /// 退货状态.
        /// </summary>
        public String ReturnStatus
        {
            get
            {
                return this._ReturnStatus;
            }
            set
            {
                this.OnPropertyValueChange(_.ReturnStatus, _ReturnStatus, value);
                this._ReturnStatus = value.SubStr(10);
            }
        }

        /// <summary>
        /// 付款状态.
        /// </summary>
        public String PaymentStatus
        {
            get
            {
                return this._PaymentStatus;
            }
            set
            {
                this.OnPropertyValueChange(_.PaymentStatus, _PaymentStatus, value);
                this._PaymentStatus = value.SubStr(10);
            }
        }

        /// <summary>
        /// 单据状态.
        /// </summary>
        public String Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnPropertyValueChange(_.Status, _Status, value);
                this._Status = value.SubStr(10);
            }
        }

        /// <summary>
        /// 审批状态.
        /// </summary>
        public String ApproveStatus
        {
            get
            {
                return this._ApproveStatus;
            }
            set
            {
                this.OnPropertyValueChange(_.ApproveStatus, _ApproveStatus, value);
                this._ApproveStatus = value.SubStr(20);
            }
        }

        /// <summary>
        /// 合同条款.
        /// </summary>
        public String ConEntry
        {
            get
            {
                return this._ConEntry;
            }
            set
            {
                this.OnPropertyValueChange(_.ConEntry, _ConEntry, value);
                this._ConEntry = value.SubStr(2000);
            }
        }

        /// <summary>
        /// 创建人.
        /// </summary>
        public Int32? CreatedEmpID
        {
            get
            {
                return this._CreatedEmpID;
            }
            set
            {
                this.OnPropertyValueChange(_.CreatedEmpID, _CreatedEmpID, value);
                this._CreatedEmpID = value;
            }
        }

        /// <summary>
        /// 创建人姓名.
        /// </summary>
        public String CreatedEmpName
        {
            get
            {
                return this._CreatedEmpName;
            }
            set
            {
                this.OnPropertyValueChange(_.CreatedEmpName, _CreatedEmpName, value);
                this._CreatedEmpName = value.SubStr(50);
            }
        }

        /// <summary>
        /// 创建时间.
        /// </summary>
        public DateTime? CreatedTime
        {
            get
            {
                return this._CreatedTime;
            }
            set
            {
                this.OnPropertyValueChange(_.CreatedTime, _CreatedTime, value);
                this._CreatedTime = value;
            }
        }

        /// <summary>
        /// 更新人.
        /// </summary>
        public Int32? UpdatedEmpID
        {
            get
            {
                return this._UpdatedEmpID;
            }
            set
            {
                this.OnPropertyValueChange(_.UpdatedEmpID, _UpdatedEmpID, value);
                this._UpdatedEmpID = value;
            }
        }

        /// <summary>
        /// 更新人.
        /// </summary>
        public String UpdatedEmpName
        {
            get
            {
                return this._UpdatedEmpName;
            }
            set
            {
                this.OnPropertyValueChange(_.UpdatedEmpName, _UpdatedEmpName, value);
                this._UpdatedEmpName = value.SubStr(50);
            }
        }

        /// <summary>
        /// 更新时间.
        /// </summary>
        public DateTime? UpdatedTime
        {
            get
            {
                return this._UpdatedTime;
            }
            set
            {
                this.OnPropertyValueChange(_.UpdatedTime, _UpdatedTime, value);
                this._UpdatedTime = value;
            }
        }

        /// <summary>
        /// 已取消(1:取消:null或0正常).
        /// </summary>
        public Boolean? IsCancel
        {
            get
            {
                return this._IsCancel;
            }
            set
            {
                this.OnPropertyValueChange(_.IsCancel, _IsCancel, value);
                this._IsCancel = value;
            }
        }

        /// <summary>
        /// 是否删除.
        /// </summary>
        public Boolean? IsDeleted
        {
            get
            {
                return this._IsDeleted;
            }
            set
            {
                this.OnPropertyValueChange(_.IsDeleted, _IsDeleted, value);
                this._IsDeleted = value;
            }
        }

        #endregion
        /// <summary>
        /// 获取实体对应的表名
        /// </summary>
        protected override Table GetTable()
        {
            return new Table<ORD_PurchaseOrder>("ORD_PurchaseOrder");
        }

        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        protected override Field GetIdentityField()
        {
            return _.POID;
        }

        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        protected override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.POGuid
			};
        }

        /// <summary>
        /// 获取列信息
        /// </summary>
        protected override Field[] GetFields()
        {
            return new Field[] {
				_.POID,		
				_.POGuid,		
				_.GCompanyID,		
				_.BillType,		
				_.BillNo,		
				_.PODate,		
				_.PONumber,		
				_.SupplierID,		
				_.SupplierName,		
				_.Address,		
				_.Contact,		
				_.Telephone,		
				_.PurOrgID,		
				_.PurDeptID,		
				_.BuyerID,		
				_.BuyerName,		
				_.ClearingForm,		
				_.ClearFormDay,		
				_.Currency,		
				_.TaxRate,		
				_.TaxAmount,		
				_.Amount,		
				_.NeedPayAmtDate,		
				_.InvType,		
				_.IsInvoiced,		
				_.InvoiceType,		
				_.PickEmpName,		
				_.TransportCompany,		
				_.ShippingNo,		
				_.FreightClearForm,		
				_.Freight,		
				_.NeedDeliveryDate,		
				_.NeedShipmentDate,		
				_.Remark,		
				_.StkInOccStatus,		
				_.StkInStatus,		
				_.StkOutStatus,		
				_.ReturnOccStatus,		
				_.ReturnStatus,		
				_.PaymentStatus,		
				_.Status,		
				_.ApproveStatus,		
				_.ConEntry,		
				_.CreatedEmpID,		
				_.CreatedEmpName,		
				_.CreatedTime,		
				_.UpdatedEmpID,		
				_.UpdatedEmpName,		
				_.UpdatedTime,		
				_.IsCancel,		
				_.IsDeleted		
			};
        }

        /// <summary>
        /// 获取列数据
        /// </summary>
        protected override object[] GetValues()
        {
            return new object[] {
				this._POID,		
				this._POGuid,		
				this._GCompanyID,		
				this._BillType,		
				this._BillNo,		
				this._PODate,		
				this._PONumber,		
				this._SupplierID,		
				this._SupplierName,		
				this._Address,		
				this._Contact,		
				this._Telephone,		
				this._PurOrgID,		
				this._PurDeptID,		
				this._BuyerID,		
				this._BuyerName,		
				this._ClearingForm,		
				this._ClearFormDay,		
				this._Currency,		
				this._TaxRate,		
				this._TaxAmount,		
				this._Amount,		
				this._NeedPayAmtDate,		
				this._InvType,		
				this._IsInvoiced,		
				this._InvoiceType,		
				this._PickEmpName,		
				this._TransportCompany,		
				this._ShippingNo,		
				this._FreightClearForm,		
				this._Freight,		
				this._NeedDeliveryDate,		
				this._NeedShipmentDate,		
				this._Remark,		
				this._StkInOccStatus,		
				this._StkInStatus,		
				this._StkOutStatus,		
				this._ReturnOccStatus,		
				this._ReturnStatus,		
				this._PaymentStatus,		
				this._Status,		
				this._ApproveStatus,		
				this._ConEntry,		
				this._CreatedEmpID,		
				this._CreatedEmpName,		
				this._CreatedTime,		
				this._UpdatedEmpID,		
				this._UpdatedEmpName,		
				this._UpdatedTime,		
				this._IsCancel,		
				this._IsDeleted		
			};
        }

        /// <summary>
        /// 给当前实体赋值
        /// </summary>
        protected override void SetValues(IRowReader reader)
        {
            if ((false == reader.IsDBNull(_.POID)))
            {
                this._POID = reader.GetInt32(_.POID);
            }
            if ((false == reader.IsDBNull(_.POGuid)))
            {
                this._POGuid = reader.GetGuid(_.POGuid);
            }
            if ((false == reader.IsDBNull(_.GCompanyID)))
            {
                this._GCompanyID = reader.GetGuid(_.GCompanyID);
            }
            if ((false == reader.IsDBNull(_.BillType)))
            {
                this._BillType = reader.GetString(_.BillType);
            }
            if ((false == reader.IsDBNull(_.BillNo)))
            {
                this._BillNo = reader.GetString(_.BillNo);
            }
            if ((false == reader.IsDBNull(_.PODate)))
            {
                this._PODate = reader.GetDateTime(_.PODate);
            }
            if ((false == reader.IsDBNull(_.PONumber)))
            {
                this._PONumber = reader.GetString(_.PONumber);
            }
            if ((false == reader.IsDBNull(_.SupplierID)))
            {
                this._SupplierID = reader.GetInt32(_.SupplierID);
            }
            if ((false == reader.IsDBNull(_.SupplierName)))
            {
                this._SupplierName = reader.GetString(_.SupplierName);
            }
            if ((false == reader.IsDBNull(_.Address)))
            {
                this._Address = reader.GetString(_.Address);
            }
            if ((false == reader.IsDBNull(_.Contact)))
            {
                this._Contact = reader.GetString(_.Contact);
            }
            if ((false == reader.IsDBNull(_.Telephone)))
            {
                this._Telephone = reader.GetString(_.Telephone);
            }
            if ((false == reader.IsDBNull(_.PurOrgID)))
            {
                this._PurOrgID = reader.GetInt32(_.PurOrgID);
            }
            if ((false == reader.IsDBNull(_.PurDeptID)))
            {
                this._PurDeptID = reader.GetInt32(_.PurDeptID);
            }
            if ((false == reader.IsDBNull(_.BuyerID)))
            {
                this._BuyerID = reader.GetInt32(_.BuyerID);
            }
            if ((false == reader.IsDBNull(_.BuyerName)))
            {
                this._BuyerName = reader.GetString(_.BuyerName);
            }
            if ((false == reader.IsDBNull(_.ClearingForm)))
            {
                this._ClearingForm = reader.GetString(_.ClearingForm);
            }
            if ((false == reader.IsDBNull(_.ClearFormDay)))
            {
                this._ClearFormDay = reader.GetInt32(_.ClearFormDay);
            }
            if ((false == reader.IsDBNull(_.Currency)))
            {
                this._Currency = reader.GetString(_.Currency);
            }
            if ((false == reader.IsDBNull(_.TaxRate)))
            {
                this._TaxRate = reader.GetDecimal(_.TaxRate);
            }
            if ((false == reader.IsDBNull(_.TaxAmount)))
            {
                this._TaxAmount = reader.GetDecimal(_.TaxAmount);
            }
            if ((false == reader.IsDBNull(_.Amount)))
            {
                this._Amount = reader.GetDecimal(_.Amount);
            }
            if ((false == reader.IsDBNull(_.NeedPayAmtDate)))
            {
                this._NeedPayAmtDate = reader.GetDateTime(_.NeedPayAmtDate);
            }
            if ((false == reader.IsDBNull(_.InvType)))
            {
                this._InvType = reader.GetString(_.InvType);
            }
            if ((false == reader.IsDBNull(_.IsInvoiced)))
            {
                this._IsInvoiced = reader.GetBoolean(_.IsInvoiced);
            }
            if ((false == reader.IsDBNull(_.InvoiceType)))
            {
                this._InvoiceType = reader.GetString(_.InvoiceType);
            }
            if ((false == reader.IsDBNull(_.PickEmpName)))
            {
                this._PickEmpName = reader.GetString(_.PickEmpName);
            }
            if ((false == reader.IsDBNull(_.TransportCompany)))
            {
                this._TransportCompany = reader.GetString(_.TransportCompany);
            }
            if ((false == reader.IsDBNull(_.ShippingNo)))
            {
                this._ShippingNo = reader.GetString(_.ShippingNo);
            }
            if ((false == reader.IsDBNull(_.FreightClearForm)))
            {
                this._FreightClearForm = reader.GetString(_.FreightClearForm);
            }
            if ((false == reader.IsDBNull(_.Freight)))
            {
                this._Freight = reader.GetDecimal(_.Freight);
            }
            if ((false == reader.IsDBNull(_.NeedDeliveryDate)))
            {
                this._NeedDeliveryDate = reader.GetDateTime(_.NeedDeliveryDate);
            }
            if ((false == reader.IsDBNull(_.NeedShipmentDate)))
            {
                this._NeedShipmentDate = reader.GetDateTime(_.NeedShipmentDate);
            }
            if ((false == reader.IsDBNull(_.Remark)))
            {
                this._Remark = reader.GetString(_.Remark);
            }
            if ((false == reader.IsDBNull(_.StkInOccStatus)))
            {
                this._StkInOccStatus = reader.GetString(_.StkInOccStatus);
            }
            if ((false == reader.IsDBNull(_.StkInStatus)))
            {
                this._StkInStatus = reader.GetString(_.StkInStatus);
            }
            if ((false == reader.IsDBNull(_.StkOutStatus)))
            {
                this._StkOutStatus = reader.GetString(_.StkOutStatus);
            }
            if ((false == reader.IsDBNull(_.ReturnOccStatus)))
            {
                this._ReturnOccStatus = reader.GetString(_.ReturnOccStatus);
            }
            if ((false == reader.IsDBNull(_.ReturnStatus)))
            {
                this._ReturnStatus = reader.GetString(_.ReturnStatus);
            }
            if ((false == reader.IsDBNull(_.PaymentStatus)))
            {
                this._PaymentStatus = reader.GetString(_.PaymentStatus);
            }
            if ((false == reader.IsDBNull(_.Status)))
            {
                this._Status = reader.GetString(_.Status);
            }
            if ((false == reader.IsDBNull(_.ApproveStatus)))
            {
                this._ApproveStatus = reader.GetString(_.ApproveStatus);
            }
            if ((false == reader.IsDBNull(_.ConEntry)))
            {
                this._ConEntry = reader.GetString(_.ConEntry);
            }
            if ((false == reader.IsDBNull(_.CreatedEmpID)))
            {
                this._CreatedEmpID = reader.GetInt32(_.CreatedEmpID);
            }
            if ((false == reader.IsDBNull(_.CreatedEmpName)))
            {
                this._CreatedEmpName = reader.GetString(_.CreatedEmpName);
            }
            if ((false == reader.IsDBNull(_.CreatedTime)))
            {
                this._CreatedTime = reader.GetDateTime(_.CreatedTime);
            }
            if ((false == reader.IsDBNull(_.UpdatedEmpID)))
            {
                this._UpdatedEmpID = reader.GetInt32(_.UpdatedEmpID);
            }
            if ((false == reader.IsDBNull(_.UpdatedEmpName)))
            {
                this._UpdatedEmpName = reader.GetString(_.UpdatedEmpName);
            }
            if ((false == reader.IsDBNull(_.UpdatedTime)))
            {
                this._UpdatedTime = reader.GetDateTime(_.UpdatedTime);
            }
            if ((false == reader.IsDBNull(_.IsCancel)))
            {
                this._IsCancel = reader.GetBoolean(_.IsCancel);
            }
            if ((false == reader.IsDBNull(_.IsDeleted)))
            {
                this._IsDeleted = reader.GetBoolean(_.IsDeleted);
            }
        }

        public override int GetHashCode()
        {
            return base.GetHashCode();
        }

        public override bool Equals(object obj)
        {
            if ((obj == null))
            {
                return false;
            }
            if ((false == typeof(ORD_PurchaseOrder).IsAssignableFrom(obj.GetType())))
            {
                return false;
            }
            if ((((object)(this)) == ((object)(obj))))
            {
                return true;
            }
            return false;
        }

        public class _
        {

            /// <summary>
            /// 表示选择所有列，与*等同
            /// </summary>
            public static AllField All = new AllField<ORD_PurchaseOrder>();

            /// <summary>
            /// 采购单ID - 字段名：POID - 数据类型：Int32?
            /// </summary>
            public static Field POID = new Field<ORD_PurchaseOrder>("POID");
            /// <summary>
            /// POGUID - 字段名：POGuid - 数据类型：Guid?
            /// </summary>
            public static Field POGuid = new Field<ORD_PurchaseOrder>("POGuid");
            /// <summary>
            /// 所属公司GUID - 字段名：GCompanyID - 数据类型：Guid?
            /// </summary>
            public static Field GCompanyID = new Field<ORD_PurchaseOrder>("GCompanyID");
            /// <summary>
            /// 单据类型 - 字段名：BillType - 数据类型：String
            /// </summary>
            public static Field BillType = new Field<ORD_PurchaseOrder>("BillType");
            /// <summary>
            /// 单据编号 - 字段名：BillNo - 数据类型：String
            /// </summary>
            public static Field BillNo = new Field<ORD_PurchaseOrder>("BillNo");
            /// <summary>
            /// 采购合同日期 - 字段名：PODate - 数据类型：DateTime?
            /// </summary>
            public static Field PODate = new Field<ORD_PurchaseOrder>("PODate");
            /// <summary>
            /// 采购PO号码 - 字段名：PONumber - 数据类型：String
            /// </summary>
            public static Field PONumber = new Field<ORD_PurchaseOrder>("PONumber");
            /// <summary>
            /// 供应商ID - 字段名：SupplierID - 数据类型：Int32?
            /// </summary>
            public static Field SupplierID = new Field<ORD_PurchaseOrder>("SupplierID");
            /// <summary>
            /// 供应商名称 - 字段名：SupplierName - 数据类型：String
            /// </summary>
            public static Field SupplierName = new Field<ORD_PurchaseOrder>("SupplierName");
            /// <summary>
            /// 供应商地址 - 字段名：Address - 数据类型：String
            /// </summary>
            public static Field Address = new Field<ORD_PurchaseOrder>("Address");
            /// <summary>
            /// 供应商联系人 - 字段名：Contact - 数据类型：String
            /// </summary>
            public static Field Contact = new Field<ORD_PurchaseOrder>("Contact");
            /// <summary>
            /// 联系电话（电话or手机）  - 字段名：Telephone - 数据类型：String
            /// </summary>
            public static Field Telephone = new Field<ORD_PurchaseOrder>("Telephone");
            /// <summary>
            /// 采购机构ID - 字段名：PurOrgID - 数据类型：Int32?
            /// </summary>
            public static Field PurOrgID = new Field<ORD_PurchaseOrder>("PurOrgID");
            /// <summary>
            /// 采购部门ID - 字段名：PurDeptID - 数据类型：Int32?
            /// </summary>
            public static Field PurDeptID = new Field<ORD_PurchaseOrder>("PurDeptID");
            /// <summary>
            /// 采购员ID - 字段名：BuyerID - 数据类型：Int32?
            /// </summary>
            public static Field BuyerID = new Field<ORD_PurchaseOrder>("BuyerID");
            /// <summary>
            /// 采购员 - 字段名：BuyerName - 数据类型：String
            /// </summary>
            public static Field BuyerName = new Field<ORD_PurchaseOrder>("BuyerName");
            /// <summary>
            /// 结算方式 - 字段名：ClearingForm - 数据类型：String
            /// </summary>
            public static Field ClearingForm = new Field<ORD_PurchaseOrder>("ClearingForm");
            /// <summary>
            /// 结算天数 - 字段名：ClearFormDay - 数据类型：Int32?
            /// </summary>
            public static Field ClearFormDay = new Field<ORD_PurchaseOrder>("ClearFormDay");
            /// <summary>
            /// 币种 - 字段名：Currency - 数据类型：String
            /// </summary>
            public static Field Currency = new Field<ORD_PurchaseOrder>("Currency");
            /// <summary>
            /// 税率 - 字段名：TaxRate - 数据类型：Decimal?
            /// </summary>
            public static Field TaxRate = new Field<ORD_PurchaseOrder>("TaxRate");
            /// <summary>
            /// 税金总金额 - 字段名：TaxAmount - 数据类型：Decimal?
            /// </summary>
            public static Field TaxAmount = new Field<ORD_PurchaseOrder>("TaxAmount");
            /// <summary>
            /// 订单总金额 - 字段名：Amount - 数据类型：Decimal?
            /// </summary>
            public static Field Amount = new Field<ORD_PurchaseOrder>("Amount");
            /// <summary>
            /// 应付款日期 - 字段名：NeedPayAmtDate - 数据类型：DateTime?
            /// </summary>
            public static Field NeedPayAmtDate = new Field<ORD_PurchaseOrder>("NeedPayAmtDate");
            /// <summary>
            /// 库存类型 - 字段名：InvType - 数据类型：String
            /// </summary>
            public static Field InvType = new Field<ORD_PurchaseOrder>("InvType");
            /// <summary>
            /// 是否开票 - 字段名：IsInvoiced - 数据类型：Boolean?
            /// </summary>
            public static Field IsInvoiced = new Field<ORD_PurchaseOrder>("IsInvoiced");
            /// <summary>
            /// 开票类型 - 字段名：InvoiceType - 数据类型：String
            /// </summary>
            public static Field InvoiceType = new Field<ORD_PurchaseOrder>("InvoiceType");
            /// <summary>
            /// 拿货人 - 字段名：PickEmpName - 数据类型：String
            /// </summary>
            public static Field PickEmpName = new Field<ORD_PurchaseOrder>("PickEmpName");
            /// <summary>
            /// 货运公司 - 字段名：TransportCompany - 数据类型：String
            /// </summary>
            public static Field TransportCompany = new Field<ORD_PurchaseOrder>("TransportCompany");
            /// <summary>
            /// 货运单号 - 字段名：ShippingNo - 数据类型：String
            /// </summary>
            public static Field ShippingNo = new Field<ORD_PurchaseOrder>("ShippingNo");
            /// <summary>
            /// 运费结算 - 字段名：FreightClearForm - 数据类型：String
            /// </summary>
            public static Field FreightClearForm = new Field<ORD_PurchaseOrder>("FreightClearForm");
            /// <summary>
            /// 运费金额 - 字段名：Freight - 数据类型：Decimal?
            /// </summary>
            public static Field Freight = new Field<ORD_PurchaseOrder>("Freight");
            /// <summary>
            /// 应到货日期 - 字段名：NeedDeliveryDate - 数据类型：DateTime?
            /// </summary>
            public static Field NeedDeliveryDate = new Field<ORD_PurchaseOrder>("NeedDeliveryDate");
            /// <summary>
            /// 销售应发货日期 - 字段名：NeedShipmentDate - 数据类型：DateTime?
            /// </summary>
            public static Field NeedShipmentDate = new Field<ORD_PurchaseOrder>("NeedShipmentDate");
            /// <summary>
            /// 备注 - 字段名：Remark - 数据类型：String
            /// </summary>
            public static Field Remark = new Field<ORD_PurchaseOrder>("Remark");
            /// <summary>
            /// 占有状态(入库单提交时回写) - 字段名：StkInOccStatus - 数据类型：String
            /// </summary>
            public static Field StkInOccStatus = new Field<ORD_PurchaseOrder>("StkInOccStatus");
            /// <summary>
            /// 入库状态 - 字段名：StkInStatus - 数据类型：String
            /// </summary>
            public static Field StkInStatus = new Field<ORD_PurchaseOrder>("StkInStatus");
            /// <summary>
            /// 出库状态 - 字段名：StkOutStatus - 数据类型：String
            /// </summary>
            public static Field StkOutStatus = new Field<ORD_PurchaseOrder>("StkOutStatus");
            /// <summary>
            /// 退货占有状态 - 字段名：ReturnOccStatus - 数据类型：String
            /// </summary>
            public static Field ReturnOccStatus = new Field<ORD_PurchaseOrder>("ReturnOccStatus");
            /// <summary>
            /// 退货状态 - 字段名：ReturnStatus - 数据类型：String
            /// </summary>
            public static Field ReturnStatus = new Field<ORD_PurchaseOrder>("ReturnStatus");
            /// <summary>
            /// 付款状态 - 字段名：PaymentStatus - 数据类型：String
            /// </summary>
            public static Field PaymentStatus = new Field<ORD_PurchaseOrder>("PaymentStatus");
            /// <summary>
            /// 单据状态 - 字段名：Status - 数据类型：String
            /// </summary>
            public static Field Status = new Field<ORD_PurchaseOrder>("Status");
            /// <summary>
            /// 审批状态 - 字段名：ApproveStatus - 数据类型：String
            /// </summary>
            public static Field ApproveStatus = new Field<ORD_PurchaseOrder>("ApproveStatus");
            /// <summary>
            /// 合同条款 - 字段名：ConEntry - 数据类型：String
            /// </summary>
            public static Field ConEntry = new Field<ORD_PurchaseOrder>("ConEntry");
            /// <summary>
            /// 创建人 - 字段名：CreatedEmpID - 数据类型：Int32?
            /// </summary>
            public static Field CreatedEmpID = new Field<ORD_PurchaseOrder>("CreatedEmpID");
            /// <summary>
            /// 创建人姓名 - 字段名：CreatedEmpName - 数据类型：String
            /// </summary>
            public static Field CreatedEmpName = new Field<ORD_PurchaseOrder>("CreatedEmpName");
            /// <summary>
            /// 创建时间 - 字段名：CreatedTime - 数据类型：DateTime?
            /// </summary>
            public static Field CreatedTime = new Field<ORD_PurchaseOrder>("CreatedTime");
            /// <summary>
            /// 更新人 - 字段名：UpdatedEmpID - 数据类型：Int32?
            /// </summary>
            public static Field UpdatedEmpID = new Field<ORD_PurchaseOrder>("UpdatedEmpID");
            /// <summary>
            /// 更新人 - 字段名：UpdatedEmpName - 数据类型：String
            /// </summary>
            public static Field UpdatedEmpName = new Field<ORD_PurchaseOrder>("UpdatedEmpName");
            /// <summary>
            /// 更新时间 - 字段名：UpdatedTime - 数据类型：DateTime?
            /// </summary>
            public static Field UpdatedTime = new Field<ORD_PurchaseOrder>("UpdatedTime");
            /// <summary>
            /// 已取消(1:取消:null或0正常) - 字段名：IsCancel - 数据类型：Boolean?
            /// </summary>
            public static Field IsCancel = new Field<ORD_PurchaseOrder>("IsCancel");
            /// <summary>
            /// 是否删除 - 字段名：IsDeleted - 数据类型：Boolean?
            /// </summary>
            public static Field IsDeleted = new Field<ORD_PurchaseOrder>("IsDeleted");
        }
    }
}
