//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by CodeSmith Template.
//
//     Creater: David
//     Date:    2015/1/16
//     Time:    10:23
//     Version: 4.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

/// <summary>
/// CodeSmith自动生成的实体
/// </summary>
namespace ZNLCRM.Entity.DBModel
{
    using System;
    using MySoft.Data;
    using ZNLCRM.Utility;
    using ZNLFrame.Entity;
    /// <summary>
    /// 表名：ORD_PurchaseNotice 主键列：NoticeGuid
    /// </summary>
    [SerializableAttribute()]
    public partial class ORD_PurchaseNotice : BaseEntity
    {
        #region Private Properties

        private Int32? _NoticeID;
        private Guid _NoticeGuid;
        private Guid? _SOGuid;
        private Guid? _SOLineGuid;
        private Int32? _NoticeQty;
        private Int32? _PurchaseQty;
        private Int32? _BuyerID;
        private String _BuyerName;
        private String _Demands;
        private Int32? _CreatedEmpID;
        private String _CreatedEmpName;
        private DateTime? _CreatedTime;
        private Int32? _UpdatedEmpID;
        private String _UpdatedEmpName;
        private DateTime? _UpdatedTime;
        private Boolean? _IsDeleted;

        #endregion

        #region Public Properties

        /// <summary>
        /// .
        /// </summary>
        public Guid NoticeGuid
        {
            get
            {
                return _NoticeGuid;
            }
            set
            {
                this.OnPropertyValueChange(_.NoticeGuid, _NoticeGuid, value);
                this._NoticeGuid = value;
            }
        }

        /// <summary>
        /// .
        /// </summary>
        public Int32? NoticeID
        {
            get
            {
                return this._NoticeID;
            }
            set
            {
                this.OnPropertyValueChange(_.NoticeID, _NoticeID, value);
                this._NoticeID = value;
            }
        }

        /// <summary>
        /// .
        /// </summary>
        public Guid? SOGuid
        {
            get
            {
                return this._SOGuid;
            }
            set
            {
                this.OnPropertyValueChange(_.SOGuid, _SOGuid, value);
                this._SOGuid = value;
            }
        }

        /// <summary>
        /// .
        /// </summary>
        public Guid? SOLineGuid
        {
            get
            {
                return this._SOLineGuid;
            }
            set
            {
                this.OnPropertyValueChange(_.SOLineGuid, _SOLineGuid, value);
                this._SOLineGuid = value;
            }
        }

        /// <summary>
        /// .
        /// </summary>
        public Int32? NoticeQty
        {
            get
            {
                return this._NoticeQty;
            }
            set
            {
                this.OnPropertyValueChange(_.NoticeQty, _NoticeQty, value);
                this._NoticeQty = value;
            }
        }

        /// <summary>
        /// 采购数量.
        /// </summary>
        public Int32? PurchaseQty
        {
            get
            {
                return this._PurchaseQty;
            }
            set
            {
                this.OnPropertyValueChange(_.PurchaseQty, _PurchaseQty, value);
                this._PurchaseQty = value;
            }
        }

        /// <summary>
        /// .
        /// </summary>
        public Int32? BuyerID
        {
            get
            {
                return this._BuyerID;
            }
            set
            {
                this.OnPropertyValueChange(_.BuyerID, _BuyerID, value);
                this._BuyerID = value;
            }
        }

        /// <summary>
        /// .
        /// </summary>
        public String BuyerName
        {
            get
            {
                return this._BuyerName;
            }
            set
            {
                this.OnPropertyValueChange(_.BuyerName, _BuyerName, value);
                this._BuyerName = value.SubStr(50);
            }
        }

        /// <summary>
        /// 采购要求.
        /// </summary>
        public String Demands
        {
            get
            {
                return this._Demands;
            }
            set
            {
                this.OnPropertyValueChange(_.Demands, _Demands, value);
                this._Demands = value.SubStr(100);
            }
        }

        /// <summary>
        /// .
        /// </summary>
        public Int32? CreatedEmpID
        {
            get
            {
                return this._CreatedEmpID;
            }
            set
            {
                this.OnPropertyValueChange(_.CreatedEmpID, _CreatedEmpID, value);
                this._CreatedEmpID = value;
            }
        }

        /// <summary>
        /// .
        /// </summary>
        public String CreatedEmpName
        {
            get
            {
                return this._CreatedEmpName;
            }
            set
            {
                this.OnPropertyValueChange(_.CreatedEmpName, _CreatedEmpName, value);
                this._CreatedEmpName = value.SubStr(50);
            }
        }

        /// <summary>
        /// .
        /// </summary>
        public DateTime? CreatedTime
        {
            get
            {
                return this._CreatedTime;
            }
            set
            {
                this.OnPropertyValueChange(_.CreatedTime, _CreatedTime, value);
                this._CreatedTime = value;
            }
        }

        /// <summary>
        /// .
        /// </summary>
        public Int32? UpdatedEmpID
        {
            get
            {
                return this._UpdatedEmpID;
            }
            set
            {
                this.OnPropertyValueChange(_.UpdatedEmpID, _UpdatedEmpID, value);
                this._UpdatedEmpID = value;
            }
        }

        /// <summary>
        /// .
        /// </summary>
        public String UpdatedEmpName
        {
            get
            {
                return this._UpdatedEmpName;
            }
            set
            {
                this.OnPropertyValueChange(_.UpdatedEmpName, _UpdatedEmpName, value);
                this._UpdatedEmpName = value.SubStr(50);
            }
        }

        /// <summary>
        /// .
        /// </summary>
        public DateTime? UpdatedTime
        {
            get
            {
                return this._UpdatedTime;
            }
            set
            {
                this.OnPropertyValueChange(_.UpdatedTime, _UpdatedTime, value);
                this._UpdatedTime = value;
            }
        }

        /// <summary>
        /// .
        /// </summary>
        public Boolean? IsDeleted
        {
            get
            {
                return this._IsDeleted;
            }
            set
            {
                this.OnPropertyValueChange(_.IsDeleted, _IsDeleted, value);
                this._IsDeleted = value;
            }
        }

        #endregion
        /// <summary>
        /// 获取实体对应的表名
        /// </summary>
        protected override Table GetTable()
        {
            return new Table<ORD_PurchaseNotice>("ORD_PurchaseNotice");
        }

        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        protected override Field GetIdentityField()
        {
            return _.NoticeID;
        }

        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        protected override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.NoticeGuid
			};
        }

        /// <summary>
        /// 获取列信息
        /// </summary>
        protected override Field[] GetFields()
        {
            return new Field[] {
				_.NoticeID,		
				_.NoticeGuid,		
				_.SOGuid,		
				_.SOLineGuid,		
				_.NoticeQty,		
				_.PurchaseQty,		
				_.BuyerID,		
				_.BuyerName,		
				_.Demands,		
				_.CreatedEmpID,		
				_.CreatedEmpName,		
				_.CreatedTime,		
				_.UpdatedEmpID,		
				_.UpdatedEmpName,		
				_.UpdatedTime,		
				_.IsDeleted		
			};
        }

        /// <summary>
        /// 获取列数据
        /// </summary>
        protected override object[] GetValues()
        {
            return new object[] {
				this._NoticeID,		
				this._NoticeGuid,		
				this._SOGuid,		
				this._SOLineGuid,		
				this._NoticeQty,		
				this._PurchaseQty,		
				this._BuyerID,		
				this._BuyerName,		
				this._Demands,		
				this._CreatedEmpID,		
				this._CreatedEmpName,		
				this._CreatedTime,		
				this._UpdatedEmpID,		
				this._UpdatedEmpName,		
				this._UpdatedTime,		
				this._IsDeleted		
			};
        }

        /// <summary>
        /// 给当前实体赋值
        /// </summary>
        protected override void SetValues(IRowReader reader)
        {
            if ((false == reader.IsDBNull(_.NoticeID)))
            {
                this._NoticeID = reader.GetInt32(_.NoticeID);
            }
            if ((false == reader.IsDBNull(_.NoticeGuid)))
            {
                this._NoticeGuid = reader.GetGuid(_.NoticeGuid);
            }
            if ((false == reader.IsDBNull(_.SOGuid)))
            {
                this._SOGuid = reader.GetGuid(_.SOGuid);
            }
            if ((false == reader.IsDBNull(_.SOLineGuid)))
            {
                this._SOLineGuid = reader.GetGuid(_.SOLineGuid);
            }
            if ((false == reader.IsDBNull(_.NoticeQty)))
            {
                this._NoticeQty = reader.GetInt32(_.NoticeQty);
            }
            if ((false == reader.IsDBNull(_.PurchaseQty)))
            {
                this._PurchaseQty = reader.GetInt32(_.PurchaseQty);
            }
            if ((false == reader.IsDBNull(_.BuyerID)))
            {
                this._BuyerID = reader.GetInt32(_.BuyerID);
            }
            if ((false == reader.IsDBNull(_.BuyerName)))
            {
                this._BuyerName = reader.GetString(_.BuyerName);
            }
            if ((false == reader.IsDBNull(_.Demands)))
            {
                this._Demands = reader.GetString(_.Demands);
            }
            if ((false == reader.IsDBNull(_.CreatedEmpID)))
            {
                this._CreatedEmpID = reader.GetInt32(_.CreatedEmpID);
            }
            if ((false == reader.IsDBNull(_.CreatedEmpName)))
            {
                this._CreatedEmpName = reader.GetString(_.CreatedEmpName);
            }
            if ((false == reader.IsDBNull(_.CreatedTime)))
            {
                this._CreatedTime = reader.GetDateTime(_.CreatedTime);
            }
            if ((false == reader.IsDBNull(_.UpdatedEmpID)))
            {
                this._UpdatedEmpID = reader.GetInt32(_.UpdatedEmpID);
            }
            if ((false == reader.IsDBNull(_.UpdatedEmpName)))
            {
                this._UpdatedEmpName = reader.GetString(_.UpdatedEmpName);
            }
            if ((false == reader.IsDBNull(_.UpdatedTime)))
            {
                this._UpdatedTime = reader.GetDateTime(_.UpdatedTime);
            }
            if ((false == reader.IsDBNull(_.IsDeleted)))
            {
                this._IsDeleted = reader.GetBoolean(_.IsDeleted);
            }
        }

        public override int GetHashCode()
        {
            return base.GetHashCode();
        }

        public override bool Equals(object obj)
        {
            if ((obj == null))
            {
                return false;
            }
            if ((false == typeof(ORD_PurchaseNotice).IsAssignableFrom(obj.GetType())))
            {
                return false;
            }
            if ((((object)(this)) == ((object)(obj))))
            {
                return true;
            }
            return false;
        }

        public class _
        {

            /// <summary>
            /// 表示选择所有列，与*等同
            /// </summary>
            public static AllField All = new AllField<ORD_PurchaseNotice>();

            /// <summary>
            ///  - 字段名：NoticeID - 数据类型：Int32?
            /// </summary>
            public static Field NoticeID = new Field<ORD_PurchaseNotice>("NoticeID");
            /// <summary>
            ///  - 字段名：NoticeGuid - 数据类型：Guid?
            /// </summary>
            public static Field NoticeGuid = new Field<ORD_PurchaseNotice>("NoticeGuid");
            /// <summary>
            ///  - 字段名：SOGuid - 数据类型：Guid?
            /// </summary>
            public static Field SOGuid = new Field<ORD_PurchaseNotice>("SOGuid");
            /// <summary>
            ///  - 字段名：SOLineGuid - 数据类型：Guid?
            /// </summary>
            public static Field SOLineGuid = new Field<ORD_PurchaseNotice>("SOLineGuid");
            /// <summary>
            ///  - 字段名：NoticeQty - 数据类型：Int32?
            /// </summary>
            public static Field NoticeQty = new Field<ORD_PurchaseNotice>("NoticeQty");
            /// <summary>
            /// 采购数量 - 字段名：PurchaseQty - 数据类型：Int32?
            /// </summary>
            public static Field PurchaseQty = new Field<ORD_PurchaseNotice>("PurchaseQty");
            /// <summary>
            ///  - 字段名：BuyerID - 数据类型：Int32?
            /// </summary>
            public static Field BuyerID = new Field<ORD_PurchaseNotice>("BuyerID");
            /// <summary>
            ///  - 字段名：BuyerName - 数据类型：String
            /// </summary>
            public static Field BuyerName = new Field<ORD_PurchaseNotice>("BuyerName");
            /// <summary>
            /// 采购要求 - 字段名：Demands - 数据类型：String
            /// </summary>
            public static Field Demands = new Field<ORD_PurchaseNotice>("Demands");
            /// <summary>
            ///  - 字段名：CreatedEmpID - 数据类型：Int32?
            /// </summary>
            public static Field CreatedEmpID = new Field<ORD_PurchaseNotice>("CreatedEmpID");
            /// <summary>
            ///  - 字段名：CreatedEmpName - 数据类型：String
            /// </summary>
            public static Field CreatedEmpName = new Field<ORD_PurchaseNotice>("CreatedEmpName");
            /// <summary>
            ///  - 字段名：CreatedTime - 数据类型：DateTime?
            /// </summary>
            public static Field CreatedTime = new Field<ORD_PurchaseNotice>("CreatedTime");
            /// <summary>
            ///  - 字段名：UpdatedEmpID - 数据类型：Int32?
            /// </summary>
            public static Field UpdatedEmpID = new Field<ORD_PurchaseNotice>("UpdatedEmpID");
            /// <summary>
            ///  - 字段名：UpdatedEmpName - 数据类型：String
            /// </summary>
            public static Field UpdatedEmpName = new Field<ORD_PurchaseNotice>("UpdatedEmpName");
            /// <summary>
            ///  - 字段名：UpdatedTime - 数据类型：DateTime?
            /// </summary>
            public static Field UpdatedTime = new Field<ORD_PurchaseNotice>("UpdatedTime");
            /// <summary>
            ///  - 字段名：IsDeleted - 数据类型：Boolean?
            /// </summary>
            public static Field IsDeleted = new Field<ORD_PurchaseNotice>("IsDeleted");
        }
    }
}
