//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by CodeSmith Template.
//
//     Creater: David
//     Date:    2015/3/4
//     Time:    13:56
//     Version: 4.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

/// <summary>
/// CodeSmith自动生成的实体
/// </summary>
namespace ZNLCRM.Entity.DBModel
{	
	using System;
	using MySoft.Data;
	using ZNLCRM.Utility;
    using ZNLFrame.Entity;
    /// <summary>
    /// 表名：ORD_SalesOrder 主键列：SOID
    /// </summary>
    [SerializableAttribute()]
	public partial class ORD_SalesOrder : BaseEntity
	{
		#region Private Properties
		
		private Int32 _SOID;
		private Guid? _SOGuid;
		private Guid? _GCompanyID;
		private String _BillType;
		private String _BillNo;
		private DateTime? _SODate;
		private String _PINumber;
		private String _PONumber;
		private String _CONumber;
		private Int32? _CustomerID;
		private String _CustomerName;
		private String _Address;
		private String _Contact;
		private String _Telephone;
		private String _Email;
		private String _Fax;
		private String _RecComName;
		private String _DeliveryAddress;
		private String _ReceiveContact;
		private String _ReceiveTel;
		private String _ReceiveEmail;
		private String _ReceiveFax;
		private Int32? _SalOrgID;
		private Int32? _SalDeptID;
		private Int32? _SalerID;
		private String _SalerName;
		private String _ClearingForm;
		private Int32? _ClearFormDay;
		private String _Currency;
		private Decimal? _TaxRate;
		private Decimal? _TaxAmount;
		private Decimal? _Amount;
		private Decimal? _CommissionAmount;
		private DateTime? _NeedRecAmtDate;
		private Boolean? _IsInvoiced;
		private String _InvoiceType;
		private Decimal? _DepositAmount;
		private String _CBNoOfReceipt;
		private String _CBNameOfReceipt;
		private Decimal? _BankingFee;
		private String _TransportCompany;
		private String _ShippingNo;
		private String _FreightClearForm;
		private Decimal? _Freight;
		private DateTime? _NeedDeliveryDate;
		private String _Remark;
		private String _NotifyStatus;
		private String _PurchaseStatus;
		private String _StkTakeStatus;
		private String _StkInStatus;
		private String _StkOutOccStatus;
		private String _StkOutStatus;
		private String _ShipmentStatus;
		private String _ReturnOccStatus;
		private String _ReturnStatus;
		private String _ReceivableStatus;
		private Int32? _CreatedEmpID;
		private String _CreatedEmpName;
		private DateTime? _CreatedTime;
		private Int32? _UpdatedEmpID;
		private String _UpdatedEmpName;
		private DateTime? _UpdatedTime;
		private String _Status;
		private String _ApproveStatus;
		private Boolean? _CalcType;
		private Boolean? _IsCancel;
		private Boolean? _IsDeleted;
		
		#endregion
		
		#region Public Properties
		
		/// <summary>
		/// 销售订单ID.
		/// </summary>
		public Int32 SOID
		{
			get 
			{
				return _SOID;
			}
			set 
			{
				this.OnPropertyValueChange(_.SOID, _SOID , value);
				this._SOID = value;
			}
		}
		
		/// <summary>
		/// SOGuid.
		/// </summary>
		public Guid? SOGuid
		{
			get 
			{
				return this._SOGuid;
			}
			set 
			{
				this.OnPropertyValueChange(_.SOGuid, _SOGuid , value);
				this._SOGuid = value;
			}
		}

		/// <summary>
		/// 所属公司guid.
		/// </summary>
		public Guid? GCompanyID
		{
			get 
			{
				return this._GCompanyID;
			}
			set 
			{
				this.OnPropertyValueChange(_.GCompanyID, _GCompanyID , value);
				this._GCompanyID = value;
			}
		}

		/// <summary>
		/// 定单类型.
		/// </summary>
		public String BillType
		{
			get 
			{
				return this._BillType;
			}
			set 
			{
				this.OnPropertyValueChange(_.BillType, _BillType , value);
				this._BillType = value.SubStr(50);
			}
		}

		/// <summary>
		/// 销售订单编号.
		/// </summary>
		public String BillNo
		{
			get 
			{
				return this._BillNo;
			}
			set 
			{
				this.OnPropertyValueChange(_.BillNo, _BillNo , value);
				this._BillNo = value.SubStr(20);
			}
		}

		/// <summary>
		/// 合同日期.
		/// </summary>
		public DateTime? SODate
		{
			get 
			{
				return this._SODate;
			}
			set 
			{
				this.OnPropertyValueChange(_.SODate, _SODate , value);
				this._SODate = value;
			}
		}

		/// <summary>
		/// PI号码.
		/// </summary>
		public String PINumber
		{
			get 
			{
				return this._PINumber;
			}
			set 
			{
				this.OnPropertyValueChange(_.PINumber, _PINumber , value);
				this._PINumber = value.SubStr(50);
			}
		}

		/// <summary>
		/// PO号码.
		/// </summary>
		public String PONumber
		{
			get 
			{
				return this._PONumber;
			}
			set 
			{
				this.OnPropertyValueChange(_.PONumber, _PONumber , value);
				this._PONumber = value.SubStr(50);
			}
		}

		/// <summary>
		/// 客户订单号.
		/// </summary>
		public String CONumber
		{
			get 
			{
				return this._CONumber;
			}
			set 
			{
				this.OnPropertyValueChange(_.CONumber, _CONumber , value);
				this._CONumber = value.SubStr(100);
			}
		}

		/// <summary>
		/// 客户ID（公司表ID）.
		/// </summary>
		public Int32? CustomerID
		{
			get 
			{
				return this._CustomerID;
			}
			set 
			{
				this.OnPropertyValueChange(_.CustomerID, _CustomerID , value);
				this._CustomerID = value;
			}
		}

		/// <summary>
		/// 客户名称（公司表名称）.
		/// </summary>
		public String CustomerName
		{
			get 
			{
				return this._CustomerName;
			}
			set 
			{
				this.OnPropertyValueChange(_.CustomerName, _CustomerName , value);
				this._CustomerName = value.SubStr(200);
			}
		}

		/// <summary>
		/// 客户地址.
		/// </summary>
		public String Address
		{
			get 
			{
				return this._Address;
			}
			set 
			{
				this.OnPropertyValueChange(_.Address, _Address , value);
				this._Address = value.SubStr(200);
			}
		}

		/// <summary>
		/// 客户联系人.
		/// </summary>
		public String Contact
		{
			get 
			{
				return this._Contact;
			}
			set 
			{
				this.OnPropertyValueChange(_.Contact, _Contact , value);
				this._Contact = value.SubStr(50);
			}
		}

		/// <summary>
		/// 联系电话（固话或手机）.
		/// </summary>
		public String Telephone
		{
			get 
			{
				return this._Telephone;
			}
			set 
			{
				this.OnPropertyValueChange(_.Telephone, _Telephone , value);
				this._Telephone = value.SubStr(50);
			}
		}

		/// <summary>
		/// 客户EMAIL.
		/// </summary>
		public String Email
		{
			get 
			{
				return this._Email;
			}
			set 
			{
				this.OnPropertyValueChange(_.Email, _Email , value);
				this._Email = value.SubStr(100);
			}
		}

		/// <summary>
		/// .
		/// </summary>
		public String Fax
		{
			get 
			{
				return this._Fax;
			}
			set 
			{
				this.OnPropertyValueChange(_.Fax, _Fax , value);
				this._Fax = value.SubStr(60);
			}
		}

		/// <summary>
		/// 收货公司.
		/// </summary>
		public String RecComName
		{
			get 
			{
				return this._RecComName;
			}
			set 
			{
				this.OnPropertyValueChange(_.RecComName, _RecComName , value);
				this._RecComName = value.SubStr(120);
			}
		}

		/// <summary>
		/// 收货地址.
		/// </summary>
		public String DeliveryAddress
		{
			get 
			{
				return this._DeliveryAddress;
			}
			set 
			{
				this.OnPropertyValueChange(_.DeliveryAddress, _DeliveryAddress , value);
				this._DeliveryAddress = value.SubStr(200);
			}
		}

		/// <summary>
		/// 收货人.
		/// </summary>
		public String ReceiveContact
		{
			get 
			{
				return this._ReceiveContact;
			}
			set 
			{
				this.OnPropertyValueChange(_.ReceiveContact, _ReceiveContact , value);
				this._ReceiveContact = value.SubStr(50);
			}
		}

		/// <summary>
		/// 收货人联系电话.
		/// </summary>
		public String ReceiveTel
		{
			get 
			{
				return this._ReceiveTel;
			}
			set 
			{
				this.OnPropertyValueChange(_.ReceiveTel, _ReceiveTel , value);
				this._ReceiveTel = value.SubStr(50);
			}
		}

		/// <summary>
		/// 收货人EMAIL.
		/// </summary>
		public String ReceiveEmail
		{
			get 
			{
				return this._ReceiveEmail;
			}
			set 
			{
				this.OnPropertyValueChange(_.ReceiveEmail, _ReceiveEmail , value);
				this._ReceiveEmail = value.SubStr(100);
			}
		}

		/// <summary>
		/// .
		/// </summary>
		public String ReceiveFax
		{
			get 
			{
				return this._ReceiveFax;
			}
			set 
			{
				this.OnPropertyValueChange(_.ReceiveFax, _ReceiveFax , value);
				this._ReceiveFax = value.SubStr(60);
			}
		}

		/// <summary>
		/// .
		/// </summary>
		public Int32? SalOrgID
		{
			get 
			{
				return this._SalOrgID;
			}
			set 
			{
				this.OnPropertyValueChange(_.SalOrgID, _SalOrgID , value);
				this._SalOrgID = value;
			}
		}

		/// <summary>
		/// 销售部门ID.
		/// </summary>
		public Int32? SalDeptID
		{
			get 
			{
				return this._SalDeptID;
			}
			set 
			{
				this.OnPropertyValueChange(_.SalDeptID, _SalDeptID , value);
				this._SalDeptID = value;
			}
		}

		/// <summary>
		/// 销售员ID.
		/// </summary>
		public Int32? SalerID
		{
			get 
			{
				return this._SalerID;
			}
			set 
			{
				this.OnPropertyValueChange(_.SalerID, _SalerID , value);
				this._SalerID = value;
			}
		}

		/// <summary>
		/// 销售员姓名.
		/// </summary>
		public String SalerName
		{
			get 
			{
				return this._SalerName;
			}
			set 
			{
				this.OnPropertyValueChange(_.SalerName, _SalerName , value);
				this._SalerName = value.SubStr(50);
			}
		}

		/// <summary>
		/// 结算方式（用枚举）.
		/// </summary>
		public String ClearingForm
		{
			get 
			{
				return this._ClearingForm;
			}
			set 
			{
				this.OnPropertyValueChange(_.ClearingForm, _ClearingForm , value);
				this._ClearingForm = value.SubStr(20);
			}
		}

		/// <summary>
		/// 结算天数.
		/// </summary>
		public Int32? ClearFormDay
		{
			get 
			{
				return this._ClearFormDay;
			}
			set 
			{
				this.OnPropertyValueChange(_.ClearFormDay, _ClearFormDay , value);
				this._ClearFormDay = value;
			}
		}

		/// <summary>
		/// 币种.
		/// </summary>
		public String Currency
		{
			get 
			{
				return this._Currency;
			}
			set 
			{
				this.OnPropertyValueChange(_.Currency, _Currency , value);
				this._Currency = value.SubStr(10);
			}
		}

		/// <summary>
		/// 税率.
		/// </summary>
		public Decimal? TaxRate
		{
			get 
			{
				return this._TaxRate;
			}
			set 
			{
				this.OnPropertyValueChange(_.TaxRate, _TaxRate , value);
				this._TaxRate = value;
			}
		}

		/// <summary>
		/// 税金总金额.
		/// </summary>
		public Decimal? TaxAmount
		{
			get 
			{
				return this._TaxAmount;
			}
			set 
			{
				this.OnPropertyValueChange(_.TaxAmount, _TaxAmount , value);
				this._TaxAmount = value;
			}
		}

		/// <summary>
		/// 订单金额.
		/// </summary>
		public Decimal? Amount
		{
			get 
			{
				return this._Amount;
			}
			set 
			{
				this.OnPropertyValueChange(_.Amount, _Amount , value);
				this._Amount = value;
			}
		}

		/// <summary>
		/// 佣金金额.
		/// </summary>
		public Decimal? CommissionAmount
		{
			get 
			{
				return this._CommissionAmount;
			}
			set 
			{
				this.OnPropertyValueChange(_.CommissionAmount, _CommissionAmount , value);
				this._CommissionAmount = value;
			}
		}

		/// <summary>
		/// 应收款日期.
		/// </summary>
		public DateTime? NeedRecAmtDate
		{
			get 
			{
				return this._NeedRecAmtDate;
			}
			set 
			{
				this.OnPropertyValueChange(_.NeedRecAmtDate, _NeedRecAmtDate , value);
				this._NeedRecAmtDate = value;
			}
		}

		/// <summary>
		/// 是否开票.
		/// </summary>
		public Boolean? IsInvoiced
		{
			get 
			{
				return this._IsInvoiced;
			}
			set 
			{
				this.OnPropertyValueChange(_.IsInvoiced, _IsInvoiced , value);
				this._IsInvoiced = value;
			}
		}

		/// <summary>
		/// 开票类型.
		/// </summary>
		public String InvoiceType
		{
			get 
			{
				return this._InvoiceType;
			}
			set 
			{
				this.OnPropertyValueChange(_.InvoiceType, _InvoiceType , value);
				this._InvoiceType = value.SubStr(50);
			}
		}

		/// <summary>
		/// 预收定金.
		/// </summary>
		public Decimal? DepositAmount
		{
			get 
			{
				return this._DepositAmount;
			}
			set 
			{
				this.OnPropertyValueChange(_.DepositAmount, _DepositAmount , value);
				this._DepositAmount = value;
			}
		}

		/// <summary>
		/// 收款银行帐号.
		/// </summary>
		public String CBNoOfReceipt
		{
			get 
			{
				return this._CBNoOfReceipt;
			}
			set 
			{
				this.OnPropertyValueChange(_.CBNoOfReceipt, _CBNoOfReceipt , value);
				this._CBNoOfReceipt = value.SubStr(50);
			}
		}

		/// <summary>
		/// 收款银行.
		/// </summary>
		public String CBNameOfReceipt
		{
			get 
			{
				return this._CBNameOfReceipt;
			}
			set 
			{
				this.OnPropertyValueChange(_.CBNameOfReceipt, _CBNameOfReceipt , value);
				this._CBNameOfReceipt = value.SubStr(50);
			}
		}

		/// <summary>
		/// 银行手续费.
		/// </summary>
		public Decimal? BankingFee
		{
			get 
			{
				return this._BankingFee;
			}
			set 
			{
				this.OnPropertyValueChange(_.BankingFee, _BankingFee , value);
				this._BankingFee = value;
			}
		}

		/// <summary>
		/// 货运公司.
		/// </summary>
		public String TransportCompany
		{
			get 
			{
				return this._TransportCompany;
			}
			set 
			{
				this.OnPropertyValueChange(_.TransportCompany, _TransportCompany , value);
				this._TransportCompany = value.SubStr(50);
			}
		}

		/// <summary>
		/// 货运单号.
		/// </summary>
		public String ShippingNo
		{
			get 
			{
				return this._ShippingNo;
			}
			set 
			{
				this.OnPropertyValueChange(_.ShippingNo, _ShippingNo , value);
				this._ShippingNo = value.SubStr(100);
			}
		}

		/// <summary>
		/// 运费结算.
		/// </summary>
		public String FreightClearForm
		{
			get 
			{
				return this._FreightClearForm;
			}
			set 
			{
				this.OnPropertyValueChange(_.FreightClearForm, _FreightClearForm , value);
				this._FreightClearForm = value.SubStr(50);
			}
		}

		/// <summary>
		/// 运费.
		/// </summary>
		public Decimal? Freight
		{
			get 
			{
				return this._Freight;
			}
			set 
			{
				this.OnPropertyValueChange(_.Freight, _Freight , value);
				this._Freight = value;
			}
		}

		/// <summary>
		/// 需发货日期.
		/// </summary>
		public DateTime? NeedDeliveryDate
		{
			get 
			{
				return this._NeedDeliveryDate;
			}
			set 
			{
				this.OnPropertyValueChange(_.NeedDeliveryDate, _NeedDeliveryDate , value);
				this._NeedDeliveryDate = value;
			}
		}

		/// <summary>
		/// 备注.
		/// </summary>
		public String Remark
		{
			get 
			{
				return this._Remark;
			}
			set 
			{
				this.OnPropertyValueChange(_.Remark, _Remark , value);
				this._Remark = value.SubStr(100);
			}
		}

		/// <summary>
		/// 通知状态.
		/// </summary>
		public String NotifyStatus
		{
			get 
			{
				return this._NotifyStatus;
			}
			set 
			{
				this.OnPropertyValueChange(_.NotifyStatus, _NotifyStatus , value);
				this._NotifyStatus = value.SubStr(10);
			}
		}

		/// <summary>
		/// 采购状态.
		/// </summary>
		public String PurchaseStatus
		{
			get 
			{
				return this._PurchaseStatus;
			}
			set 
			{
				this.OnPropertyValueChange(_.PurchaseStatus, _PurchaseStatus , value);
				this._PurchaseStatus = value.SubStr(10);
			}
		}

		/// <summary>
		/// 收货状态.
		/// </summary>
		public String StkTakeStatus
		{
			get 
			{
				return this._StkTakeStatus;
			}
			set 
			{
				this.OnPropertyValueChange(_.StkTakeStatus, _StkTakeStatus , value);
				this._StkTakeStatus = value.SubStr(10);
			}
		}

		/// <summary>
		/// 入库状态.
		/// </summary>
		public String StkInStatus
		{
			get 
			{
				return this._StkInStatus;
			}
			set 
			{
				this.OnPropertyValueChange(_.StkInStatus, _StkInStatus , value);
				this._StkInStatus = value.SubStr(10);
			}
		}

		/// <summary>
		/// 出库占有状态.
		/// </summary>
		public String StkOutOccStatus
		{
			get 
			{
				return this._StkOutOccStatus;
			}
			set 
			{
				this.OnPropertyValueChange(_.StkOutOccStatus, _StkOutOccStatus , value);
				this._StkOutOccStatus = value.SubStr(10);
			}
		}

		/// <summary>
		/// 出库状态.
		/// </summary>
		public String StkOutStatus
		{
			get 
			{
				return this._StkOutStatus;
			}
			set 
			{
				this.OnPropertyValueChange(_.StkOutStatus, _StkOutStatus , value);
				this._StkOutStatus = value.SubStr(10);
			}
		}

		/// <summary>
		/// 发运状态.
		/// </summary>
		public String ShipmentStatus
		{
			get 
			{
				return this._ShipmentStatus;
			}
			set 
			{
				this.OnPropertyValueChange(_.ShipmentStatus, _ShipmentStatus , value);
				this._ShipmentStatus = value.SubStr(10);
			}
		}

		/// <summary>
		/// 退货占有状态.
		/// </summary>
		public String ReturnOccStatus
		{
			get 
			{
				return this._ReturnOccStatus;
			}
			set 
			{
				this.OnPropertyValueChange(_.ReturnOccStatus, _ReturnOccStatus , value);
				this._ReturnOccStatus = value.SubStr(10);
			}
		}

		/// <summary>
		/// 退货状态.
		/// </summary>
		public String ReturnStatus
		{
			get 
			{
				return this._ReturnStatus;
			}
			set 
			{
				this.OnPropertyValueChange(_.ReturnStatus, _ReturnStatus , value);
				this._ReturnStatus = value.SubStr(10);
			}
		}

		/// <summary>
		/// 收款状态.
		/// </summary>
		public String ReceivableStatus
		{
			get 
			{
				return this._ReceivableStatus;
			}
			set 
			{
				this.OnPropertyValueChange(_.ReceivableStatus, _ReceivableStatus , value);
				this._ReceivableStatus = value.SubStr(10);
			}
		}

		/// <summary>
		/// 创建人.
		/// </summary>
		public Int32? CreatedEmpID
		{
			get 
			{
				return this._CreatedEmpID;
			}
			set 
			{
				this.OnPropertyValueChange(_.CreatedEmpID, _CreatedEmpID , value);
				this._CreatedEmpID = value;
			}
		}

		/// <summary>
		/// 创建人姓名.
		/// </summary>
		public String CreatedEmpName
		{
			get 
			{
				return this._CreatedEmpName;
			}
			set 
			{
				this.OnPropertyValueChange(_.CreatedEmpName, _CreatedEmpName , value);
				this._CreatedEmpName = value.SubStr(50);
			}
		}

		/// <summary>
		/// 创建时间.
		/// </summary>
		public DateTime? CreatedTime
		{
			get 
			{
				return this._CreatedTime;
			}
			set 
			{
				this.OnPropertyValueChange(_.CreatedTime, _CreatedTime , value);
				this._CreatedTime = value;
			}
		}

		/// <summary>
		/// 更新人.
		/// </summary>
		public Int32? UpdatedEmpID
		{
			get 
			{
				return this._UpdatedEmpID;
			}
			set 
			{
				this.OnPropertyValueChange(_.UpdatedEmpID, _UpdatedEmpID , value);
				this._UpdatedEmpID = value;
			}
		}

		/// <summary>
		/// 更新人.
		/// </summary>
		public String UpdatedEmpName
		{
			get 
			{
				return this._UpdatedEmpName;
			}
			set 
			{
				this.OnPropertyValueChange(_.UpdatedEmpName, _UpdatedEmpName , value);
				this._UpdatedEmpName = value.SubStr(50);
			}
		}

		/// <summary>
		/// 更新时间.
		/// </summary>
		public DateTime? UpdatedTime
		{
			get 
			{
				return this._UpdatedTime;
			}
			set 
			{
				this.OnPropertyValueChange(_.UpdatedTime, _UpdatedTime , value);
				this._UpdatedTime = value;
			}
		}

		/// <summary>
		/// 单据状态.
		/// </summary>
		public String Status
		{
			get 
			{
				return this._Status;
			}
			set 
			{
				this.OnPropertyValueChange(_.Status, _Status , value);
				this._Status = value.SubStr(10);
			}
		}

		/// <summary>
		/// 审批状态.
		/// </summary>
		public String ApproveStatus
		{
			get 
			{
				return this._ApproveStatus;
			}
			set 
			{
				this.OnPropertyValueChange(_.ApproveStatus, _ApproveStatus , value);
				this._ApproveStatus = value.SubStr(20);
			}
		}

		/// <summary>
		/// 计算方式（0.未含税算含税,1.含税算未含税）.
		/// </summary>
		public Boolean? CalcType
		{
			get 
			{
				return this._CalcType;
			}
			set 
			{
				this.OnPropertyValueChange(_.CalcType, _CalcType , value);
				this._CalcType = value;
			}
		}

		/// <summary>
		/// 是否取消.
		/// </summary>
		public Boolean? IsCancel
		{
			get 
			{
				return this._IsCancel;
			}
			set 
			{
				this.OnPropertyValueChange(_.IsCancel, _IsCancel , value);
				this._IsCancel = value;
			}
		}

		/// <summary>
		/// 是否删除.
		/// </summary>
		public Boolean? IsDeleted
		{
			get 
			{
				return this._IsDeleted;
			}
			set 
			{
				this.OnPropertyValueChange(_.IsDeleted, _IsDeleted , value);
				this._IsDeleted = value;
			}
		}
		
		#endregion
	    /// <summary>
        /// 获取实体对应的表名
        /// </summary>
        protected override Table GetTable() {
            return new Table< ORD_SalesOrder >("ORD_SalesOrder");
        }
		
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        protected override Field GetIdentityField() {
            return _.SOID;
        }  			
		
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        protected override Field[] GetPrimaryKeyFields() {
            return new Field[] {
				_.SOID
			};
        }
			
	    /// <summary>
        /// 获取列信息
        /// </summary>
        protected override Field[] GetFields() {
            return new Field[] {
				_.SOID,		
				_.SOGuid,		
				_.GCompanyID,		
				_.BillType,		
				_.BillNo,		
				_.SODate,		
				_.PINumber,		
				_.PONumber,		
				_.CONumber,		
				_.CustomerID,		
				_.CustomerName,		
				_.Address,		
				_.Contact,		
				_.Telephone,		
				_.Email,		
				_.Fax,		
				_.RecComName,		
				_.DeliveryAddress,		
				_.ReceiveContact,		
				_.ReceiveTel,		
				_.ReceiveEmail,		
				_.ReceiveFax,		
				_.SalOrgID,		
				_.SalDeptID,		
				_.SalerID,		
				_.SalerName,		
				_.ClearingForm,		
				_.ClearFormDay,		
				_.Currency,		
				_.TaxRate,		
				_.TaxAmount,		
				_.Amount,		
				_.CommissionAmount,		
				_.NeedRecAmtDate,		
				_.IsInvoiced,		
				_.InvoiceType,		
				_.DepositAmount,		
				_.CBNoOfReceipt,		
				_.CBNameOfReceipt,		
				_.BankingFee,		
				_.TransportCompany,		
				_.ShippingNo,		
				_.FreightClearForm,		
				_.Freight,		
				_.NeedDeliveryDate,		
				_.Remark,		
				_.NotifyStatus,		
				_.PurchaseStatus,		
				_.StkTakeStatus,		
				_.StkInStatus,		
				_.StkOutOccStatus,		
				_.StkOutStatus,		
				_.ShipmentStatus,		
				_.ReturnOccStatus,		
				_.ReturnStatus,		
				_.ReceivableStatus,		
				_.CreatedEmpID,		
				_.CreatedEmpName,		
				_.CreatedTime,		
				_.UpdatedEmpID,		
				_.UpdatedEmpName,		
				_.UpdatedTime,		
				_.Status,		
				_.ApproveStatus,		
				_.CalcType,		
				_.IsCancel,		
				_.IsDeleted		
			};
		}
		
	    /// <summary>
        /// 获取列数据
        /// </summary>
        protected override object[] GetValues() {
            return new object[] {
				this._SOID,		
				this._SOGuid,		
				this._GCompanyID,		
				this._BillType,		
				this._BillNo,		
				this._SODate,		
				this._PINumber,		
				this._PONumber,		
				this._CONumber,		
				this._CustomerID,		
				this._CustomerName,		
				this._Address,		
				this._Contact,		
				this._Telephone,		
				this._Email,		
				this._Fax,		
				this._RecComName,		
				this._DeliveryAddress,		
				this._ReceiveContact,		
				this._ReceiveTel,		
				this._ReceiveEmail,		
				this._ReceiveFax,		
				this._SalOrgID,		
				this._SalDeptID,		
				this._SalerID,		
				this._SalerName,		
				this._ClearingForm,		
				this._ClearFormDay,		
				this._Currency,		
				this._TaxRate,		
				this._TaxAmount,		
				this._Amount,		
				this._CommissionAmount,		
				this._NeedRecAmtDate,		
				this._IsInvoiced,		
				this._InvoiceType,		
				this._DepositAmount,		
				this._CBNoOfReceipt,		
				this._CBNameOfReceipt,		
				this._BankingFee,		
				this._TransportCompany,		
				this._ShippingNo,		
				this._FreightClearForm,		
				this._Freight,		
				this._NeedDeliveryDate,		
				this._Remark,		
				this._NotifyStatus,		
				this._PurchaseStatus,		
				this._StkTakeStatus,		
				this._StkInStatus,		
				this._StkOutOccStatus,		
				this._StkOutStatus,		
				this._ShipmentStatus,		
				this._ReturnOccStatus,		
				this._ReturnStatus,		
				this._ReceivableStatus,		
				this._CreatedEmpID,		
				this._CreatedEmpName,		
				this._CreatedTime,		
				this._UpdatedEmpID,		
				this._UpdatedEmpName,		
				this._UpdatedTime,		
				this._Status,		
				this._ApproveStatus,		
				this._CalcType,		
				this._IsCancel,		
				this._IsDeleted		
			};
		}
		
	    /// <summary>
        /// 给当前实体赋值
        /// </summary>
        protected override void SetValues(IRowReader reader) {
            if ((false == reader.IsDBNull(_.SOID))) {
                this._SOID = reader.GetInt32(_.SOID);
            }
            if ((false == reader.IsDBNull(_.SOGuid))) {
                this._SOGuid = reader.GetGuid(_.SOGuid);
            }
            if ((false == reader.IsDBNull(_.GCompanyID))) {
                this._GCompanyID = reader.GetGuid(_.GCompanyID);
            }
            if ((false == reader.IsDBNull(_.BillType))) {
                this._BillType = reader.GetString(_.BillType);
            }
            if ((false == reader.IsDBNull(_.BillNo))) {
                this._BillNo = reader.GetString(_.BillNo);
            }
            if ((false == reader.IsDBNull(_.SODate))) {
                this._SODate = reader.GetDateTime(_.SODate);
            }
            if ((false == reader.IsDBNull(_.PINumber))) {
                this._PINumber = reader.GetString(_.PINumber);
            }
            if ((false == reader.IsDBNull(_.PONumber))) {
                this._PONumber = reader.GetString(_.PONumber);
            }
            if ((false == reader.IsDBNull(_.CONumber))) {
                this._CONumber = reader.GetString(_.CONumber);
            }
            if ((false == reader.IsDBNull(_.CustomerID))) {
                this._CustomerID = reader.GetInt32(_.CustomerID);
            }
            if ((false == reader.IsDBNull(_.CustomerName))) {
                this._CustomerName = reader.GetString(_.CustomerName);
            }
            if ((false == reader.IsDBNull(_.Address))) {
                this._Address = reader.GetString(_.Address);
            }
            if ((false == reader.IsDBNull(_.Contact))) {
                this._Contact = reader.GetString(_.Contact);
            }
            if ((false == reader.IsDBNull(_.Telephone))) {
                this._Telephone = reader.GetString(_.Telephone);
            }
            if ((false == reader.IsDBNull(_.Email))) {
                this._Email = reader.GetString(_.Email);
            }
            if ((false == reader.IsDBNull(_.Fax))) {
                this._Fax = reader.GetString(_.Fax);
            }
            if ((false == reader.IsDBNull(_.RecComName))) {
                this._RecComName = reader.GetString(_.RecComName);
            }
            if ((false == reader.IsDBNull(_.DeliveryAddress))) {
                this._DeliveryAddress = reader.GetString(_.DeliveryAddress);
            }
            if ((false == reader.IsDBNull(_.ReceiveContact))) {
                this._ReceiveContact = reader.GetString(_.ReceiveContact);
            }
            if ((false == reader.IsDBNull(_.ReceiveTel))) {
                this._ReceiveTel = reader.GetString(_.ReceiveTel);
            }
            if ((false == reader.IsDBNull(_.ReceiveEmail))) {
                this._ReceiveEmail = reader.GetString(_.ReceiveEmail);
            }
            if ((false == reader.IsDBNull(_.ReceiveFax))) {
                this._ReceiveFax = reader.GetString(_.ReceiveFax);
            }
            if ((false == reader.IsDBNull(_.SalOrgID))) {
                this._SalOrgID = reader.GetInt32(_.SalOrgID);
            }
            if ((false == reader.IsDBNull(_.SalDeptID))) {
                this._SalDeptID = reader.GetInt32(_.SalDeptID);
            }
            if ((false == reader.IsDBNull(_.SalerID))) {
                this._SalerID = reader.GetInt32(_.SalerID);
            }
            if ((false == reader.IsDBNull(_.SalerName))) {
                this._SalerName = reader.GetString(_.SalerName);
            }
            if ((false == reader.IsDBNull(_.ClearingForm))) {
                this._ClearingForm = reader.GetString(_.ClearingForm);
            }
            if ((false == reader.IsDBNull(_.ClearFormDay))) {
                this._ClearFormDay = reader.GetInt32(_.ClearFormDay);
            }
            if ((false == reader.IsDBNull(_.Currency))) {
                this._Currency = reader.GetString(_.Currency);
            }
            if ((false == reader.IsDBNull(_.TaxRate))) {
                this._TaxRate = reader.GetDecimal(_.TaxRate);
            }
            if ((false == reader.IsDBNull(_.TaxAmount))) {
                this._TaxAmount = reader.GetDecimal(_.TaxAmount);
            }
            if ((false == reader.IsDBNull(_.Amount))) {
                this._Amount = reader.GetDecimal(_.Amount);
            }
            if ((false == reader.IsDBNull(_.CommissionAmount))) {
                this._CommissionAmount = reader.GetDecimal(_.CommissionAmount);
            }
            if ((false == reader.IsDBNull(_.NeedRecAmtDate))) {
                this._NeedRecAmtDate = reader.GetDateTime(_.NeedRecAmtDate);
            }
            if ((false == reader.IsDBNull(_.IsInvoiced))) {
                this._IsInvoiced = reader.GetBoolean(_.IsInvoiced);
            }
            if ((false == reader.IsDBNull(_.InvoiceType))) {
                this._InvoiceType = reader.GetString(_.InvoiceType);
            }
            if ((false == reader.IsDBNull(_.DepositAmount))) {
                this._DepositAmount = reader.GetDecimal(_.DepositAmount);
            }
            if ((false == reader.IsDBNull(_.CBNoOfReceipt))) {
                this._CBNoOfReceipt = reader.GetString(_.CBNoOfReceipt);
            }
            if ((false == reader.IsDBNull(_.CBNameOfReceipt))) {
                this._CBNameOfReceipt = reader.GetString(_.CBNameOfReceipt);
            }
            if ((false == reader.IsDBNull(_.BankingFee))) {
                this._BankingFee = reader.GetDecimal(_.BankingFee);
            }
            if ((false == reader.IsDBNull(_.TransportCompany))) {
                this._TransportCompany = reader.GetString(_.TransportCompany);
            }
            if ((false == reader.IsDBNull(_.ShippingNo))) {
                this._ShippingNo = reader.GetString(_.ShippingNo);
            }
            if ((false == reader.IsDBNull(_.FreightClearForm))) {
                this._FreightClearForm = reader.GetString(_.FreightClearForm);
            }
            if ((false == reader.IsDBNull(_.Freight))) {
                this._Freight = reader.GetDecimal(_.Freight);
            }
            if ((false == reader.IsDBNull(_.NeedDeliveryDate))) {
                this._NeedDeliveryDate = reader.GetDateTime(_.NeedDeliveryDate);
            }
            if ((false == reader.IsDBNull(_.Remark))) {
                this._Remark = reader.GetString(_.Remark);
            }
            if ((false == reader.IsDBNull(_.NotifyStatus))) {
                this._NotifyStatus = reader.GetString(_.NotifyStatus);
            }
            if ((false == reader.IsDBNull(_.PurchaseStatus))) {
                this._PurchaseStatus = reader.GetString(_.PurchaseStatus);
            }
            if ((false == reader.IsDBNull(_.StkTakeStatus))) {
                this._StkTakeStatus = reader.GetString(_.StkTakeStatus);
            }
            if ((false == reader.IsDBNull(_.StkInStatus))) {
                this._StkInStatus = reader.GetString(_.StkInStatus);
            }
            if ((false == reader.IsDBNull(_.StkOutOccStatus))) {
                this._StkOutOccStatus = reader.GetString(_.StkOutOccStatus);
            }
            if ((false == reader.IsDBNull(_.StkOutStatus))) {
                this._StkOutStatus = reader.GetString(_.StkOutStatus);
            }
            if ((false == reader.IsDBNull(_.ShipmentStatus))) {
                this._ShipmentStatus = reader.GetString(_.ShipmentStatus);
            }
            if ((false == reader.IsDBNull(_.ReturnOccStatus))) {
                this._ReturnOccStatus = reader.GetString(_.ReturnOccStatus);
            }
            if ((false == reader.IsDBNull(_.ReturnStatus))) {
                this._ReturnStatus = reader.GetString(_.ReturnStatus);
            }
            if ((false == reader.IsDBNull(_.ReceivableStatus))) {
                this._ReceivableStatus = reader.GetString(_.ReceivableStatus);
            }
            if ((false == reader.IsDBNull(_.CreatedEmpID))) {
                this._CreatedEmpID = reader.GetInt32(_.CreatedEmpID);
            }
            if ((false == reader.IsDBNull(_.CreatedEmpName))) {
                this._CreatedEmpName = reader.GetString(_.CreatedEmpName);
            }
            if ((false == reader.IsDBNull(_.CreatedTime))) {
                this._CreatedTime = reader.GetDateTime(_.CreatedTime);
            }
            if ((false == reader.IsDBNull(_.UpdatedEmpID))) {
                this._UpdatedEmpID = reader.GetInt32(_.UpdatedEmpID);
            }
            if ((false == reader.IsDBNull(_.UpdatedEmpName))) {
                this._UpdatedEmpName = reader.GetString(_.UpdatedEmpName);
            }
            if ((false == reader.IsDBNull(_.UpdatedTime))) {
                this._UpdatedTime = reader.GetDateTime(_.UpdatedTime);
            }
            if ((false == reader.IsDBNull(_.Status))) {
                this._Status = reader.GetString(_.Status);
            }
            if ((false == reader.IsDBNull(_.ApproveStatus))) {
                this._ApproveStatus = reader.GetString(_.ApproveStatus);
            }
            if ((false == reader.IsDBNull(_.CalcType))) {
                this._CalcType = reader.GetBoolean(_.CalcType);
            }
            if ((false == reader.IsDBNull(_.IsCancel))) {
                this._IsCancel = reader.GetBoolean(_.IsCancel);
            }
            if ((false == reader.IsDBNull(_.IsDeleted))) {
                this._IsDeleted = reader.GetBoolean(_.IsDeleted);
            }
		}
		
	    public override int GetHashCode() {
            return base.GetHashCode();
        }
        
        public override bool Equals(object obj) {
            if ((obj == null)) {
                return false;
            }
            if ((false == typeof(ORD_SalesOrder).IsAssignableFrom(obj.GetType()))) {
                return false;
            }
            if ((((object)(this)) == ((object)(obj)))) {
                return true;
            }
            return false;
        }
		
        public class _ {
                
            /// <summary>
            /// 表示选择所有列，与*等同
            /// </summary>
            public static AllField All = new AllField< ORD_SalesOrder >();
			
		    /// <summary>
            /// 销售订单ID - 字段名：SOID - 数据类型：Int32?
            /// </summary>
            public static Field SOID = new Field< ORD_SalesOrder >("SOID");
		    /// <summary>
            /// SOGuid - 字段名：SOGuid - 数据类型：Guid?
            /// </summary>
            public static Field SOGuid = new Field< ORD_SalesOrder >("SOGuid");
		    /// <summary>
            /// 所属公司guid - 字段名：GCompanyID - 数据类型：Guid?
            /// </summary>
            public static Field GCompanyID = new Field< ORD_SalesOrder >("GCompanyID");
		    /// <summary>
            /// 定单类型 - 字段名：BillType - 数据类型：String
            /// </summary>
            public static Field BillType = new Field< ORD_SalesOrder >("BillType");
		    /// <summary>
            /// 销售订单编号 - 字段名：BillNo - 数据类型：String
            /// </summary>
            public static Field BillNo = new Field< ORD_SalesOrder >("BillNo");
		    /// <summary>
            /// 合同日期 - 字段名：SODate - 数据类型：DateTime?
            /// </summary>
            public static Field SODate = new Field< ORD_SalesOrder >("SODate");
		    /// <summary>
            /// PI号码 - 字段名：PINumber - 数据类型：String
            /// </summary>
            public static Field PINumber = new Field< ORD_SalesOrder >("PINumber");
		    /// <summary>
            /// PO号码 - 字段名：PONumber - 数据类型：String
            /// </summary>
            public static Field PONumber = new Field< ORD_SalesOrder >("PONumber");
		    /// <summary>
            /// 客户订单号 - 字段名：CONumber - 数据类型：String
            /// </summary>
            public static Field CONumber = new Field< ORD_SalesOrder >("CONumber");
		    /// <summary>
            /// 客户ID（公司表ID） - 字段名：CustomerID - 数据类型：Int32?
            /// </summary>
            public static Field CustomerID = new Field< ORD_SalesOrder >("CustomerID");
		    /// <summary>
            /// 客户名称（公司表名称） - 字段名：CustomerName - 数据类型：String
            /// </summary>
            public static Field CustomerName = new Field< ORD_SalesOrder >("CustomerName");
		    /// <summary>
            /// 客户地址 - 字段名：Address - 数据类型：String
            /// </summary>
            public static Field Address = new Field< ORD_SalesOrder >("Address");
		    /// <summary>
            /// 客户联系人 - 字段名：Contact - 数据类型：String
            /// </summary>
            public static Field Contact = new Field< ORD_SalesOrder >("Contact");
		    /// <summary>
            /// 联系电话（固话或手机） - 字段名：Telephone - 数据类型：String
            /// </summary>
            public static Field Telephone = new Field< ORD_SalesOrder >("Telephone");
		    /// <summary>
            /// 客户EMAIL - 字段名：Email - 数据类型：String
            /// </summary>
            public static Field Email = new Field< ORD_SalesOrder >("Email");
		    /// <summary>
            ///  - 字段名：Fax - 数据类型：String
            /// </summary>
            public static Field Fax = new Field< ORD_SalesOrder >("Fax");
		    /// <summary>
            /// 收货公司 - 字段名：RecComName - 数据类型：String
            /// </summary>
            public static Field RecComName = new Field< ORD_SalesOrder >("RecComName");
		    /// <summary>
            /// 收货地址 - 字段名：DeliveryAddress - 数据类型：String
            /// </summary>
            public static Field DeliveryAddress = new Field< ORD_SalesOrder >("DeliveryAddress");
		    /// <summary>
            /// 收货人 - 字段名：ReceiveContact - 数据类型：String
            /// </summary>
            public static Field ReceiveContact = new Field< ORD_SalesOrder >("ReceiveContact");
		    /// <summary>
            /// 收货人联系电话 - 字段名：ReceiveTel - 数据类型：String
            /// </summary>
            public static Field ReceiveTel = new Field< ORD_SalesOrder >("ReceiveTel");
		    /// <summary>
            /// 收货人EMAIL - 字段名：ReceiveEmail - 数据类型：String
            /// </summary>
            public static Field ReceiveEmail = new Field< ORD_SalesOrder >("ReceiveEmail");
		    /// <summary>
            ///  - 字段名：ReceiveFax - 数据类型：String
            /// </summary>
            public static Field ReceiveFax = new Field< ORD_SalesOrder >("ReceiveFax");
		    /// <summary>
            ///  - 字段名：SalOrgID - 数据类型：Int32?
            /// </summary>
            public static Field SalOrgID = new Field< ORD_SalesOrder >("SalOrgID");
		    /// <summary>
            /// 销售部门ID - 字段名：SalDeptID - 数据类型：Int32?
            /// </summary>
            public static Field SalDeptID = new Field< ORD_SalesOrder >("SalDeptID");
		    /// <summary>
            /// 销售员ID - 字段名：SalerID - 数据类型：Int32?
            /// </summary>
            public static Field SalerID = new Field< ORD_SalesOrder >("SalerID");
		    /// <summary>
            /// 销售员姓名 - 字段名：SalerName - 数据类型：String
            /// </summary>
            public static Field SalerName = new Field< ORD_SalesOrder >("SalerName");
		    /// <summary>
            /// 结算方式（用枚举） - 字段名：ClearingForm - 数据类型：String
            /// </summary>
            public static Field ClearingForm = new Field< ORD_SalesOrder >("ClearingForm");
		    /// <summary>
            /// 结算天数 - 字段名：ClearFormDay - 数据类型：Int32?
            /// </summary>
            public static Field ClearFormDay = new Field< ORD_SalesOrder >("ClearFormDay");
		    /// <summary>
            /// 币种 - 字段名：Currency - 数据类型：String
            /// </summary>
            public static Field Currency = new Field< ORD_SalesOrder >("Currency");
		    /// <summary>
            /// 税率 - 字段名：TaxRate - 数据类型：Decimal?
            /// </summary>
            public static Field TaxRate = new Field< ORD_SalesOrder >("TaxRate");
		    /// <summary>
            /// 税金总金额 - 字段名：TaxAmount - 数据类型：Decimal?
            /// </summary>
            public static Field TaxAmount = new Field< ORD_SalesOrder >("TaxAmount");
		    /// <summary>
            /// 订单金额 - 字段名：Amount - 数据类型：Decimal?
            /// </summary>
            public static Field Amount = new Field< ORD_SalesOrder >("Amount");
		    /// <summary>
            /// 佣金金额 - 字段名：CommissionAmount - 数据类型：Decimal?
            /// </summary>
            public static Field CommissionAmount = new Field< ORD_SalesOrder >("CommissionAmount");
		    /// <summary>
            /// 应收款日期 - 字段名：NeedRecAmtDate - 数据类型：DateTime?
            /// </summary>
            public static Field NeedRecAmtDate = new Field< ORD_SalesOrder >("NeedRecAmtDate");
		    /// <summary>
            /// 是否开票 - 字段名：IsInvoiced - 数据类型：Boolean?
            /// </summary>
            public static Field IsInvoiced = new Field< ORD_SalesOrder >("IsInvoiced");
		    /// <summary>
            /// 开票类型 - 字段名：InvoiceType - 数据类型：String
            /// </summary>
            public static Field InvoiceType = new Field< ORD_SalesOrder >("InvoiceType");
		    /// <summary>
            /// 预收定金 - 字段名：DepositAmount - 数据类型：Decimal?
            /// </summary>
            public static Field DepositAmount = new Field< ORD_SalesOrder >("DepositAmount");
		    /// <summary>
            /// 收款银行帐号 - 字段名：CBNoOfReceipt - 数据类型：String
            /// </summary>
            public static Field CBNoOfReceipt = new Field< ORD_SalesOrder >("CBNoOfReceipt");
		    /// <summary>
            /// 收款银行 - 字段名：CBNameOfReceipt - 数据类型：String
            /// </summary>
            public static Field CBNameOfReceipt = new Field< ORD_SalesOrder >("CBNameOfReceipt");
		    /// <summary>
            /// 银行手续费 - 字段名：BankingFee - 数据类型：Decimal?
            /// </summary>
            public static Field BankingFee = new Field< ORD_SalesOrder >("BankingFee");
		    /// <summary>
            /// 货运公司 - 字段名：TransportCompany - 数据类型：String
            /// </summary>
            public static Field TransportCompany = new Field< ORD_SalesOrder >("TransportCompany");
		    /// <summary>
            /// 货运单号 - 字段名：ShippingNo - 数据类型：String
            /// </summary>
            public static Field ShippingNo = new Field< ORD_SalesOrder >("ShippingNo");
		    /// <summary>
            /// 运费结算 - 字段名：FreightClearForm - 数据类型：String
            /// </summary>
            public static Field FreightClearForm = new Field< ORD_SalesOrder >("FreightClearForm");
		    /// <summary>
            /// 运费 - 字段名：Freight - 数据类型：Decimal?
            /// </summary>
            public static Field Freight = new Field< ORD_SalesOrder >("Freight");
		    /// <summary>
            /// 需发货日期 - 字段名：NeedDeliveryDate - 数据类型：DateTime?
            /// </summary>
            public static Field NeedDeliveryDate = new Field< ORD_SalesOrder >("NeedDeliveryDate");
		    /// <summary>
            /// 备注 - 字段名：Remark - 数据类型：String
            /// </summary>
            public static Field Remark = new Field< ORD_SalesOrder >("Remark");
		    /// <summary>
            /// 通知状态 - 字段名：NotifyStatus - 数据类型：String
            /// </summary>
            public static Field NotifyStatus = new Field< ORD_SalesOrder >("NotifyStatus");
		    /// <summary>
            /// 采购状态 - 字段名：PurchaseStatus - 数据类型：String
            /// </summary>
            public static Field PurchaseStatus = new Field< ORD_SalesOrder >("PurchaseStatus");
		    /// <summary>
            /// 收货状态 - 字段名：StkTakeStatus - 数据类型：String
            /// </summary>
            public static Field StkTakeStatus = new Field< ORD_SalesOrder >("StkTakeStatus");
		    /// <summary>
            /// 入库状态 - 字段名：StkInStatus - 数据类型：String
            /// </summary>
            public static Field StkInStatus = new Field< ORD_SalesOrder >("StkInStatus");
		    /// <summary>
            /// 出库占有状态 - 字段名：StkOutOccStatus - 数据类型：String
            /// </summary>
            public static Field StkOutOccStatus = new Field< ORD_SalesOrder >("StkOutOccStatus");
		    /// <summary>
            /// 出库状态 - 字段名：StkOutStatus - 数据类型：String
            /// </summary>
            public static Field StkOutStatus = new Field< ORD_SalesOrder >("StkOutStatus");
		    /// <summary>
            /// 发运状态 - 字段名：ShipmentStatus - 数据类型：String
            /// </summary>
            public static Field ShipmentStatus = new Field< ORD_SalesOrder >("ShipmentStatus");
		    /// <summary>
            /// 退货占有状态 - 字段名：ReturnOccStatus - 数据类型：String
            /// </summary>
            public static Field ReturnOccStatus = new Field< ORD_SalesOrder >("ReturnOccStatus");
		    /// <summary>
            /// 退货状态 - 字段名：ReturnStatus - 数据类型：String
            /// </summary>
            public static Field ReturnStatus = new Field< ORD_SalesOrder >("ReturnStatus");
		    /// <summary>
            /// 收款状态 - 字段名：ReceivableStatus - 数据类型：String
            /// </summary>
            public static Field ReceivableStatus = new Field< ORD_SalesOrder >("ReceivableStatus");
		    /// <summary>
            /// 创建人 - 字段名：CreatedEmpID - 数据类型：Int32?
            /// </summary>
            public static Field CreatedEmpID = new Field< ORD_SalesOrder >("CreatedEmpID");
		    /// <summary>
            /// 创建人姓名 - 字段名：CreatedEmpName - 数据类型：String
            /// </summary>
            public static Field CreatedEmpName = new Field< ORD_SalesOrder >("CreatedEmpName");
		    /// <summary>
            /// 创建时间 - 字段名：CreatedTime - 数据类型：DateTime?
            /// </summary>
            public static Field CreatedTime = new Field< ORD_SalesOrder >("CreatedTime");
		    /// <summary>
            /// 更新人 - 字段名：UpdatedEmpID - 数据类型：Int32?
            /// </summary>
            public static Field UpdatedEmpID = new Field< ORD_SalesOrder >("UpdatedEmpID");
		    /// <summary>
            /// 更新人 - 字段名：UpdatedEmpName - 数据类型：String
            /// </summary>
            public static Field UpdatedEmpName = new Field< ORD_SalesOrder >("UpdatedEmpName");
		    /// <summary>
            /// 更新时间 - 字段名：UpdatedTime - 数据类型：DateTime?
            /// </summary>
            public static Field UpdatedTime = new Field< ORD_SalesOrder >("UpdatedTime");
		    /// <summary>
            /// 单据状态 - 字段名：Status - 数据类型：String
            /// </summary>
            public static Field Status = new Field< ORD_SalesOrder >("Status");
		    /// <summary>
            /// 审批状态 - 字段名：ApproveStatus - 数据类型：String
            /// </summary>
            public static Field ApproveStatus = new Field< ORD_SalesOrder >("ApproveStatus");
		    /// <summary>
            /// 计算方式（0.未含税算含税,1.含税算未含税） - 字段名：CalcType - 数据类型：Boolean?
            /// </summary>
            public static Field CalcType = new Field< ORD_SalesOrder >("CalcType");
		    /// <summary>
            /// 是否取消 - 字段名：IsCancel - 数据类型：Boolean?
            /// </summary>
            public static Field IsCancel = new Field< ORD_SalesOrder >("IsCancel");
		    /// <summary>
            /// 是否删除 - 字段名：IsDeleted - 数据类型：Boolean?
            /// </summary>
            public static Field IsDeleted = new Field< ORD_SalesOrder >("IsDeleted");
		}
	}
}
