//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by CodeSmith Template.
//
//     Creater: Administrator
//     Date:    2015/3/12
//     Time:    14:16
//     Version: 4.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

/// <summary>
/// CodeSmith自动生成的实体
/// </summary>
namespace ZNLCRM.Entity.DBModel
{
    using System;
    using MySoft.Data;
    using ZNLCRM.Utility;
    using ZNLFrame.Entity;
    /// <summary>
    /// 表名：STK_In 主键列：StkInGuid
    /// </summary>
    [SerializableAttribute()]
    public partial class STK_In : BaseEntity
    {
        #region Private Properties

        private Int32? _StkInID;
        private Guid? _StkInGuid;
        private Guid? _GCompanyID;
        private String _BillNo;
        private String _BillType;
        private DateTime? _InDate;
        private Int32? _OperOrgID;
        private Int32? _OperDeptID;
        private Int32? _OperEmpID;
        private String _OperEmpName;
        private Int32? _ReceiverID;
        private String _ReceiverName;
        private Guid? _SourceBillGuid;
        private String _SourceBillNo;
        private String _Currency;
        private Decimal? _TaxRate;
        private Decimal? _Amount;
        private Decimal? _SCAmount;
        private Decimal? _TaxAmount;
        private Decimal? _ExchangeRate;
        private String _Remark;
        private Decimal? _PaymentAmount;
        private String _StkOutStatus;
        private String _PaymentStatus;
        private String _ApproveStatus;
        private String _Status;
        private Int32? _CreatedEmpID;
        private String _CreatedEmpName;
        private DateTime? _CreatedTime;
        private Int32? _UpdatedEmpID;
        private String _UpdatedEmpName;
        private DateTime? _UpdatedTime;
        private Boolean? _IsDeleted;

        #endregion

        #region Public Properties

        /// <summary>
        /// .
        /// </summary>
        public Guid? StkInGuid
        {
            get
            {
                return _StkInGuid;
            }
            set
            {
                this.OnPropertyValueChange(_.StkInGuid, _StkInGuid, value);
                this._StkInGuid = value;
            }
        }

        /// <summary>
        /// .
        /// </summary>
        public Int32? StkInID
        {
            get
            {
                return this._StkInID;
            }
            set
            {
                this.OnPropertyValueChange(_.StkInID, _StkInID, value);
                this._StkInID = value;
            }
        }

        /// <summary>
        /// 所属公司GUID.
        /// </summary>
        public Guid? GCompanyID
        {
            get
            {
                return this._GCompanyID;
            }
            set
            {
                this.OnPropertyValueChange(_.GCompanyID, _GCompanyID, value);
                this._GCompanyID = value;
            }
        }

        /// <summary>
        /// .
        /// </summary>
        public String BillNo
        {
            get
            {
                return this._BillNo;
            }
            set
            {
                this.OnPropertyValueChange(_.BillNo, _BillNo, value);
                this._BillNo = value.SubStr(20);
            }
        }

        /// <summary>
        /// .
        /// </summary>
        public String BillType
        {
            get
            {
                return this._BillType;
            }
            set
            {
                this.OnPropertyValueChange(_.BillType, _BillType, value);
                this._BillType = value.SubStr(20);
            }
        }

        /// <summary>
        /// .
        /// </summary>
        public DateTime? InDate
        {
            get
            {
                return this._InDate;
            }
            set
            {
                this.OnPropertyValueChange(_.InDate, _InDate, value);
                this._InDate = value;
            }
        }

        /// <summary>
        /// 所属机构ID.
        /// </summary>
        public Int32? OperOrgID
        {
            get
            {
                return this._OperOrgID;
            }
            set
            {
                this.OnPropertyValueChange(_.OperOrgID, _OperOrgID, value);
                this._OperOrgID = value;
            }
        }

        /// <summary>
        /// 所属部门ID.
        /// </summary>
        public Int32? OperDeptID
        {
            get
            {
                return this._OperDeptID;
            }
            set
            {
                this.OnPropertyValueChange(_.OperDeptID, _OperDeptID, value);
                this._OperDeptID = value;
            }
        }

        /// <summary>
        /// 所属人员ID.
        /// </summary>
        public Int32? OperEmpID
        {
            get
            {
                return this._OperEmpID;
            }
            set
            {
                this.OnPropertyValueChange(_.OperEmpID, _OperEmpID, value);
                this._OperEmpID = value;
            }
        }

        /// <summary>
        /// 所属人员.
        /// </summary>
        public String OperEmpName
        {
            get
            {
                return this._OperEmpName;
            }
            set
            {
                this.OnPropertyValueChange(_.OperEmpName, _OperEmpName, value);
                this._OperEmpName = value.SubStr(50);
            }
        }

        /// <summary>
        /// 收货人ID.
        /// </summary>
        public Int32? ReceiverID
        {
            get
            {
                return this._ReceiverID;
            }
            set
            {
                this.OnPropertyValueChange(_.ReceiverID, _ReceiverID, value);
                this._ReceiverID = value;
            }
        }

        /// <summary>
        /// 收货人.
        /// </summary>
        public String ReceiverName
        {
            get
            {
                return this._ReceiverName;
            }
            set
            {
                this.OnPropertyValueChange(_.ReceiverName, _ReceiverName, value);
                this._ReceiverName = value.SubStr(50);
            }
        }

        /// <summary>
        /// .
        /// </summary>
        public Guid? SourceBillGuid
        {
            get
            {
                return this._SourceBillGuid;
            }
            set
            {
                this.OnPropertyValueChange(_.SourceBillGuid, _SourceBillGuid, value);
                this._SourceBillGuid = value;
            }
        }

        /// <summary>
        /// .
        /// </summary>
        public String SourceBillNo
        {
            get
            {
                return this._SourceBillNo;
            }
            set
            {
                this.OnPropertyValueChange(_.SourceBillNo, _SourceBillNo, value);
                this._SourceBillNo = value.SubStr(20);
            }
        }

        /// <summary>
        /// 币种.
        /// </summary>
        public String Currency
        {
            get
            {
                return this._Currency;
            }
            set
            {
                this.OnPropertyValueChange(_.Currency, _Currency, value);
                this._Currency = value.SubStr(50);
            }
        }

        /// <summary>
        /// 税率.
        /// </summary>
        public Decimal? TaxRate
        {
            get
            {
                return this._TaxRate;
            }
            set
            {
                this.OnPropertyValueChange(_.TaxRate, _TaxRate, value);
                this._TaxRate = value;
            }
        }

        /// <summary>
        /// 总金额(如果明细币种不一样，金额直接相加）.
        /// </summary>
        public Decimal? Amount
        {
            get
            {
                return this._Amount;
            }
            set
            {
                this.OnPropertyValueChange(_.Amount, _Amount, value);
                this._Amount = value;
            }
        }

        /// <summary>
        /// 本币金额.
        /// </summary>
        public Decimal? SCAmount
        {
            get
            {
                return this._SCAmount;
            }
            set
            {
                this.OnPropertyValueChange(_.SCAmount, _SCAmount, value);
                this._SCAmount = value;
            }
        }

        /// <summary>
        /// 税额.
        /// </summary>
        public Decimal? TaxAmount
        {
            get
            {
                return this._TaxAmount;
            }
            set
            {
                this.OnPropertyValueChange(_.TaxAmount, _TaxAmount, value);
                this._TaxAmount = value;
            }
        }

        /// <summary>
        /// .
        /// </summary>
        public Decimal? ExchangeRate
        {
            get
            {
                return this._ExchangeRate;
            }
            set
            {
                this.OnPropertyValueChange(_.ExchangeRate, _ExchangeRate, value);
                this._ExchangeRate = value;
            }
        }

        /// <summary>
        /// .
        /// </summary>
        public String Remark
        {
            get
            {
                return this._Remark;
            }
            set
            {
                this.OnPropertyValueChange(_.Remark, _Remark, value);
                this._Remark = value.SubStr(200);
            }
        }

        /// <summary>
        /// .
        /// </summary>
        public Decimal? PaymentAmount
        {
            get
            {
                return this._PaymentAmount;
            }
            set
            {
                this.OnPropertyValueChange(_.PaymentAmount, _PaymentAmount, value);
                this._PaymentAmount = value;
            }
        }

        /// <summary>
        /// 出库状态.
        /// </summary>
        public String StkOutStatus
        {
            get
            {
                return this._StkOutStatus;
            }
            set
            {
                this.OnPropertyValueChange(_.StkOutStatus, _StkOutStatus, value);
                this._StkOutStatus = value.SubStr(10);
            }
        }

        /// <summary>
        /// 付款状态.
        /// </summary>
        public String PaymentStatus
        {
            get
            {
                return this._PaymentStatus;
            }
            set
            {
                this.OnPropertyValueChange(_.PaymentStatus, _PaymentStatus, value);
                this._PaymentStatus = value.SubStr(10);
            }
        }

        /// <summary>
        /// .
        /// </summary>
        public String ApproveStatus
        {
            get
            {
                return this._ApproveStatus;
            }
            set
            {
                this.OnPropertyValueChange(_.ApproveStatus, _ApproveStatus, value);
                this._ApproveStatus = value.SubStr(10);
            }
        }

        /// <summary>
        /// .
        /// </summary>
        public String Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnPropertyValueChange(_.Status, _Status, value);
                this._Status = value.SubStr(10);
            }
        }

        /// <summary>
        /// .
        /// </summary>
        public Int32? CreatedEmpID
        {
            get
            {
                return this._CreatedEmpID;
            }
            set
            {
                this.OnPropertyValueChange(_.CreatedEmpID, _CreatedEmpID, value);
                this._CreatedEmpID = value;
            }
        }

        /// <summary>
        /// .
        /// </summary>
        public String CreatedEmpName
        {
            get
            {
                return this._CreatedEmpName;
            }
            set
            {
                this.OnPropertyValueChange(_.CreatedEmpName, _CreatedEmpName, value);
                this._CreatedEmpName = value.SubStr(50);
            }
        }

        /// <summary>
        /// .
        /// </summary>
        public DateTime? CreatedTime
        {
            get
            {
                return this._CreatedTime;
            }
            set
            {
                this.OnPropertyValueChange(_.CreatedTime, _CreatedTime, value);
                this._CreatedTime = value;
            }
        }

        /// <summary>
        /// .
        /// </summary>
        public Int32? UpdatedEmpID
        {
            get
            {
                return this._UpdatedEmpID;
            }
            set
            {
                this.OnPropertyValueChange(_.UpdatedEmpID, _UpdatedEmpID, value);
                this._UpdatedEmpID = value;
            }
        }

        /// <summary>
        /// .
        /// </summary>
        public String UpdatedEmpName
        {
            get
            {
                return this._UpdatedEmpName;
            }
            set
            {
                this.OnPropertyValueChange(_.UpdatedEmpName, _UpdatedEmpName, value);
                this._UpdatedEmpName = value.SubStr(50);
            }
        }

        /// <summary>
        /// .
        /// </summary>
        public DateTime? UpdatedTime
        {
            get
            {
                return this._UpdatedTime;
            }
            set
            {
                this.OnPropertyValueChange(_.UpdatedTime, _UpdatedTime, value);
                this._UpdatedTime = value;
            }
        }

        /// <summary>
        /// 是否删除.
        /// </summary>
        public Boolean? IsDeleted
        {
            get
            {
                return this._IsDeleted;
            }
            set
            {
                this.OnPropertyValueChange(_.IsDeleted, _IsDeleted, value);
                this._IsDeleted = value;
            }
        }

        #endregion
        /// <summary>
        /// 获取实体对应的表名
        /// </summary>
        protected override Table GetTable()
        {
            return new Table<STK_In>("STK_In");
        }

        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        protected override Field GetIdentityField()
        {
            return _.StkInID;
        }

        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        protected override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.StkInGuid
			};
        }

        /// <summary>
        /// 获取列信息
        /// </summary>
        protected override Field[] GetFields()
        {
            return new Field[] {
				_.StkInID,		
				_.StkInGuid,		
				_.GCompanyID,		
				_.BillNo,		
				_.BillType,		
				_.InDate,		
				_.OperOrgID,		
				_.OperDeptID,		
				_.OperEmpID,		
				_.OperEmpName,		
				_.ReceiverID,		
				_.ReceiverName,		
				_.SourceBillGuid,		
				_.SourceBillNo,		
				_.Currency,		
				_.TaxRate,		
				_.Amount,		
				_.SCAmount,		
				_.TaxAmount,		
				_.ExchangeRate,		
				_.Remark,		
				_.PaymentAmount,		
				_.StkOutStatus,		
				_.PaymentStatus,		
				_.ApproveStatus,		
				_.Status,		
				_.CreatedEmpID,		
				_.CreatedEmpName,		
				_.CreatedTime,		
				_.UpdatedEmpID,		
				_.UpdatedEmpName,		
				_.UpdatedTime,		
				_.IsDeleted		
			};
        }

        /// <summary>
        /// 获取列数据
        /// </summary>
        protected override object[] GetValues()
        {
            return new object[] {
				this._StkInID,		
				this._StkInGuid,		
				this._GCompanyID,		
				this._BillNo,		
				this._BillType,		
				this._InDate,		
				this._OperOrgID,		
				this._OperDeptID,		
				this._OperEmpID,		
				this._OperEmpName,		
				this._ReceiverID,		
				this._ReceiverName,		
				this._SourceBillGuid,		
				this._SourceBillNo,		
				this._Currency,		
				this._TaxRate,		
				this._Amount,		
				this._SCAmount,		
				this._TaxAmount,		
				this._ExchangeRate,		
				this._Remark,		
				this._PaymentAmount,		
				this._StkOutStatus,		
				this._PaymentStatus,		
				this._ApproveStatus,		
				this._Status,		
				this._CreatedEmpID,		
				this._CreatedEmpName,		
				this._CreatedTime,		
				this._UpdatedEmpID,		
				this._UpdatedEmpName,		
				this._UpdatedTime,		
				this._IsDeleted		
			};
        }

        /// <summary>
        /// 给当前实体赋值
        /// </summary>
        protected override void SetValues(IRowReader reader)
        {
            if ((false == reader.IsDBNull(_.StkInID)))
            {
                this._StkInID = reader.GetInt32(_.StkInID);
            }
            if ((false == reader.IsDBNull(_.StkInGuid)))
            {
                this._StkInGuid = reader.GetGuid(_.StkInGuid);
            }
            if ((false == reader.IsDBNull(_.GCompanyID)))
            {
                this._GCompanyID = reader.GetGuid(_.GCompanyID);
            }
            if ((false == reader.IsDBNull(_.BillNo)))
            {
                this._BillNo = reader.GetString(_.BillNo);
            }
            if ((false == reader.IsDBNull(_.BillType)))
            {
                this._BillType = reader.GetString(_.BillType);
            }
            if ((false == reader.IsDBNull(_.InDate)))
            {
                this._InDate = reader.GetDateTime(_.InDate);
            }
            if ((false == reader.IsDBNull(_.OperOrgID)))
            {
                this._OperOrgID = reader.GetInt32(_.OperOrgID);
            }
            if ((false == reader.IsDBNull(_.OperDeptID)))
            {
                this._OperDeptID = reader.GetInt32(_.OperDeptID);
            }
            if ((false == reader.IsDBNull(_.OperEmpID)))
            {
                this._OperEmpID = reader.GetInt32(_.OperEmpID);
            }
            if ((false == reader.IsDBNull(_.OperEmpName)))
            {
                this._OperEmpName = reader.GetString(_.OperEmpName);
            }
            if ((false == reader.IsDBNull(_.ReceiverID)))
            {
                this._ReceiverID = reader.GetInt32(_.ReceiverID);
            }
            if ((false == reader.IsDBNull(_.ReceiverName)))
            {
                this._ReceiverName = reader.GetString(_.ReceiverName);
            }
            if ((false == reader.IsDBNull(_.SourceBillGuid)))
            {
                this._SourceBillGuid = reader.GetGuid(_.SourceBillGuid);
            }
            if ((false == reader.IsDBNull(_.SourceBillNo)))
            {
                this._SourceBillNo = reader.GetString(_.SourceBillNo);
            }
            if ((false == reader.IsDBNull(_.Currency)))
            {
                this._Currency = reader.GetString(_.Currency);
            }
            if ((false == reader.IsDBNull(_.TaxRate)))
            {
                this._TaxRate = reader.GetDecimal(_.TaxRate);
            }
            if ((false == reader.IsDBNull(_.Amount)))
            {
                this._Amount = reader.GetDecimal(_.Amount);
            }
            if ((false == reader.IsDBNull(_.SCAmount)))
            {
                this._SCAmount = reader.GetDecimal(_.SCAmount);
            }
            if ((false == reader.IsDBNull(_.TaxAmount)))
            {
                this._TaxAmount = reader.GetDecimal(_.TaxAmount);
            }
            if ((false == reader.IsDBNull(_.ExchangeRate)))
            {
                this._ExchangeRate = reader.GetDecimal(_.ExchangeRate);
            }
            if ((false == reader.IsDBNull(_.Remark)))
            {
                this._Remark = reader.GetString(_.Remark);
            }
            if ((false == reader.IsDBNull(_.PaymentAmount)))
            {
                this._PaymentAmount = reader.GetDecimal(_.PaymentAmount);
            }
            if ((false == reader.IsDBNull(_.StkOutStatus)))
            {
                this._StkOutStatus = reader.GetString(_.StkOutStatus);
            }
            if ((false == reader.IsDBNull(_.PaymentStatus)))
            {
                this._PaymentStatus = reader.GetString(_.PaymentStatus);
            }
            if ((false == reader.IsDBNull(_.ApproveStatus)))
            {
                this._ApproveStatus = reader.GetString(_.ApproveStatus);
            }
            if ((false == reader.IsDBNull(_.Status)))
            {
                this._Status = reader.GetString(_.Status);
            }
            if ((false == reader.IsDBNull(_.CreatedEmpID)))
            {
                this._CreatedEmpID = reader.GetInt32(_.CreatedEmpID);
            }
            if ((false == reader.IsDBNull(_.CreatedEmpName)))
            {
                this._CreatedEmpName = reader.GetString(_.CreatedEmpName);
            }
            if ((false == reader.IsDBNull(_.CreatedTime)))
            {
                this._CreatedTime = reader.GetDateTime(_.CreatedTime);
            }
            if ((false == reader.IsDBNull(_.UpdatedEmpID)))
            {
                this._UpdatedEmpID = reader.GetInt32(_.UpdatedEmpID);
            }
            if ((false == reader.IsDBNull(_.UpdatedEmpName)))
            {
                this._UpdatedEmpName = reader.GetString(_.UpdatedEmpName);
            }
            if ((false == reader.IsDBNull(_.UpdatedTime)))
            {
                this._UpdatedTime = reader.GetDateTime(_.UpdatedTime);
            }
            if ((false == reader.IsDBNull(_.IsDeleted)))
            {
                this._IsDeleted = reader.GetBoolean(_.IsDeleted);
            }
        }

        public override int GetHashCode()
        {
            return base.GetHashCode();
        }

        public override bool Equals(object obj)
        {
            if ((obj == null))
            {
                return false;
            }
            if ((false == typeof(STK_In).IsAssignableFrom(obj.GetType())))
            {
                return false;
            }
            if ((((object)(this)) == ((object)(obj))))
            {
                return true;
            }
            return false;
        }

        public class _
        {

            /// <summary>
            /// 表示选择所有列，与*等同
            /// </summary>
            public static AllField All = new AllField<STK_In>();

            /// <summary>
            ///  - 字段名：StkInID - 数据类型：Int32?
            /// </summary>
            public static Field StkInID = new Field<STK_In>("StkInID");
            /// <summary>
            ///  - 字段名：StkInGuid - 数据类型：Guid?
            /// </summary>
            public static Field StkInGuid = new Field<STK_In>("StkInGuid");
            /// <summary>
            /// 所属公司GUID - 字段名：GCompanyID - 数据类型：Guid?
            /// </summary>
            public static Field GCompanyID = new Field<STK_In>("GCompanyID");
            /// <summary>
            ///  - 字段名：BillNo - 数据类型：String
            /// </summary>
            public static Field BillNo = new Field<STK_In>("BillNo");
            /// <summary>
            ///  - 字段名：BillType - 数据类型：String
            /// </summary>
            public static Field BillType = new Field<STK_In>("BillType");
            /// <summary>
            ///  - 字段名：InDate - 数据类型：DateTime?
            /// </summary>
            public static Field InDate = new Field<STK_In>("InDate");
            /// <summary>
            /// 所属机构ID - 字段名：OperOrgID - 数据类型：Int32?
            /// </summary>
            public static Field OperOrgID = new Field<STK_In>("OperOrgID");
            /// <summary>
            /// 所属部门ID - 字段名：OperDeptID - 数据类型：Int32?
            /// </summary>
            public static Field OperDeptID = new Field<STK_In>("OperDeptID");
            /// <summary>
            /// 所属人员ID - 字段名：OperEmpID - 数据类型：Int32?
            /// </summary>
            public static Field OperEmpID = new Field<STK_In>("OperEmpID");
            /// <summary>
            /// 所属人员 - 字段名：OperEmpName - 数据类型：String
            /// </summary>
            public static Field OperEmpName = new Field<STK_In>("OperEmpName");
            /// <summary>
            /// 收货人ID - 字段名：ReceiverID - 数据类型：Int32?
            /// </summary>
            public static Field ReceiverID = new Field<STK_In>("ReceiverID");
            /// <summary>
            /// 收货人 - 字段名：ReceiverName - 数据类型：String
            /// </summary>
            public static Field ReceiverName = new Field<STK_In>("ReceiverName");
            /// <summary>
            ///  - 字段名：SourceBillGuid - 数据类型：Guid?
            /// </summary>
            public static Field SourceBillGuid = new Field<STK_In>("SourceBillGuid");
            /// <summary>
            ///  - 字段名：SourceBillNo - 数据类型：String
            /// </summary>
            public static Field SourceBillNo = new Field<STK_In>("SourceBillNo");
            /// <summary>
            /// 币种 - 字段名：Currency - 数据类型：String
            /// </summary>
            public static Field Currency = new Field<STK_In>("Currency");
            /// <summary>
            /// 税率 - 字段名：TaxRate - 数据类型：Decimal?
            /// </summary>
            public static Field TaxRate = new Field<STK_In>("TaxRate");
            /// <summary>
            /// 总金额(如果明细币种不一样，金额直接相加） - 字段名：Amount - 数据类型：Decimal?
            /// </summary>
            public static Field Amount = new Field<STK_In>("Amount");
            /// <summary>
            /// 本币金额 - 字段名：SCAmount - 数据类型：Decimal?
            /// </summary>
            public static Field SCAmount = new Field<STK_In>("SCAmount");
            /// <summary>
            /// 税额 - 字段名：TaxAmount - 数据类型：Decimal?
            /// </summary>
            public static Field TaxAmount = new Field<STK_In>("TaxAmount");
            /// <summary>
            ///  - 字段名：ExchangeRate - 数据类型：Decimal?
            /// </summary>
            public static Field ExchangeRate = new Field<STK_In>("ExchangeRate");
            /// <summary>
            ///  - 字段名：Remark - 数据类型：String
            /// </summary>
            public static Field Remark = new Field<STK_In>("Remark");
            /// <summary>
            ///  - 字段名：PaymentAmount - 数据类型：Decimal?
            /// </summary>
            public static Field PaymentAmount = new Field<STK_In>("PaymentAmount");
            /// <summary>
            /// 出库状态 - 字段名：StkOutStatus - 数据类型：String
            /// </summary>
            public static Field StkOutStatus = new Field<STK_In>("StkOutStatus");
            /// <summary>
            /// 付款状态 - 字段名：PaymentStatus - 数据类型：String
            /// </summary>
            public static Field PaymentStatus = new Field<STK_In>("PaymentStatus");
            /// <summary>
            ///  - 字段名：ApproveStatus - 数据类型：String
            /// </summary>
            public static Field ApproveStatus = new Field<STK_In>("ApproveStatus");
            /// <summary>
            ///  - 字段名：Status - 数据类型：String
            /// </summary>
            public static Field Status = new Field<STK_In>("Status");
            /// <summary>
            ///  - 字段名：CreatedEmpID - 数据类型：Int32?
            /// </summary>
            public static Field CreatedEmpID = new Field<STK_In>("CreatedEmpID");
            /// <summary>
            ///  - 字段名：CreatedEmpName - 数据类型：String
            /// </summary>
            public static Field CreatedEmpName = new Field<STK_In>("CreatedEmpName");
            /// <summary>
            ///  - 字段名：CreatedTime - 数据类型：DateTime?
            /// </summary>
            public static Field CreatedTime = new Field<STK_In>("CreatedTime");
            /// <summary>
            ///  - 字段名：UpdatedEmpID - 数据类型：Int32?
            /// </summary>
            public static Field UpdatedEmpID = new Field<STK_In>("UpdatedEmpID");
            /// <summary>
            ///  - 字段名：UpdatedEmpName - 数据类型：String
            /// </summary>
            public static Field UpdatedEmpName = new Field<STK_In>("UpdatedEmpName");
            /// <summary>
            ///  - 字段名：UpdatedTime - 数据类型：DateTime?
            /// </summary>
            public static Field UpdatedTime = new Field<STK_In>("UpdatedTime");
            /// <summary>
            /// 是否删除 - 字段名：IsDeleted - 数据类型：Boolean?
            /// </summary>
            public static Field IsDeleted = new Field<STK_In>("IsDeleted");
        }
    }
}
