//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by CodeSmith Template.
//
//     Creater: David
//     Date:    2015/3/12
//     Time:    14:21
//     Version: 4.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

/// <summary>
/// CodeSmith自动生成的实体
/// </summary>
namespace ZNLCRM.Entity.DBModel
{	
	using System;
	using MySoft.Data;
	using ZNLCRM.Utility;
    using ZNLFrame.Entity;
    /// <summary>
    /// 表名：STK_InOutLink 主键列：StkLinkGuid
    /// </summary>
    [SerializableAttribute()]
	public partial class STK_InOutLink : BaseEntity
	{
		#region Private Properties
		
		private Int32? _StkLinkID;
		private Guid? _StkLinkGuid;
		private Guid? _ItemCode;
		private String _StkOutType;
		private Guid? _StkOutGuid;
		private String _StkOutBillNo;
		private Guid? _StkOutLineGuid;
		private String _StkInType;
		private Guid? _StkInGuid;
		private String _StkInBillNo;
		private Guid? _StkInLineGuid;
		private Int32? _StkLinkQty;
		private Int32? _CreatedEmpID;
		private String _CreatedEmpName;
		private DateTime? _CreatedTime;
		private Int32? _UpdatedEmpID;
		private String _UpdatedEmpName;
		private DateTime? _UpdatedTime;
		private Boolean? _IsDeleted;
		
		#endregion
		
		#region Public Properties
		
		/// <summary>
		/// .
		/// </summary>
		public Guid? StkLinkGuid
		{
			get 
			{
				return _StkLinkGuid;
			}
			set 
			{
				this.OnPropertyValueChange(_.StkLinkGuid, _StkLinkGuid , value);
				this._StkLinkGuid = value;
			}
		}
		
		/// <summary>
		/// .
		/// </summary>
		public Int32? StkLinkID
		{
			get 
			{
				return this._StkLinkID;
			}
			set 
			{
				this.OnPropertyValueChange(_.StkLinkID, _StkLinkID , value);
				this._StkLinkID = value;
			}
		}

		/// <summary>
		/// 库存Guid.
		/// </summary>
		public Guid? ItemCode
		{
			get 
			{
				return this._ItemCode;
			}
			set 
			{
				this.OnPropertyValueChange(_.ItemCode, _ItemCode , value);
				this._ItemCode = value;
			}
		}

		/// <summary>
		/// 出库类型.
		/// </summary>
		public String StkOutType
		{
			get 
			{
				return this._StkOutType;
			}
			set 
			{
				this.OnPropertyValueChange(_.StkOutType, _StkOutType , value);
				this._StkOutType = value.SubStr(20);
			}
		}

		/// <summary>
		/// 出库主单Guid.
		/// </summary>
		public Guid? StkOutGuid
		{
			get 
			{
				return this._StkOutGuid;
			}
			set 
			{
				this.OnPropertyValueChange(_.StkOutGuid, _StkOutGuid , value);
				this._StkOutGuid = value;
			}
		}

		/// <summary>
		/// 出库单号.
		/// </summary>
		public String StkOutBillNo
		{
			get 
			{
				return this._StkOutBillNo;
			}
			set 
			{
				this.OnPropertyValueChange(_.StkOutBillNo, _StkOutBillNo , value);
				this._StkOutBillNo = value.SubStr(20);
			}
		}

		/// <summary>
		/// 出库明细Guid.
		/// </summary>
		public Guid? StkOutLineGuid
		{
			get 
			{
				return this._StkOutLineGuid;
			}
			set 
			{
				this.OnPropertyValueChange(_.StkOutLineGuid, _StkOutLineGuid , value);
				this._StkOutLineGuid = value;
			}
		}

		/// <summary>
		/// 入库类型.
		/// </summary>
		public String StkInType
		{
			get 
			{
				return this._StkInType;
			}
			set 
			{
				this.OnPropertyValueChange(_.StkInType, _StkInType , value);
				this._StkInType = value.SubStr(20);
			}
		}

		/// <summary>
		/// 入库主单Guid.
		/// </summary>
		public Guid? StkInGuid
		{
			get 
			{
				return this._StkInGuid;
			}
			set 
			{
				this.OnPropertyValueChange(_.StkInGuid, _StkInGuid , value);
				this._StkInGuid = value;
			}
		}

		/// <summary>
		/// 入库单号.
		/// </summary>
		public String StkInBillNo
		{
			get 
			{
				return this._StkInBillNo;
			}
			set 
			{
				this.OnPropertyValueChange(_.StkInBillNo, _StkInBillNo , value);
				this._StkInBillNo = value.SubStr(20);
			}
		}

		/// <summary>
		/// 入库明细Guid.
		/// </summary>
		public Guid? StkInLineGuid
		{
			get 
			{
				return this._StkInLineGuid;
			}
			set 
			{
				this.OnPropertyValueChange(_.StkInLineGuid, _StkInLineGuid , value);
				this._StkInLineGuid = value;
			}
		}

		/// <summary>
		/// 关联数量.
		/// </summary>
		public Int32? StkLinkQty
		{
			get 
			{
				return this._StkLinkQty;
			}
			set 
			{
				this.OnPropertyValueChange(_.StkLinkQty, _StkLinkQty , value);
				this._StkLinkQty = value;
			}
		}

		/// <summary>
		/// 创建人员ID.
		/// </summary>
		public Int32? CreatedEmpID
		{
			get 
			{
				return this._CreatedEmpID;
			}
			set 
			{
				this.OnPropertyValueChange(_.CreatedEmpID, _CreatedEmpID , value);
				this._CreatedEmpID = value;
			}
		}

		/// <summary>
		/// 创建人员.
		/// </summary>
		public String CreatedEmpName
		{
			get 
			{
				return this._CreatedEmpName;
			}
			set 
			{
				this.OnPropertyValueChange(_.CreatedEmpName, _CreatedEmpName , value);
				this._CreatedEmpName = value.SubStr(50);
			}
		}

		/// <summary>
		/// 创建时间.
		/// </summary>
		public DateTime? CreatedTime
		{
			get 
			{
				return this._CreatedTime;
			}
			set 
			{
				this.OnPropertyValueChange(_.CreatedTime, _CreatedTime , value);
				this._CreatedTime = value;
			}
		}

		/// <summary>
		/// 修改人员.
		/// </summary>
		public Int32? UpdatedEmpID
		{
			get 
			{
				return this._UpdatedEmpID;
			}
			set 
			{
				this.OnPropertyValueChange(_.UpdatedEmpID, _UpdatedEmpID , value);
				this._UpdatedEmpID = value;
			}
		}

		/// <summary>
		/// 修改人员.
		/// </summary>
		public String UpdatedEmpName
		{
			get 
			{
				return this._UpdatedEmpName;
			}
			set 
			{
				this.OnPropertyValueChange(_.UpdatedEmpName, _UpdatedEmpName , value);
				this._UpdatedEmpName = value.SubStr(50);
			}
		}

		/// <summary>
		/// 修改时间.
		/// </summary>
		public DateTime? UpdatedTime
		{
			get 
			{
				return this._UpdatedTime;
			}
			set 
			{
				this.OnPropertyValueChange(_.UpdatedTime, _UpdatedTime , value);
				this._UpdatedTime = value;
			}
		}

		/// <summary>
		/// 删除标记.
		/// </summary>
		public Boolean? IsDeleted
		{
			get 
			{
				return this._IsDeleted;
			}
			set 
			{
				this.OnPropertyValueChange(_.IsDeleted, _IsDeleted , value);
				this._IsDeleted = value;
			}
		}
		
		#endregion
	    /// <summary>
        /// 获取实体对应的表名
        /// </summary>
        protected override Table GetTable() {
            return new Table< STK_InOutLink >("STK_InOutLink");
        }
		
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        protected override Field GetIdentityField() {
            return _.StkLinkID;
        }  			
		
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        protected override Field[] GetPrimaryKeyFields() {
            return new Field[] {
				_.StkLinkGuid
			};
        }
			
	    /// <summary>
        /// 获取列信息
        /// </summary>
        protected override Field[] GetFields() {
            return new Field[] {
				_.StkLinkID,		
				_.StkLinkGuid,		
				_.ItemCode,		
				_.StkOutType,		
				_.StkOutGuid,		
				_.StkOutBillNo,		
				_.StkOutLineGuid,		
				_.StkInType,		
				_.StkInGuid,		
				_.StkInBillNo,		
				_.StkInLineGuid,		
				_.StkLinkQty,		
				_.CreatedEmpID,		
				_.CreatedEmpName,		
				_.CreatedTime,		
				_.UpdatedEmpID,		
				_.UpdatedEmpName,		
				_.UpdatedTime,		
				_.IsDeleted		
			};
		}
		
	    /// <summary>
        /// 获取列数据
        /// </summary>
        protected override object[] GetValues() {
            return new object[] {
				this._StkLinkID,		
				this._StkLinkGuid,		
				this._ItemCode,		
				this._StkOutType,		
				this._StkOutGuid,		
				this._StkOutBillNo,		
				this._StkOutLineGuid,		
				this._StkInType,		
				this._StkInGuid,		
				this._StkInBillNo,		
				this._StkInLineGuid,		
				this._StkLinkQty,		
				this._CreatedEmpID,		
				this._CreatedEmpName,		
				this._CreatedTime,		
				this._UpdatedEmpID,		
				this._UpdatedEmpName,		
				this._UpdatedTime,		
				this._IsDeleted		
			};
		}
		
	    /// <summary>
        /// 给当前实体赋值
        /// </summary>
        protected override void SetValues(IRowReader reader) {
            if ((false == reader.IsDBNull(_.StkLinkID))) {
                this._StkLinkID = reader.GetInt32(_.StkLinkID);
            }
            if ((false == reader.IsDBNull(_.StkLinkGuid))) {
                this._StkLinkGuid = reader.GetGuid(_.StkLinkGuid);
            }
            if ((false == reader.IsDBNull(_.ItemCode))) {
                this._ItemCode = reader.GetGuid(_.ItemCode);
            }
            if ((false == reader.IsDBNull(_.StkOutType))) {
                this._StkOutType = reader.GetString(_.StkOutType);
            }
            if ((false == reader.IsDBNull(_.StkOutGuid))) {
                this._StkOutGuid = reader.GetGuid(_.StkOutGuid);
            }
            if ((false == reader.IsDBNull(_.StkOutBillNo))) {
                this._StkOutBillNo = reader.GetString(_.StkOutBillNo);
            }
            if ((false == reader.IsDBNull(_.StkOutLineGuid))) {
                this._StkOutLineGuid = reader.GetGuid(_.StkOutLineGuid);
            }
            if ((false == reader.IsDBNull(_.StkInType))) {
                this._StkInType = reader.GetString(_.StkInType);
            }
            if ((false == reader.IsDBNull(_.StkInGuid))) {
                this._StkInGuid = reader.GetGuid(_.StkInGuid);
            }
            if ((false == reader.IsDBNull(_.StkInBillNo))) {
                this._StkInBillNo = reader.GetString(_.StkInBillNo);
            }
            if ((false == reader.IsDBNull(_.StkInLineGuid))) {
                this._StkInLineGuid = reader.GetGuid(_.StkInLineGuid);
            }
            if ((false == reader.IsDBNull(_.StkLinkQty))) {
                this._StkLinkQty = reader.GetInt32(_.StkLinkQty);
            }
            if ((false == reader.IsDBNull(_.CreatedEmpID))) {
                this._CreatedEmpID = reader.GetInt32(_.CreatedEmpID);
            }
            if ((false == reader.IsDBNull(_.CreatedEmpName))) {
                this._CreatedEmpName = reader.GetString(_.CreatedEmpName);
            }
            if ((false == reader.IsDBNull(_.CreatedTime))) {
                this._CreatedTime = reader.GetDateTime(_.CreatedTime);
            }
            if ((false == reader.IsDBNull(_.UpdatedEmpID))) {
                this._UpdatedEmpID = reader.GetInt32(_.UpdatedEmpID);
            }
            if ((false == reader.IsDBNull(_.UpdatedEmpName))) {
                this._UpdatedEmpName = reader.GetString(_.UpdatedEmpName);
            }
            if ((false == reader.IsDBNull(_.UpdatedTime))) {
                this._UpdatedTime = reader.GetDateTime(_.UpdatedTime);
            }
            if ((false == reader.IsDBNull(_.IsDeleted))) {
                this._IsDeleted = reader.GetBoolean(_.IsDeleted);
            }
		}
		
	    public override int GetHashCode() {
            return base.GetHashCode();
        }
        
        public override bool Equals(object obj) {
            if ((obj == null)) {
                return false;
            }
            if ((false == typeof(STK_InOutLink).IsAssignableFrom(obj.GetType()))) {
                return false;
            }
            if ((((object)(this)) == ((object)(obj)))) {
                return true;
            }
            return false;
        }
		
        public class _ {
                
            /// <summary>
            /// 表示选择所有列，与*等同
            /// </summary>
            public static AllField All = new AllField< STK_InOutLink >();
			
		    /// <summary>
            ///  - 字段名：StkLinkID - 数据类型：Int32?
            /// </summary>
            public static Field StkLinkID = new Field< STK_InOutLink >("StkLinkID");
		    /// <summary>
            ///  - 字段名：StkLinkGuid - 数据类型：Guid?
            /// </summary>
            public static Field StkLinkGuid = new Field< STK_InOutLink >("StkLinkGuid");
		    /// <summary>
            /// 库存Guid - 字段名：ItemCode - 数据类型：Guid?
            /// </summary>
            public static Field ItemCode = new Field< STK_InOutLink >("ItemCode");
		    /// <summary>
            /// 出库类型 - 字段名：StkOutType - 数据类型：String
            /// </summary>
            public static Field StkOutType = new Field< STK_InOutLink >("StkOutType");
		    /// <summary>
            /// 出库主单Guid - 字段名：StkOutGuid - 数据类型：Guid?
            /// </summary>
            public static Field StkOutGuid = new Field< STK_InOutLink >("StkOutGuid");
		    /// <summary>
            /// 出库单号 - 字段名：StkOutBillNo - 数据类型：String
            /// </summary>
            public static Field StkOutBillNo = new Field< STK_InOutLink >("StkOutBillNo");
		    /// <summary>
            /// 出库明细Guid - 字段名：StkOutLineGuid - 数据类型：Guid?
            /// </summary>
            public static Field StkOutLineGuid = new Field< STK_InOutLink >("StkOutLineGuid");
		    /// <summary>
            /// 入库类型 - 字段名：StkInType - 数据类型：String
            /// </summary>
            public static Field StkInType = new Field< STK_InOutLink >("StkInType");
		    /// <summary>
            /// 入库主单Guid - 字段名：StkInGuid - 数据类型：Guid?
            /// </summary>
            public static Field StkInGuid = new Field< STK_InOutLink >("StkInGuid");
		    /// <summary>
            /// 入库单号 - 字段名：StkInBillNo - 数据类型：String
            /// </summary>
            public static Field StkInBillNo = new Field< STK_InOutLink >("StkInBillNo");
		    /// <summary>
            /// 入库明细Guid - 字段名：StkInLineGuid - 数据类型：Guid?
            /// </summary>
            public static Field StkInLineGuid = new Field< STK_InOutLink >("StkInLineGuid");
		    /// <summary>
            /// 关联数量 - 字段名：StkLinkQty - 数据类型：Int32?
            /// </summary>
            public static Field StkLinkQty = new Field< STK_InOutLink >("StkLinkQty");
		    /// <summary>
            /// 创建人员ID - 字段名：CreatedEmpID - 数据类型：Int32?
            /// </summary>
            public static Field CreatedEmpID = new Field< STK_InOutLink >("CreatedEmpID");
		    /// <summary>
            /// 创建人员 - 字段名：CreatedEmpName - 数据类型：String
            /// </summary>
            public static Field CreatedEmpName = new Field< STK_InOutLink >("CreatedEmpName");
		    /// <summary>
            /// 创建时间 - 字段名：CreatedTime - 数据类型：DateTime?
            /// </summary>
            public static Field CreatedTime = new Field< STK_InOutLink >("CreatedTime");
		    /// <summary>
            /// 修改人员 - 字段名：UpdatedEmpID - 数据类型：Int32?
            /// </summary>
            public static Field UpdatedEmpID = new Field< STK_InOutLink >("UpdatedEmpID");
		    /// <summary>
            /// 修改人员 - 字段名：UpdatedEmpName - 数据类型：String
            /// </summary>
            public static Field UpdatedEmpName = new Field< STK_InOutLink >("UpdatedEmpName");
		    /// <summary>
            /// 修改时间 - 字段名：UpdatedTime - 数据类型：DateTime?
            /// </summary>
            public static Field UpdatedTime = new Field< STK_InOutLink >("UpdatedTime");
		    /// <summary>
            /// 删除标记 - 字段名：IsDeleted - 数据类型：Boolean?
            /// </summary>
            public static Field IsDeleted = new Field< STK_InOutLink >("IsDeleted");
		}
	}
}
