//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by CodeSmith Template.
//
//     Creater: Administrator
//     Date:    2015/1/23
//     Time:    10:15
//     Version: 4.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

/// <summary>
/// CodeSmith自动生成的实体
/// </summary>
namespace ZNLCRM.Entity.DBModel
{
    using System;
    using MySoft.Data;
    using ZNLCRM.Utility;
    using ZNLFrame.Entity;
    /// <summary>
    /// 表名：SYS_CompanyInfo 主键列：AutoID
    /// </summary>
    [SerializableAttribute()]
    public partial class SYS_CompanyInfo : BaseEntity
    {
        #region Private Properties

        private Int32 _AutoID;
        private Guid? _CompanyID;
        private String _RegistAccount;
        private Boolean? _EnabledSubAccountRole;
        private String _CompanyName;
        private String _ShortName;
        private String _CompanyCode;
        private String _PartnerCode;
        private String _PartnerUserID;
        private String _BillNoPrefix;
        private String _Telephone;
        private String _Mobile;
        private String _Fax;
        private String _Email;
        private String _WebSite;
        private String _QQ;
        private String _Address;
        private String _Contact;
        private String _Remark;
        private String _BriefIntroduction;
        private String _LogoFilePath;
        private Int32? _CurrentUserCount;
        private Decimal? _AmountBalance;
        private Int32? _IsActive;
        private DateTime? _ExpirationTime;
        private String _StockMarkNames;
        private Boolean? _StartAutoBackupData;
        private String _MacAddressForBackup;
        private Boolean? _STKOutNeedAudit;
        private Boolean? _STKInNeedAudit;
        private DateTime? _CreatedTime;
        private Int32? _CreatedByID;
        private String _CreatedByName;
        private String _Brand;
        private String _LableName;
        private String _Product;
        private String _Sign;
        private Boolean? _DontAllowNegativeStock;
        private Boolean? _ShowCloudPrice;
        private Boolean? _AllowPopTipsForCall;
        private Boolean? _AllowICNetHotsForTools;
        private Boolean? _IsUseOcxPhoneBox;
        private String _Reference;
        private Int32? _FromBy;
        private Boolean? _IsDeleted;

        #endregion

        #region Public Properties

        /// <summary>
        /// 自增ID.
        /// </summary>
        public Int32 AutoID
        {
            get
            {
                return _AutoID;
            }
            set
            {
                this.OnPropertyValueChange(_.AutoID, _AutoID, value);
                this._AutoID = value;
            }
        }

        /// <summary>
        /// 公司ID.
        /// </summary>
        public Guid? CompanyID
        {
            get
            {
                return this._CompanyID;
            }
            set
            {
                this.OnPropertyValueChange(_.CompanyID, _CompanyID, value);
                this._CompanyID = value;
            }
        }

        /// <summary>
        /// 注册帐号.
        /// </summary>
        public String RegistAccount
        {
            get
            {
                return this._RegistAccount;
            }
            set
            {
                this.OnPropertyValueChange(_.RegistAccount, _RegistAccount, value);
                this._RegistAccount = value.SubStr(50);
            }
        }

        /// <summary>
        /// 启用子帐号权限控制.
        /// </summary>
        public Boolean? EnabledSubAccountRole
        {
            get
            {
                return this._EnabledSubAccountRole;
            }
            set
            {
                this.OnPropertyValueChange(_.EnabledSubAccountRole, _EnabledSubAccountRole, value);
                this._EnabledSubAccountRole = value;
            }
        }

        /// <summary>
        /// 公司名称.
        /// </summary>
        public String CompanyName
        {
            get
            {
                return this._CompanyName;
            }
            set
            {
                this.OnPropertyValueChange(_.CompanyName, _CompanyName, value);
                this._CompanyName = value.SubStr(100);
            }
        }

        /// <summary>
        /// 简称.
        /// </summary>
        public String ShortName
        {
            get
            {
                return this._ShortName;
            }
            set
            {
                this.OnPropertyValueChange(_.ShortName, _ShortName, value);
                this._ShortName = value.SubStr(50);
            }
        }

        /// <summary>
        /// 公司编码.
        /// </summary>
        public String CompanyCode
        {
            get
            {
                return this._CompanyCode;
            }
            set
            {
                this.OnPropertyValueChange(_.CompanyCode, _CompanyCode, value);
                this._CompanyCode = value.SubStr(50);
            }
        }

        /// <summary>
        /// 合作平台代码.
        /// </summary>
        public String PartnerCode
        {
            get
            {
                return this._PartnerCode;
            }
            set
            {
                this.OnPropertyValueChange(_.PartnerCode, _PartnerCode, value);
                this._PartnerCode = value.SubStr(50);
            }
        }

        /// <summary>
        /// 合作伙伴会员ID.
        /// </summary>
        public String PartnerUserID
        {
            get
            {
                return this._PartnerUserID;
            }
            set
            {
                this.OnPropertyValueChange(_.PartnerUserID, _PartnerUserID, value);
                this._PartnerUserID = value.SubStr(100);
            }
        }

        /// <summary>
        /// 单据编号前缀.
        /// </summary>
        public String BillNoPrefix
        {
            get
            {
                return this._BillNoPrefix;
            }
            set
            {
                this.OnPropertyValueChange(_.BillNoPrefix, _BillNoPrefix, value);
                this._BillNoPrefix = value.SubStr(4);
            }
        }

        /// <summary>
        /// 电话.
        /// </summary>
        public String Telephone
        {
            get
            {
                return this._Telephone;
            }
            set
            {
                this.OnPropertyValueChange(_.Telephone, _Telephone, value);
                this._Telephone = value.SubStr(100);
            }
        }

        /// <summary>
        /// 手机.
        /// </summary>
        public String Mobile
        {
            get
            {
                return this._Mobile;
            }
            set
            {
                this.OnPropertyValueChange(_.Mobile, _Mobile, value);
                this._Mobile = value.SubStr(50);
            }
        }

        /// <summary>
        /// 传真.
        /// </summary>
        public String Fax
        {
            get
            {
                return this._Fax;
            }
            set
            {
                this.OnPropertyValueChange(_.Fax, _Fax, value);
                this._Fax = value.SubStr(50);
            }
        }

        /// <summary>
        /// 邮箱.
        /// </summary>
        public String Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnPropertyValueChange(_.Email, _Email, value);
                this._Email = value.SubStr(100);
            }
        }

        /// <summary>
        /// 网址.
        /// </summary>
        public String WebSite
        {
            get
            {
                return this._WebSite;
            }
            set
            {
                this.OnPropertyValueChange(_.WebSite, _WebSite, value);
                this._WebSite = value.SubStr(200);
            }
        }

        /// <summary>
        /// QQ号.
        /// </summary>
        public String QQ
        {
            get
            {
                return this._QQ;
            }
            set
            {
                this.OnPropertyValueChange(_.QQ, _QQ, value);
                this._QQ = value.SubStr(50);
            }
        }

        /// <summary>
        /// 地址.
        /// </summary>
        public String Address
        {
            get
            {
                return this._Address;
            }
            set
            {
                this.OnPropertyValueChange(_.Address, _Address, value);
                this._Address = value.SubStr(200);
            }
        }

        /// <summary>
        /// 联系人.
        /// </summary>
        public String Contact
        {
            get
            {
                return this._Contact;
            }
            set
            {
                this.OnPropertyValueChange(_.Contact, _Contact, value);
                this._Contact = value.SubStr(100);
            }
        }

        /// <summary>
        /// 备注.
        /// </summary>
        public String Remark
        {
            get
            {
                return this._Remark;
            }
            set
            {
                this.OnPropertyValueChange(_.Remark, _Remark, value);
                this._Remark = value.SubStr(8000);
            }
        }

        /// <summary>
        /// 简介.
        /// </summary>
        public String BriefIntroduction
        {
            get
            {
                return this._BriefIntroduction;
            }
            set
            {
                this.OnPropertyValueChange(_.BriefIntroduction, _BriefIntroduction, value);
                this._BriefIntroduction = value;
            }
        }

        /// <summary>
        /// Logo文件路径.
        /// </summary>
        public String LogoFilePath
        {
            get
            {
                return this._LogoFilePath;
            }
            set
            {
                this.OnPropertyValueChange(_.LogoFilePath, _LogoFilePath, value);
                this._LogoFilePath = value.SubStr(100);
            }
        }

        /// <summary>
        /// 当前用户数.
        /// </summary>
        public Int32? CurrentUserCount
        {
            get
            {
                return this._CurrentUserCount;
            }
            set
            {
                this.OnPropertyValueChange(_.CurrentUserCount, _CurrentUserCount, value);
                this._CurrentUserCount = value;
            }
        }

        /// <summary>
        /// 帐户余额.
        /// </summary>
        public Decimal? AmountBalance
        {
            get
            {
                return this._AmountBalance;
            }
            set
            {
                this.OnPropertyValueChange(_.AmountBalance, _AmountBalance, value);
                this._AmountBalance = value;
            }
        }

        /// <summary>
        /// 是否启用(1:禁用，2:启用，4:删除).
        /// </summary>
        public Int32? IsActive
        {
            get
            {
                return this._IsActive;
            }
            set
            {
                this.OnPropertyValueChange(_.IsActive, _IsActive, value);
                this._IsActive = value;
            }
        }

        /// <summary>
        /// 到期时间.
        /// </summary>
        public DateTime? ExpirationTime
        {
            get
            {
                return this._ExpirationTime;
            }
            set
            {
                this.OnPropertyValueChange(_.ExpirationTime, _ExpirationTime, value);
                this._ExpirationTime = value;
            }
        }

        /// <summary>
        /// 库存标识库.
        /// </summary>
        public String StockMarkNames
        {
            get
            {
                return this._StockMarkNames;
            }
            set
            {
                this.OnPropertyValueChange(_.StockMarkNames, _StockMarkNames, value);
                this._StockMarkNames = value.SubStr(1000);
            }
        }

        /// <summary>
        /// 是否开启数据自动备份.
        /// </summary>
        public Boolean? StartAutoBackupData
        {
            get
            {
                return this._StartAutoBackupData;
            }
            set
            {
                this.OnPropertyValueChange(_.StartAutoBackupData, _StartAutoBackupData, value);
                this._StartAutoBackupData = value;
            }
        }

        /// <summary>
        /// 绑定备份机器的MAC地址.
        /// </summary>
        public String MacAddressForBackup
        {
            get
            {
                return this._MacAddressForBackup;
            }
            set
            {
                this.OnPropertyValueChange(_.MacAddressForBackup, _MacAddressForBackup, value);
                this._MacAddressForBackup = value.SubStr(100);
            }
        }

        /// <summary>
        /// 出货单需要审核.
        /// </summary>
        public Boolean? STKOutNeedAudit
        {
            get
            {
                return this._STKOutNeedAudit;
            }
            set
            {
                this.OnPropertyValueChange(_.STKOutNeedAudit, _STKOutNeedAudit, value);
                this._STKOutNeedAudit = value;
            }
        }

        /// <summary>
        /// 入库单需要审核.
        /// </summary>
        public Boolean? STKInNeedAudit
        {
            get
            {
                return this._STKInNeedAudit;
            }
            set
            {
                this.OnPropertyValueChange(_.STKInNeedAudit, _STKInNeedAudit, value);
                this._STKInNeedAudit = value;
            }
        }

        /// <summary>
        /// 创建时间.
        /// </summary>
        public DateTime? CreatedTime
        {
            get
            {
                return this._CreatedTime;
            }
            set
            {
                this.OnPropertyValueChange(_.CreatedTime, _CreatedTime, value);
                this._CreatedTime = value;
            }
        }

        /// <summary>
        /// 创建人ID.
        /// </summary>
        public Int32? CreatedByID
        {
            get
            {
                return this._CreatedByID;
            }
            set
            {
                this.OnPropertyValueChange(_.CreatedByID, _CreatedByID, value);
                this._CreatedByID = value;
            }
        }

        /// <summary>
        /// 创建人名称.
        /// </summary>
        public String CreatedByName
        {
            get
            {
                return this._CreatedByName;
            }
            set
            {
                this.OnPropertyValueChange(_.CreatedByName, _CreatedByName, value);
                this._CreatedByName = value.SubStr(50);
            }
        }

        /// <summary>
        /// 品牌.
        /// </summary>
        public String Brand
        {
            get
            {
                return this._Brand;
            }
            set
            {
                this.OnPropertyValueChange(_.Brand, _Brand, value);
                this._Brand = value.SubStr(50);
            }
        }

        /// <summary>
        /// 公司标签.
        /// </summary>
        public String LableName
        {
            get
            {
                return this._LableName;
            }
            set
            {
                this.OnPropertyValueChange(_.LableName, _LableName, value);
                this._LableName = value.SubStr(50);
            }
        }

        /// <summary>
        /// 热卖产品.
        /// </summary>
        public String Product
        {
            get
            {
                return this._Product;
            }
            set
            {
                this.OnPropertyValueChange(_.Product, _Product, value);
                this._Product = value.SubStr(50);
            }
        }

        /// <summary>
        /// 公司签名.
        /// </summary>
        public String Sign
        {
            get
            {
                return this._Sign;
            }
            set
            {
                this.OnPropertyValueChange(_.Sign, _Sign, value);
                this._Sign = value.SubStr(36);
            }
        }

        /// <summary>
        /// 不允许负库存出库.
        /// </summary>
        public Boolean? DontAllowNegativeStock
        {
            get
            {
                return this._DontAllowNegativeStock;
            }
            set
            {
                this.OnPropertyValueChange(_.DontAllowNegativeStock, _DontAllowNegativeStock, value);
                this._DontAllowNegativeStock = value;
            }
        }

        /// <summary>
        /// 是否显示云价格.
        /// </summary>
        public Boolean? ShowCloudPrice
        {
            get
            {
                return this._ShowCloudPrice;
            }
            set
            {
                this.OnPropertyValueChange(_.ShowCloudPrice, _ShowCloudPrice, value);
                this._ShowCloudPrice = value;
            }
        }

        /// <summary>
        /// .
        /// </summary>
        public Boolean? AllowPopTipsForCall
        {
            get
            {
                return this._AllowPopTipsForCall;
            }
            set
            {
                this.OnPropertyValueChange(_.AllowPopTipsForCall, _AllowPopTipsForCall, value);
                this._AllowPopTipsForCall = value;
            }
        }

        /// <summary>
        /// 允许使用IC交易网热卖发布工具.
        /// </summary>
        public Boolean? AllowICNetHotsForTools
        {
            get
            {
                return this._AllowICNetHotsForTools;
            }
            set
            {
                this.OnPropertyValueChange(_.AllowICNetHotsForTools, _AllowICNetHotsForTools, value);
                this._AllowICNetHotsForTools = value;
            }
        }

        /// <summary>
        /// 电话盒使用控件驱动.
        /// </summary>
        public Boolean? IsUseOcxPhoneBox
        {
            get
            {
                return this._IsUseOcxPhoneBox;
            }
            set
            {
                this.OnPropertyValueChange(_.IsUseOcxPhoneBox, _IsUseOcxPhoneBox, value);
                this._IsUseOcxPhoneBox = value;
            }
        }

        /// <summary>
        /// 推荐人.
        /// </summary>
        public String Reference
        {
            get
            {
                return this._Reference;
            }
            set
            {
                this.OnPropertyValueChange(_.Reference, _Reference, value);
                this._Reference = value.SubStr(50);
            }
        }

        /// <summary>
        /// 客户来源.
        /// </summary>
        public Int32? FromBy
        {
            get
            {
                return this._FromBy;
            }
            set
            {
                this.OnPropertyValueChange(_.FromBy, _FromBy, value);
                this._FromBy = value;
            }
        }

        /// <summary>
        /// .
        /// </summary>
        public Boolean? IsDeleted
        {
            get
            {
                return this._IsDeleted;
            }
            set
            {
                this.OnPropertyValueChange(_.IsDeleted, _IsDeleted, value);
                this._IsDeleted = value;
            }
        }

        #endregion
        /// <summary>
        /// 获取实体对应的表名
        /// </summary>
        protected override Table GetTable()
        {
            return new Table<SYS_CompanyInfo>("SYS_CompanyInfo");
        }

        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        protected override Field GetIdentityField()
        {
            return _.AutoID;
        }

        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        protected override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.AutoID
			};
        }

        /// <summary>
        /// 获取列信息
        /// </summary>
        protected override Field[] GetFields()
        {
            return new Field[] {
				_.AutoID,		
				_.CompanyID,		
				_.RegistAccount,		
				_.EnabledSubAccountRole,		
				_.CompanyName,		
				_.ShortName,		
				_.CompanyCode,		
				_.PartnerCode,		
				_.PartnerUserID,		
				_.BillNoPrefix,		
				_.Telephone,		
				_.Mobile,		
				_.Fax,		
				_.Email,		
				_.WebSite,		
				_.QQ,		
				_.Address,		
				_.Contact,		
				_.Remark,		
				_.BriefIntroduction,		
				_.LogoFilePath,		
				_.CurrentUserCount,		
				_.AmountBalance,		
				_.IsActive,		
				_.ExpirationTime,		
				_.StockMarkNames,		
				_.StartAutoBackupData,		
				_.MacAddressForBackup,		
				_.STKOutNeedAudit,		
				_.STKInNeedAudit,		
				_.CreatedTime,		
				_.CreatedByID,		
				_.CreatedByName,		
				_.Brand,		
				_.LableName,		
				_.Product,		
				_.Sign,		
				_.DontAllowNegativeStock,		
				_.ShowCloudPrice,		
				_.AllowPopTipsForCall,		
				_.AllowICNetHotsForTools,		
				_.IsUseOcxPhoneBox,		
				_.Reference,		
				_.FromBy,		
				_.IsDeleted		
			};
        }

        /// <summary>
        /// 获取列数据
        /// </summary>
        protected override object[] GetValues()
        {
            return new object[] {
				this._AutoID,		
				this._CompanyID,		
				this._RegistAccount,		
				this._EnabledSubAccountRole,		
				this._CompanyName,		
				this._ShortName,		
				this._CompanyCode,		
				this._PartnerCode,		
				this._PartnerUserID,		
				this._BillNoPrefix,		
				this._Telephone,		
				this._Mobile,		
				this._Fax,		
				this._Email,		
				this._WebSite,		
				this._QQ,		
				this._Address,		
				this._Contact,		
				this._Remark,		
				this._BriefIntroduction,		
				this._LogoFilePath,		
				this._CurrentUserCount,		
				this._AmountBalance,		
				this._IsActive,		
				this._ExpirationTime,		
				this._StockMarkNames,		
				this._StartAutoBackupData,		
				this._MacAddressForBackup,		
				this._STKOutNeedAudit,		
				this._STKInNeedAudit,		
				this._CreatedTime,		
				this._CreatedByID,		
				this._CreatedByName,		
				this._Brand,		
				this._LableName,		
				this._Product,		
				this._Sign,		
				this._DontAllowNegativeStock,		
				this._ShowCloudPrice,		
				this._AllowPopTipsForCall,		
				this._AllowICNetHotsForTools,		
				this._IsUseOcxPhoneBox,		
				this._Reference,		
				this._FromBy,		
				this._IsDeleted		
			};
        }

        /// <summary>
        /// 给当前实体赋值
        /// </summary>
        protected override void SetValues(IRowReader reader)
        {
            if ((false == reader.IsDBNull(_.AutoID)))
            {
                this._AutoID = reader.GetInt32(_.AutoID);
            }
            if ((false == reader.IsDBNull(_.CompanyID)))
            {
                this._CompanyID = reader.GetGuid(_.CompanyID);
            }
            if ((false == reader.IsDBNull(_.RegistAccount)))
            {
                this._RegistAccount = reader.GetString(_.RegistAccount);
            }
            if ((false == reader.IsDBNull(_.EnabledSubAccountRole)))
            {
                this._EnabledSubAccountRole = reader.GetBoolean(_.EnabledSubAccountRole);
            }
            if ((false == reader.IsDBNull(_.CompanyName)))
            {
                this._CompanyName = reader.GetString(_.CompanyName);
            }
            if ((false == reader.IsDBNull(_.ShortName)))
            {
                this._ShortName = reader.GetString(_.ShortName);
            }
            if ((false == reader.IsDBNull(_.CompanyCode)))
            {
                this._CompanyCode = reader.GetString(_.CompanyCode);
            }
            if ((false == reader.IsDBNull(_.PartnerCode)))
            {
                this._PartnerCode = reader.GetString(_.PartnerCode);
            }
            if ((false == reader.IsDBNull(_.PartnerUserID)))
            {
                this._PartnerUserID = reader.GetString(_.PartnerUserID);
            }
            if ((false == reader.IsDBNull(_.BillNoPrefix)))
            {
                this._BillNoPrefix = reader.GetString(_.BillNoPrefix);
            }
            if ((false == reader.IsDBNull(_.Telephone)))
            {
                this._Telephone = reader.GetString(_.Telephone);
            }
            if ((false == reader.IsDBNull(_.Mobile)))
            {
                this._Mobile = reader.GetString(_.Mobile);
            }
            if ((false == reader.IsDBNull(_.Fax)))
            {
                this._Fax = reader.GetString(_.Fax);
            }
            if ((false == reader.IsDBNull(_.Email)))
            {
                this._Email = reader.GetString(_.Email);
            }
            if ((false == reader.IsDBNull(_.WebSite)))
            {
                this._WebSite = reader.GetString(_.WebSite);
            }
            if ((false == reader.IsDBNull(_.QQ)))
            {
                this._QQ = reader.GetString(_.QQ);
            }
            if ((false == reader.IsDBNull(_.Address)))
            {
                this._Address = reader.GetString(_.Address);
            }
            if ((false == reader.IsDBNull(_.Contact)))
            {
                this._Contact = reader.GetString(_.Contact);
            }
            if ((false == reader.IsDBNull(_.Remark)))
            {
                this._Remark = reader.GetString(_.Remark);
            }
            if ((false == reader.IsDBNull(_.BriefIntroduction)))
            {
                this._BriefIntroduction = reader.GetString(_.BriefIntroduction);
            }
            if ((false == reader.IsDBNull(_.LogoFilePath)))
            {
                this._LogoFilePath = reader.GetString(_.LogoFilePath);
            }
            if ((false == reader.IsDBNull(_.CurrentUserCount)))
            {
                this._CurrentUserCount = reader.GetInt32(_.CurrentUserCount);
            }
            if ((false == reader.IsDBNull(_.AmountBalance)))
            {
                this._AmountBalance = reader.GetDecimal(_.AmountBalance);
            }
            if ((false == reader.IsDBNull(_.IsActive)))
            {
                this._IsActive = reader.GetInt32(_.IsActive);
            }
            if ((false == reader.IsDBNull(_.ExpirationTime)))
            {
                this._ExpirationTime = reader.GetDateTime(_.ExpirationTime);
            }
            if ((false == reader.IsDBNull(_.StockMarkNames)))
            {
                this._StockMarkNames = reader.GetString(_.StockMarkNames);
            }
            if ((false == reader.IsDBNull(_.StartAutoBackupData)))
            {
                this._StartAutoBackupData = reader.GetBoolean(_.StartAutoBackupData);
            }
            if ((false == reader.IsDBNull(_.MacAddressForBackup)))
            {
                this._MacAddressForBackup = reader.GetString(_.MacAddressForBackup);
            }
            if ((false == reader.IsDBNull(_.STKOutNeedAudit)))
            {
                this._STKOutNeedAudit = reader.GetBoolean(_.STKOutNeedAudit);
            }
            if ((false == reader.IsDBNull(_.STKInNeedAudit)))
            {
                this._STKInNeedAudit = reader.GetBoolean(_.STKInNeedAudit);
            }
            if ((false == reader.IsDBNull(_.CreatedTime)))
            {
                this._CreatedTime = reader.GetDateTime(_.CreatedTime);
            }
            if ((false == reader.IsDBNull(_.CreatedByID)))
            {
                this._CreatedByID = reader.GetInt32(_.CreatedByID);
            }
            if ((false == reader.IsDBNull(_.CreatedByName)))
            {
                this._CreatedByName = reader.GetString(_.CreatedByName);
            }
            if ((false == reader.IsDBNull(_.Brand)))
            {
                this._Brand = reader.GetString(_.Brand);
            }
            if ((false == reader.IsDBNull(_.LableName)))
            {
                this._LableName = reader.GetString(_.LableName);
            }
            if ((false == reader.IsDBNull(_.Product)))
            {
                this._Product = reader.GetString(_.Product);
            }
            if ((false == reader.IsDBNull(_.Sign)))
            {
                this._Sign = reader.GetString(_.Sign);
            }
            if ((false == reader.IsDBNull(_.DontAllowNegativeStock)))
            {
                this._DontAllowNegativeStock = reader.GetBoolean(_.DontAllowNegativeStock);
            }
            if ((false == reader.IsDBNull(_.ShowCloudPrice)))
            {
                this._ShowCloudPrice = reader.GetBoolean(_.ShowCloudPrice);
            }
            if ((false == reader.IsDBNull(_.AllowPopTipsForCall)))
            {
                this._AllowPopTipsForCall = reader.GetBoolean(_.AllowPopTipsForCall);
            }
            if ((false == reader.IsDBNull(_.AllowICNetHotsForTools)))
            {
                this._AllowICNetHotsForTools = reader.GetBoolean(_.AllowICNetHotsForTools);
            }
            if ((false == reader.IsDBNull(_.IsUseOcxPhoneBox)))
            {
                this._IsUseOcxPhoneBox = reader.GetBoolean(_.IsUseOcxPhoneBox);
            }
            if ((false == reader.IsDBNull(_.Reference)))
            {
                this._Reference = reader.GetString(_.Reference);
            }
            if ((false == reader.IsDBNull(_.FromBy)))
            {
                this._FromBy = reader.GetInt32(_.FromBy);
            }
            if ((false == reader.IsDBNull(_.IsDeleted)))
            {
                this._IsDeleted = reader.GetBoolean(_.IsDeleted);
            }
        }

        public override int GetHashCode()
        {
            return base.GetHashCode();
        }

        public override bool Equals(object obj)
        {
            if ((obj == null))
            {
                return false;
            }
            if ((false == typeof(SYS_CompanyInfo).IsAssignableFrom(obj.GetType())))
            {
                return false;
            }
            if ((((object)(this)) == ((object)(obj))))
            {
                return true;
            }
            return false;
        }

        public class _
        {

            /// <summary>
            /// 表示选择所有列，与*等同
            /// </summary>
            public static AllField All = new AllField<SYS_CompanyInfo>();

            /// <summary>
            /// 自增ID - 字段名：AutoID - 数据类型：Int32?
            /// </summary>
            public static Field AutoID = new Field<SYS_CompanyInfo>("AutoID");
            /// <summary>
            /// 公司ID - 字段名：CompanyID - 数据类型：Guid?
            /// </summary>
            public static Field CompanyID = new Field<SYS_CompanyInfo>("CompanyID");
            /// <summary>
            /// 注册帐号 - 字段名：RegistAccount - 数据类型：String
            /// </summary>
            public static Field RegistAccount = new Field<SYS_CompanyInfo>("RegistAccount");
            /// <summary>
            /// 启用子帐号权限控制 - 字段名：EnabledSubAccountRole - 数据类型：Boolean?
            /// </summary>
            public static Field EnabledSubAccountRole = new Field<SYS_CompanyInfo>("EnabledSubAccountRole");
            /// <summary>
            /// 公司名称 - 字段名：CompanyName - 数据类型：String
            /// </summary>
            public static Field CompanyName = new Field<SYS_CompanyInfo>("CompanyName");
            /// <summary>
            /// 简称 - 字段名：ShortName - 数据类型：String
            /// </summary>
            public static Field ShortName = new Field<SYS_CompanyInfo>("ShortName");
            /// <summary>
            /// 公司编码 - 字段名：CompanyCode - 数据类型：String
            /// </summary>
            public static Field CompanyCode = new Field<SYS_CompanyInfo>("CompanyCode");
            /// <summary>
            /// 合作平台代码 - 字段名：PartnerCode - 数据类型：String
            /// </summary>
            public static Field PartnerCode = new Field<SYS_CompanyInfo>("PartnerCode");
            /// <summary>
            /// 合作伙伴会员ID - 字段名：PartnerUserID - 数据类型：String
            /// </summary>
            public static Field PartnerUserID = new Field<SYS_CompanyInfo>("PartnerUserID");
            /// <summary>
            /// 单据编号前缀 - 字段名：BillNoPrefix - 数据类型：String
            /// </summary>
            public static Field BillNoPrefix = new Field<SYS_CompanyInfo>("BillNoPrefix");
            /// <summary>
            /// 电话 - 字段名：Telephone - 数据类型：String
            /// </summary>
            public static Field Telephone = new Field<SYS_CompanyInfo>("Telephone");
            /// <summary>
            /// 手机 - 字段名：Mobile - 数据类型：String
            /// </summary>
            public static Field Mobile = new Field<SYS_CompanyInfo>("Mobile");
            /// <summary>
            /// 传真 - 字段名：Fax - 数据类型：String
            /// </summary>
            public static Field Fax = new Field<SYS_CompanyInfo>("Fax");
            /// <summary>
            /// 邮箱 - 字段名：Email - 数据类型：String
            /// </summary>
            public static Field Email = new Field<SYS_CompanyInfo>("Email");
            /// <summary>
            /// 网址 - 字段名：WebSite - 数据类型：String
            /// </summary>
            public static Field WebSite = new Field<SYS_CompanyInfo>("WebSite");
            /// <summary>
            /// QQ号 - 字段名：QQ - 数据类型：String
            /// </summary>
            public static Field QQ = new Field<SYS_CompanyInfo>("QQ");
            /// <summary>
            /// 地址 - 字段名：Address - 数据类型：String
            /// </summary>
            public static Field Address = new Field<SYS_CompanyInfo>("Address");
            /// <summary>
            /// 联系人 - 字段名：Contact - 数据类型：String
            /// </summary>
            public static Field Contact = new Field<SYS_CompanyInfo>("Contact");
            /// <summary>
            /// 备注 - 字段名：Remark - 数据类型：String
            /// </summary>
            public static Field Remark = new Field<SYS_CompanyInfo>("Remark");
            /// <summary>
            /// 简介 - 字段名：BriefIntroduction - 数据类型：String
            /// </summary>
            public static Field BriefIntroduction = new Field<SYS_CompanyInfo>("BriefIntroduction");
            /// <summary>
            /// Logo文件路径 - 字段名：LogoFilePath - 数据类型：String
            /// </summary>
            public static Field LogoFilePath = new Field<SYS_CompanyInfo>("LogoFilePath");
            /// <summary>
            /// 当前用户数 - 字段名：CurrentUserCount - 数据类型：Int32?
            /// </summary>
            public static Field CurrentUserCount = new Field<SYS_CompanyInfo>("CurrentUserCount");
            /// <summary>
            /// 帐户余额 - 字段名：AmountBalance - 数据类型：Decimal?
            /// </summary>
            public static Field AmountBalance = new Field<SYS_CompanyInfo>("AmountBalance");
            /// <summary>
            /// 是否启用(1:禁用，2:启用，4:删除) - 字段名：IsActive - 数据类型：Int32?
            /// </summary>
            public static Field IsActive = new Field<SYS_CompanyInfo>("IsActive");
            /// <summary>
            /// 到期时间 - 字段名：ExpirationTime - 数据类型：DateTime?
            /// </summary>
            public static Field ExpirationTime = new Field<SYS_CompanyInfo>("ExpirationTime");
            /// <summary>
            /// 库存标识库 - 字段名：StockMarkNames - 数据类型：String
            /// </summary>
            public static Field StockMarkNames = new Field<SYS_CompanyInfo>("StockMarkNames");
            /// <summary>
            /// 是否开启数据自动备份 - 字段名：StartAutoBackupData - 数据类型：Boolean?
            /// </summary>
            public static Field StartAutoBackupData = new Field<SYS_CompanyInfo>("StartAutoBackupData");
            /// <summary>
            /// 绑定备份机器的MAC地址 - 字段名：MacAddressForBackup - 数据类型：String
            /// </summary>
            public static Field MacAddressForBackup = new Field<SYS_CompanyInfo>("MacAddressForBackup");
            /// <summary>
            /// 出货单需要审核 - 字段名：STKOutNeedAudit - 数据类型：Boolean?
            /// </summary>
            public static Field STKOutNeedAudit = new Field<SYS_CompanyInfo>("STKOutNeedAudit");
            /// <summary>
            /// 入库单需要审核 - 字段名：STKInNeedAudit - 数据类型：Boolean?
            /// </summary>
            public static Field STKInNeedAudit = new Field<SYS_CompanyInfo>("STKInNeedAudit");
            /// <summary>
            /// 创建时间 - 字段名：CreatedTime - 数据类型：DateTime?
            /// </summary>
            public static Field CreatedTime = new Field<SYS_CompanyInfo>("CreatedTime");
            /// <summary>
            /// 创建人ID - 字段名：CreatedByID - 数据类型：Int32?
            /// </summary>
            public static Field CreatedByID = new Field<SYS_CompanyInfo>("CreatedByID");
            /// <summary>
            /// 创建人名称 - 字段名：CreatedByName - 数据类型：String
            /// </summary>
            public static Field CreatedByName = new Field<SYS_CompanyInfo>("CreatedByName");
            /// <summary>
            /// 品牌 - 字段名：Brand - 数据类型：String
            /// </summary>
            public static Field Brand = new Field<SYS_CompanyInfo>("Brand");
            /// <summary>
            /// 公司标签 - 字段名：LableName - 数据类型：String
            /// </summary>
            public static Field LableName = new Field<SYS_CompanyInfo>("LableName");
            /// <summary>
            /// 热卖产品 - 字段名：Product - 数据类型：String
            /// </summary>
            public static Field Product = new Field<SYS_CompanyInfo>("Product");
            /// <summary>
            /// 公司签名 - 字段名：Sign - 数据类型：String
            /// </summary>
            public static Field Sign = new Field<SYS_CompanyInfo>("Sign");
            /// <summary>
            /// 不允许负库存出库 - 字段名：DontAllowNegativeStock - 数据类型：Boolean?
            /// </summary>
            public static Field DontAllowNegativeStock = new Field<SYS_CompanyInfo>("DontAllowNegativeStock");
            /// <summary>
            /// 是否显示云价格 - 字段名：ShowCloudPrice - 数据类型：Boolean?
            /// </summary>
            public static Field ShowCloudPrice = new Field<SYS_CompanyInfo>("ShowCloudPrice");
            /// <summary>
            ///  - 字段名：AllowPopTipsForCall - 数据类型：Boolean?
            /// </summary>
            public static Field AllowPopTipsForCall = new Field<SYS_CompanyInfo>("AllowPopTipsForCall");
            /// <summary>
            /// 允许使用IC交易网热卖发布工具 - 字段名：AllowICNetHotsForTools - 数据类型：Boolean?
            /// </summary>
            public static Field AllowICNetHotsForTools = new Field<SYS_CompanyInfo>("AllowICNetHotsForTools");
            /// <summary>
            /// 电话盒使用控件驱动 - 字段名：IsUseOcxPhoneBox - 数据类型：Boolean?
            /// </summary>
            public static Field IsUseOcxPhoneBox = new Field<SYS_CompanyInfo>("IsUseOcxPhoneBox");
            /// <summary>
            /// 推荐人 - 字段名：Reference - 数据类型：String
            /// </summary>
            public static Field Reference = new Field<SYS_CompanyInfo>("Reference");
            /// <summary>
            /// 客户来源 - 字段名：FromBy - 数据类型：Int32?
            /// </summary>
            public static Field FromBy = new Field<SYS_CompanyInfo>("FromBy");
            /// <summary>
            ///  - 字段名：IsDeleted - 数据类型：Boolean?
            /// </summary>
            public static Field IsDeleted = new Field<SYS_CompanyInfo>("IsDeleted");
        }
    }
}
