//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by CodeSmith Template.
//
//     Creater: David
//     Date:    2014/11/6
//     Time:    11:15
//     Version: 4.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

/// <summary>
/// CodeSmith自动生成的实体
/// </summary>
namespace ZNLCRM.Entity.DBModel
{	
	using System;
	using MySoft.Data;
	using ZNLCRM.Utility;
    using ZNLFrame.Entity;
    /// <summary>
    /// 表名：FIN_CashBankJournal 主键列：CBJID
    /// </summary>
    [SerializableAttribute()]
	public partial class FIN_CashBankJournal : BaseEntity
	{
		#region Private Properties
		
		private Int32 _CBJID;
		private Int32? _CBID;
		private String _CBNo;
		private Guid? _GCompanyID;
		private DateTime? _BusinessDate;
		private Int32? _CompanyID;
		private String _CompanyName;
		private String _BillType;
		private Int32? _SourceBillID;
		private String _SourceBillNo;
		private Decimal? _InCome;
		private Decimal? _Expenditure;
		private Decimal? _ExchangeRate;
		private Decimal? _TaxRate;
		private Decimal? _SCAmount;
		private Int32? _OperatorID;
		private String _OperatorName;
		private DateTime? _CreatedTime;
		private String _Abstract;
		private Int32? _OrgID;
		private String _OrgName;
		private Int32? _DeptID;
		private String _DeptName;
		private Boolean? _IsCheck;
		private String _CheckEmpName;
		private DateTime? _CheckDate;
		
		#endregion
		
		#region Public Properties
		
		/// <summary>
		/// 现金银行日记帐ID.
		/// </summary>
		public Int32 CBJID
		{
			get 
			{
				return _CBJID;
			}
			set 
			{
				this.OnPropertyValueChange(_.CBJID, _CBJID , value);
				this._CBJID = value;
			}
		}
		
		/// <summary>
		/// 账号ID.
		/// </summary>
		public Int32? CBID
		{
			get 
			{
				return this._CBID;
			}
			set 
			{
				this.OnPropertyValueChange(_.CBID, _CBID , value);
				this._CBID = value;
			}
		}

		/// <summary>
		/// 帐号编码.
		/// </summary>
		public String CBNo
		{
			get 
			{
				return this._CBNo;
			}
			set 
			{
				this.OnPropertyValueChange(_.CBNo, _CBNo , value);
				this._CBNo = value.SubStr(50);
			}
		}

		/// <summary>
		/// 所属公司ID.
		/// </summary>
		public Guid? GCompanyID
		{
			get 
			{
				return this._GCompanyID;
			}
			set 
			{
				this.OnPropertyValueChange(_.GCompanyID, _GCompanyID , value);
				this._GCompanyID = value;
			}
		}

		/// <summary>
		/// 业务日期.
		/// </summary>
		public DateTime? BusinessDate
		{
			get 
			{
				return this._BusinessDate;
			}
			set 
			{
				this.OnPropertyValueChange(_.BusinessDate, _BusinessDate , value);
				this._BusinessDate = value;
			}
		}

		/// <summary>
		/// 公司ID.
		/// </summary>
		public Int32? CompanyID
		{
			get 
			{
				return this._CompanyID;
			}
			set 
			{
				this.OnPropertyValueChange(_.CompanyID, _CompanyID , value);
				this._CompanyID = value;
			}
		}

		/// <summary>
		/// 公司名称.
		/// </summary>
		public String CompanyName
		{
			get 
			{
				return this._CompanyName;
			}
			set 
			{
				this.OnPropertyValueChange(_.CompanyName, _CompanyName , value);
				this._CompanyName = value.SubStr(200);
			}
		}

		/// <summary>
		/// 单据类型.
		/// </summary>
		public String BillType
		{
			get 
			{
				return this._BillType;
			}
			set 
			{
				this.OnPropertyValueChange(_.BillType, _BillType , value);
				this._BillType = value.SubStr(20);
			}
		}

		/// <summary>
		/// 内部单据ID.
		/// </summary>
		public Int32? SourceBillID
		{
			get 
			{
				return this._SourceBillID;
			}
			set 
			{
				this.OnPropertyValueChange(_.SourceBillID, _SourceBillID , value);
				this._SourceBillID = value;
			}
		}

		/// <summary>
		/// 源单据编号.
		/// </summary>
		public String SourceBillNo
		{
			get 
			{
				return this._SourceBillNo;
			}
			set 
			{
				this.OnPropertyValueChange(_.SourceBillNo, _SourceBillNo , value);
				this._SourceBillNo = value.SubStr(50);
			}
		}

		/// <summary>
		/// 原币收入.
		/// </summary>
		public Decimal? InCome
		{
			get 
			{
				return this._InCome;
			}
			set 
			{
				this.OnPropertyValueChange(_.InCome, _InCome , value);
				this._InCome = value;
			}
		}

		/// <summary>
		/// 原币支出.
		/// </summary>
		public Decimal? Expenditure
		{
			get 
			{
				return this._Expenditure;
			}
			set 
			{
				this.OnPropertyValueChange(_.Expenditure, _Expenditure , value);
				this._Expenditure = value;
			}
		}

		/// <summary>
		/// 汇率.
		/// </summary>
		public Decimal? ExchangeRate
		{
			get 
			{
				return this._ExchangeRate;
			}
			set 
			{
				this.OnPropertyValueChange(_.ExchangeRate, _ExchangeRate , value);
				this._ExchangeRate = value;
			}
		}

		/// <summary>
		/// 税率.
		/// </summary>
		public Decimal? TaxRate
		{
			get 
			{
				return this._TaxRate;
			}
			set 
			{
				this.OnPropertyValueChange(_.TaxRate, _TaxRate , value);
				this._TaxRate = value;
			}
		}

		/// <summary>
		/// 本币金额.
		/// </summary>
		public Decimal? SCAmount
		{
			get 
			{
				return this._SCAmount;
			}
			set 
			{
				this.OnPropertyValueChange(_.SCAmount, _SCAmount , value);
				this._SCAmount = value;
			}
		}

		/// <summary>
		/// 经手人ID.
		/// </summary>
		public Int32? OperatorID
		{
			get 
			{
				return this._OperatorID;
			}
			set 
			{
				this.OnPropertyValueChange(_.OperatorID, _OperatorID , value);
				this._OperatorID = value;
			}
		}

		/// <summary>
		/// 经手人.
		/// </summary>
		public String OperatorName
		{
			get 
			{
				return this._OperatorName;
			}
			set 
			{
				this.OnPropertyValueChange(_.OperatorName, _OperatorName , value);
				this._OperatorName = value.SubStr(50);
			}
		}

		/// <summary>
		/// .
		/// </summary>
		public DateTime? CreatedTime
		{
			get 
			{
				return this._CreatedTime;
			}
			set 
			{
				this.OnPropertyValueChange(_.CreatedTime, _CreatedTime , value);
				this._CreatedTime = value;
			}
		}

		/// <summary>
		/// 摘要.
		/// </summary>
		public String Abstract
		{
			get 
			{
				return this._Abstract;
			}
			set 
			{
				this.OnPropertyValueChange(_.Abstract, _Abstract , value);
				this._Abstract = value.SubStr(500);
			}
		}

		/// <summary>
		/// 机构Id.
		/// </summary>
		public Int32? OrgID
		{
			get 
			{
				return this._OrgID;
			}
			set 
			{
				this.OnPropertyValueChange(_.OrgID, _OrgID , value);
				this._OrgID = value;
			}
		}

		/// <summary>
		/// 机构名称.
		/// </summary>
		public String OrgName
		{
			get 
			{
				return this._OrgName;
			}
			set 
			{
				this.OnPropertyValueChange(_.OrgName, _OrgName , value);
				this._OrgName = value.SubStr(50);
			}
		}

		/// <summary>
		/// 部门ID.
		/// </summary>
		public Int32? DeptID
		{
			get 
			{
				return this._DeptID;
			}
			set 
			{
				this.OnPropertyValueChange(_.DeptID, _DeptID , value);
				this._DeptID = value;
			}
		}

		/// <summary>
		/// 部门.
		/// </summary>
		public String DeptName
		{
			get 
			{
				return this._DeptName;
			}
			set 
			{
				this.OnPropertyValueChange(_.DeptName, _DeptName , value);
				this._DeptName = value.SubStr(50);
			}
		}

		/// <summary>
		/// 对帐.
		/// </summary>
		public Boolean? IsCheck
		{
			get 
			{
				return this._IsCheck;
			}
			set 
			{
				this.OnPropertyValueChange(_.IsCheck, _IsCheck , value);
				this._IsCheck = value;
			}
		}

		/// <summary>
		/// 对帐人.
		/// </summary>
		public String CheckEmpName
		{
			get 
			{
				return this._CheckEmpName;
			}
			set 
			{
				this.OnPropertyValueChange(_.CheckEmpName, _CheckEmpName , value);
				this._CheckEmpName = value.SubStr(50);
			}
		}

		/// <summary>
		/// 对帐日期.
		/// </summary>
		public DateTime? CheckDate
		{
			get 
			{
				return this._CheckDate;
			}
			set 
			{
				this.OnPropertyValueChange(_.CheckDate, _CheckDate , value);
				this._CheckDate = value;
			}
		}
		
		#endregion
	    /// <summary>
        /// 获取实体对应的表名
        /// </summary>
        protected override Table GetTable() {
            return new Table< FIN_CashBankJournal >("FIN_CashBankJournal");
        }
		
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        protected override Field GetIdentityField() {
            return _.CBJID;
        }  			
		
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        protected override Field[] GetPrimaryKeyFields() {
            return new Field[] {
				_.CBJID
			};
        }
			
	    /// <summary>
        /// 获取列信息
        /// </summary>
        protected override Field[] GetFields() {
            return new Field[] {
				_.CBJID,		
				_.CBID,		
				_.CBNo,		
				_.GCompanyID,		
				_.BusinessDate,		
				_.CompanyID,		
				_.CompanyName,		
				_.BillType,		
				_.SourceBillID,		
				_.SourceBillNo,		
				_.InCome,		
				_.Expenditure,		
				_.ExchangeRate,		
				_.TaxRate,		
				_.SCAmount,		
				_.OperatorID,		
				_.OperatorName,		
				_.CreatedTime,		
				_.Abstract,		
				_.OrgID,		
				_.OrgName,		
				_.DeptID,		
				_.DeptName,		
				_.IsCheck,		
				_.CheckEmpName,		
				_.CheckDate		
			};
		}
		
	    /// <summary>
        /// 获取列数据
        /// </summary>
        protected override object[] GetValues() {
            return new object[] {
				this._CBJID,		
				this._CBID,		
				this._CBNo,		
				this._GCompanyID,		
				this._BusinessDate,		
				this._CompanyID,		
				this._CompanyName,		
				this._BillType,		
				this._SourceBillID,		
				this._SourceBillNo,		
				this._InCome,		
				this._Expenditure,		
				this._ExchangeRate,		
				this._TaxRate,		
				this._SCAmount,		
				this._OperatorID,		
				this._OperatorName,		
				this._CreatedTime,		
				this._Abstract,		
				this._OrgID,		
				this._OrgName,		
				this._DeptID,		
				this._DeptName,		
				this._IsCheck,		
				this._CheckEmpName,		
				this._CheckDate		
			};
		}
		
	    /// <summary>
        /// 给当前实体赋值
        /// </summary>
        protected override void SetValues(IRowReader reader) {
            if ((false == reader.IsDBNull(_.CBJID))) {
                this._CBJID = reader.GetInt32(_.CBJID);
            }
            if ((false == reader.IsDBNull(_.CBID))) {
                this._CBID = reader.GetInt32(_.CBID);
            }
            if ((false == reader.IsDBNull(_.CBNo))) {
                this._CBNo = reader.GetString(_.CBNo);
            }
            if ((false == reader.IsDBNull(_.GCompanyID))) {
                this._GCompanyID = reader.GetGuid(_.GCompanyID);
            }
            if ((false == reader.IsDBNull(_.BusinessDate))) {
                this._BusinessDate = reader.GetDateTime(_.BusinessDate);
            }
            if ((false == reader.IsDBNull(_.CompanyID))) {
                this._CompanyID = reader.GetInt32(_.CompanyID);
            }
            if ((false == reader.IsDBNull(_.CompanyName))) {
                this._CompanyName = reader.GetString(_.CompanyName);
            }
            if ((false == reader.IsDBNull(_.BillType))) {
                this._BillType = reader.GetString(_.BillType);
            }
            if ((false == reader.IsDBNull(_.SourceBillID))) {
                this._SourceBillID = reader.GetInt32(_.SourceBillID);
            }
            if ((false == reader.IsDBNull(_.SourceBillNo))) {
                this._SourceBillNo = reader.GetString(_.SourceBillNo);
            }
            if ((false == reader.IsDBNull(_.InCome))) {
                this._InCome = reader.GetDecimal(_.InCome);
            }
            if ((false == reader.IsDBNull(_.Expenditure))) {
                this._Expenditure = reader.GetDecimal(_.Expenditure);
            }
            if ((false == reader.IsDBNull(_.ExchangeRate))) {
                this._ExchangeRate = reader.GetDecimal(_.ExchangeRate);
            }
            if ((false == reader.IsDBNull(_.TaxRate))) {
                this._TaxRate = reader.GetDecimal(_.TaxRate);
            }
            if ((false == reader.IsDBNull(_.SCAmount))) {
                this._SCAmount = reader.GetDecimal(_.SCAmount);
            }
            if ((false == reader.IsDBNull(_.OperatorID))) {
                this._OperatorID = reader.GetInt32(_.OperatorID);
            }
            if ((false == reader.IsDBNull(_.OperatorName))) {
                this._OperatorName = reader.GetString(_.OperatorName);
            }
            if ((false == reader.IsDBNull(_.CreatedTime))) {
                this._CreatedTime = reader.GetDateTime(_.CreatedTime);
            }
            if ((false == reader.IsDBNull(_.Abstract))) {
                this._Abstract = reader.GetString(_.Abstract);
            }
            if ((false == reader.IsDBNull(_.OrgID))) {
                this._OrgID = reader.GetInt32(_.OrgID);
            }
            if ((false == reader.IsDBNull(_.OrgName))) {
                this._OrgName = reader.GetString(_.OrgName);
            }
            if ((false == reader.IsDBNull(_.DeptID))) {
                this._DeptID = reader.GetInt32(_.DeptID);
            }
            if ((false == reader.IsDBNull(_.DeptName))) {
                this._DeptName = reader.GetString(_.DeptName);
            }
            if ((false == reader.IsDBNull(_.IsCheck))) {
                this._IsCheck = reader.GetBoolean(_.IsCheck);
            }
            if ((false == reader.IsDBNull(_.CheckEmpName))) {
                this._CheckEmpName = reader.GetString(_.CheckEmpName);
            }
            if ((false == reader.IsDBNull(_.CheckDate))) {
                this._CheckDate = reader.GetDateTime(_.CheckDate);
            }
		}
		
	    public override int GetHashCode() {
            return base.GetHashCode();
        }
        
        public override bool Equals(object obj) {
            if ((obj == null)) {
                return false;
            }
            if ((false == typeof(FIN_CashBankJournal).IsAssignableFrom(obj.GetType()))) {
                return false;
            }
            if ((((object)(this)) == ((object)(obj)))) {
                return true;
            }
            return false;
        }
		
        public class _ {
                
            /// <summary>
            /// 表示选择所有列，与*等同
            /// </summary>
            public static AllField All = new AllField< FIN_CashBankJournal >();
			
		    /// <summary>
            /// 现金银行日记帐ID - 字段名：CBJID - 数据类型：Int32?
            /// </summary>
            public static Field CBJID = new Field< FIN_CashBankJournal >("CBJID");
		    /// <summary>
            /// 账号ID - 字段名：CBID - 数据类型：Int32?
            /// </summary>
            public static Field CBID = new Field< FIN_CashBankJournal >("CBID");
		    /// <summary>
            /// 帐号编码 - 字段名：CBNo - 数据类型：String
            /// </summary>
            public static Field CBNo = new Field< FIN_CashBankJournal >("CBNo");
		    /// <summary>
            /// 所属公司ID - 字段名：GCompanyID - 数据类型：Guid?
            /// </summary>
            public static Field GCompanyID = new Field< FIN_CashBankJournal >("GCompanyID");
		    /// <summary>
            /// 业务日期 - 字段名：BusinessDate - 数据类型：DateTime?
            /// </summary>
            public static Field BusinessDate = new Field< FIN_CashBankJournal >("BusinessDate");
		    /// <summary>
            /// 公司ID - 字段名：CompanyID - 数据类型：Int32?
            /// </summary>
            public static Field CompanyID = new Field< FIN_CashBankJournal >("CompanyID");
		    /// <summary>
            /// 公司名称 - 字段名：CompanyName - 数据类型：String
            /// </summary>
            public static Field CompanyName = new Field< FIN_CashBankJournal >("CompanyName");
		    /// <summary>
            /// 单据类型 - 字段名：BillType - 数据类型：String
            /// </summary>
            public static Field BillType = new Field< FIN_CashBankJournal >("BillType");
		    /// <summary>
            /// 内部单据ID - 字段名：SourceBillID - 数据类型：Int32?
            /// </summary>
            public static Field SourceBillID = new Field< FIN_CashBankJournal >("SourceBillID");
		    /// <summary>
            /// 源单据编号 - 字段名：SourceBillNo - 数据类型：String
            /// </summary>
            public static Field SourceBillNo = new Field< FIN_CashBankJournal >("SourceBillNo");
		    /// <summary>
            /// 原币收入 - 字段名：InCome - 数据类型：Decimal?
            /// </summary>
            public static Field InCome = new Field< FIN_CashBankJournal >("InCome");
		    /// <summary>
            /// 原币支出 - 字段名：Expenditure - 数据类型：Decimal?
            /// </summary>
            public static Field Expenditure = new Field< FIN_CashBankJournal >("Expenditure");
		    /// <summary>
            /// 汇率 - 字段名：ExchangeRate - 数据类型：Decimal?
            /// </summary>
            public static Field ExchangeRate = new Field< FIN_CashBankJournal >("ExchangeRate");
		    /// <summary>
            /// 税率 - 字段名：TaxRate - 数据类型：Decimal?
            /// </summary>
            public static Field TaxRate = new Field< FIN_CashBankJournal >("TaxRate");
		    /// <summary>
            /// 本币金额 - 字段名：SCAmount - 数据类型：Decimal?
            /// </summary>
            public static Field SCAmount = new Field< FIN_CashBankJournal >("SCAmount");
		    /// <summary>
            /// 经手人ID - 字段名：OperatorID - 数据类型：Int32?
            /// </summary>
            public static Field OperatorID = new Field< FIN_CashBankJournal >("OperatorID");
		    /// <summary>
            /// 经手人 - 字段名：OperatorName - 数据类型：String
            /// </summary>
            public static Field OperatorName = new Field< FIN_CashBankJournal >("OperatorName");
		    /// <summary>
            ///  - 字段名：CreatedTime - 数据类型：DateTime?
            /// </summary>
            public static Field CreatedTime = new Field< FIN_CashBankJournal >("CreatedTime");
		    /// <summary>
            /// 摘要 - 字段名：Abstract - 数据类型：String
            /// </summary>
            public static Field Abstract = new Field< FIN_CashBankJournal >("Abstract");
		    /// <summary>
            /// 机构Id - 字段名：OrgID - 数据类型：Int32?
            /// </summary>
            public static Field OrgID = new Field< FIN_CashBankJournal >("OrgID");
		    /// <summary>
            /// 机构名称 - 字段名：OrgName - 数据类型：String
            /// </summary>
            public static Field OrgName = new Field< FIN_CashBankJournal >("OrgName");
		    /// <summary>
            /// 部门ID - 字段名：DeptID - 数据类型：Int32?
            /// </summary>
            public static Field DeptID = new Field< FIN_CashBankJournal >("DeptID");
		    /// <summary>
            /// 部门 - 字段名：DeptName - 数据类型：String
            /// </summary>
            public static Field DeptName = new Field< FIN_CashBankJournal >("DeptName");
		    /// <summary>
            /// 对帐 - 字段名：IsCheck - 数据类型：Boolean?
            /// </summary>
            public static Field IsCheck = new Field< FIN_CashBankJournal >("IsCheck");
		    /// <summary>
            /// 对帐人 - 字段名：CheckEmpName - 数据类型：String
            /// </summary>
            public static Field CheckEmpName = new Field< FIN_CashBankJournal >("CheckEmpName");
		    /// <summary>
            /// 对帐日期 - 字段名：CheckDate - 数据类型：DateTime?
            /// </summary>
            public static Field CheckDate = new Field< FIN_CashBankJournal >("CheckDate");
		}
	}
}
