//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by CodeSmith Template.
//
//     Creater: David
//     Date:    2014/11/7
//     Time:    17:53
//     Version: 4.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

/// <summary>
/// CodeSmith自动生成的实体
/// </summary>
namespace ZNLCRM.Entity.DBModel
{	
	using System;
	using MySoft.Data;
	using ZNLCRM.Utility;
    using ZNLFrame.Entity;
    /// <summary>
    /// 表名：FIN_SubmitExpense 主键列：ExpID
    /// </summary>
    [SerializableAttribute()]
	public partial class FIN_SubmitExpense : BaseEntity
	{
		#region Private Properties
		
		private Int32 _ExpID;
		private Guid? _ExpGuID;
		private Guid? _GCompanyGuID;
		private Int32? _OrgID;
		private String _BillNo;
		private String _SourceBillNo;
		private Guid? _SourceGuid;
		private String _ExpName;
		private Int32? _OpEmpID;
		private String _OpEmpName;
		private DateTime? _OpDate;
		private Decimal? _Amount;
		private Decimal? _ChkAmount;
		private String _Remark;
		private String _ApproveStatus;
		private String _Status;
		private DateTime? _CreatedTime;
		private Int32? _CreatedEmpID;
		private String _CreatedEmpName;
		private DateTime? _UpdatedTime;
		private Int32? _UpdatedEmpID;
		private String _UpdatedEmpName;
		private Boolean? _IsDeleted;
		
		#endregion
		
		#region Public Properties
		
		/// <summary>
		/// .
		/// </summary>
		public Int32 ExpID
		{
			get 
			{
				return _ExpID;
			}
			set 
			{
				this.OnPropertyValueChange(_.ExpID, _ExpID , value);
				this._ExpID = value;
			}
		}
		
		/// <summary>
		/// .
		/// </summary>
		public Guid? ExpGuID
		{
			get 
			{
				return this._ExpGuID;
			}
			set 
			{
				this.OnPropertyValueChange(_.ExpGuID, _ExpGuID , value);
				this._ExpGuID = value;
			}
		}

		/// <summary>
		/// 注册客户Guid.
		/// </summary>
		public Guid? GCompanyGuID
		{
			get 
			{
				return this._GCompanyGuID;
			}
			set 
			{
				this.OnPropertyValueChange(_.GCompanyGuID, _GCompanyGuID , value);
				this._GCompanyGuID = value;
			}
		}

		/// <summary>
		/// .
		/// </summary>
		public Int32? OrgID
		{
			get 
			{
				return this._OrgID;
			}
			set 
			{
				this.OnPropertyValueChange(_.OrgID, _OrgID , value);
				this._OrgID = value;
			}
		}

		/// <summary>
		/// 单号.
		/// </summary>
		public String BillNo
		{
			get 
			{
				return this._BillNo;
			}
			set 
			{
				this.OnPropertyValueChange(_.BillNo, _BillNo , value);
				this._BillNo = value.SubStr(30);
			}
		}

		/// <summary>
		/// 关联单号.
		/// </summary>
		public String SourceBillNo
		{
			get 
			{
				return this._SourceBillNo;
			}
			set 
			{
				this.OnPropertyValueChange(_.SourceBillNo, _SourceBillNo , value);
				this._SourceBillNo = value.SubStr(30);
			}
		}

		/// <summary>
		/// 关联GUID.
		/// </summary>
		public Guid? SourceGuid
		{
			get 
			{
				return this._SourceGuid;
			}
			set 
			{
				this.OnPropertyValueChange(_.SourceGuid, _SourceGuid , value);
				this._SourceGuid = value;
			}
		}

		/// <summary>
		/// 报销标题.
		/// </summary>
		public String ExpName
		{
			get 
			{
				return this._ExpName;
			}
			set 
			{
				this.OnPropertyValueChange(_.ExpName, _ExpName , value);
				this._ExpName = value.SubStr(200);
			}
		}

		/// <summary>
		/// 所属人员ID.
		/// </summary>
		public Int32? OpEmpID
		{
			get 
			{
				return this._OpEmpID;
			}
			set 
			{
				this.OnPropertyValueChange(_.OpEmpID, _OpEmpID , value);
				this._OpEmpID = value;
			}
		}

		/// <summary>
		/// 处理原因.
		/// </summary>
		public String OpEmpName
		{
			get 
			{
				return this._OpEmpName;
			}
			set 
			{
				this.OnPropertyValueChange(_.OpEmpName, _OpEmpName , value);
				this._OpEmpName = value.SubStr(50);
			}
		}

		/// <summary>
		/// .
		/// </summary>
		public DateTime? OpDate
		{
			get 
			{
				return this._OpDate;
			}
			set 
			{
				this.OnPropertyValueChange(_.OpDate, _OpDate , value);
				this._OpDate = value;
			}
		}

		/// <summary>
		/// 报销金额.
		/// </summary>
		public Decimal? Amount
		{
			get 
			{
				return this._Amount;
			}
			set 
			{
				this.OnPropertyValueChange(_.Amount, _Amount , value);
				this._Amount = value;
			}
		}

		/// <summary>
		/// 已受理金额.
		/// </summary>
		public Decimal? ChkAmount
		{
			get 
			{
				return this._ChkAmount;
			}
			set 
			{
				this.OnPropertyValueChange(_.ChkAmount, _ChkAmount , value);
				this._ChkAmount = value;
			}
		}

		/// <summary>
		/// 报销备注.
		/// </summary>
		public String Remark
		{
			get 
			{
				return this._Remark;
			}
			set 
			{
				this.OnPropertyValueChange(_.Remark, _Remark , value);
				this._Remark = value.SubStr(500);
			}
		}

		/// <summary>
		/// 审核状态.
		/// </summary>
		public String ApproveStatus
		{
			get 
			{
				return this._ApproveStatus;
			}
			set 
			{
				this.OnPropertyValueChange(_.ApproveStatus, _ApproveStatus , value);
				this._ApproveStatus = value.SubStr(50);
			}
		}

		/// <summary>
		/// 状态.
		/// </summary>
		public String Status
		{
			get 
			{
				return this._Status;
			}
			set 
			{
				this.OnPropertyValueChange(_.Status, _Status , value);
				this._Status = value.SubStr(50);
			}
		}

		/// <summary>
		/// .
		/// </summary>
		public DateTime? CreatedTime
		{
			get 
			{
				return this._CreatedTime;
			}
			set 
			{
				this.OnPropertyValueChange(_.CreatedTime, _CreatedTime , value);
				this._CreatedTime = value;
			}
		}

		/// <summary>
		/// .
		/// </summary>
		public Int32? CreatedEmpID
		{
			get 
			{
				return this._CreatedEmpID;
			}
			set 
			{
				this.OnPropertyValueChange(_.CreatedEmpID, _CreatedEmpID , value);
				this._CreatedEmpID = value;
			}
		}

		/// <summary>
		/// .
		/// </summary>
		public String CreatedEmpName
		{
			get 
			{
				return this._CreatedEmpName;
			}
			set 
			{
				this.OnPropertyValueChange(_.CreatedEmpName, _CreatedEmpName , value);
				this._CreatedEmpName = value.SubStr(50);
			}
		}

		/// <summary>
		/// .
		/// </summary>
		public DateTime? UpdatedTime
		{
			get 
			{
				return this._UpdatedTime;
			}
			set 
			{
				this.OnPropertyValueChange(_.UpdatedTime, _UpdatedTime , value);
				this._UpdatedTime = value;
			}
		}

		/// <summary>
		/// .
		/// </summary>
		public Int32? UpdatedEmpID
		{
			get 
			{
				return this._UpdatedEmpID;
			}
			set 
			{
				this.OnPropertyValueChange(_.UpdatedEmpID, _UpdatedEmpID , value);
				this._UpdatedEmpID = value;
			}
		}

		/// <summary>
		/// .
		/// </summary>
		public String UpdatedEmpName
		{
			get 
			{
				return this._UpdatedEmpName;
			}
			set 
			{
				this.OnPropertyValueChange(_.UpdatedEmpName, _UpdatedEmpName , value);
				this._UpdatedEmpName = value.SubStr(50);
			}
		}

		/// <summary>
		/// 是否删除(0:正常,1:已删除).
		/// </summary>
		public Boolean? IsDeleted
		{
			get 
			{
				return this._IsDeleted;
			}
			set 
			{
				this.OnPropertyValueChange(_.IsDeleted, _IsDeleted , value);
				this._IsDeleted = value;
			}
		}
		
		#endregion
	    /// <summary>
        /// 获取实体对应的表名
        /// </summary>
        protected override Table GetTable() {
            return new Table< FIN_SubmitExpense >("FIN_SubmitExpense");
        }
		
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        protected override Field GetIdentityField() {
            return _.ExpID;
        }  			
		
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        protected override Field[] GetPrimaryKeyFields() {
            return new Field[] {
				_.ExpID
			};
        }
			
	    /// <summary>
        /// 获取列信息
        /// </summary>
        protected override Field[] GetFields() {
            return new Field[] {
				_.ExpID,		
				_.ExpGuID,		
				_.GCompanyGuID,		
				_.OrgID,		
				_.BillNo,		
				_.SourceBillNo,		
				_.SourceGuid,		
				_.ExpName,		
				_.OpEmpID,		
				_.OpEmpName,		
				_.OpDate,		
				_.Amount,		
				_.ChkAmount,		
				_.Remark,		
				_.ApproveStatus,		
				_.Status,		
				_.CreatedTime,		
				_.CreatedEmpID,		
				_.CreatedEmpName,		
				_.UpdatedTime,		
				_.UpdatedEmpID,		
				_.UpdatedEmpName,		
				_.IsDeleted		
			};
		}
		
	    /// <summary>
        /// 获取列数据
        /// </summary>
        protected override object[] GetValues() {
            return new object[] {
				this._ExpID,		
				this._ExpGuID,		
				this._GCompanyGuID,		
				this._OrgID,		
				this._BillNo,		
				this._SourceBillNo,		
				this._SourceGuid,		
				this._ExpName,		
				this._OpEmpID,		
				this._OpEmpName,		
				this._OpDate,		
				this._Amount,		
				this._ChkAmount,		
				this._Remark,		
				this._ApproveStatus,		
				this._Status,		
				this._CreatedTime,		
				this._CreatedEmpID,		
				this._CreatedEmpName,		
				this._UpdatedTime,		
				this._UpdatedEmpID,		
				this._UpdatedEmpName,		
				this._IsDeleted		
			};
		}
		
	    /// <summary>
        /// 给当前实体赋值
        /// </summary>
        protected override void SetValues(IRowReader reader) {
            if ((false == reader.IsDBNull(_.ExpID))) {
                this._ExpID = reader.GetInt32(_.ExpID);
            }
            if ((false == reader.IsDBNull(_.ExpGuID))) {
                this._ExpGuID = reader.GetGuid(_.ExpGuID);
            }
            if ((false == reader.IsDBNull(_.GCompanyGuID))) {
                this._GCompanyGuID = reader.GetGuid(_.GCompanyGuID);
            }
            if ((false == reader.IsDBNull(_.OrgID))) {
                this._OrgID = reader.GetInt32(_.OrgID);
            }
            if ((false == reader.IsDBNull(_.BillNo))) {
                this._BillNo = reader.GetString(_.BillNo);
            }
            if ((false == reader.IsDBNull(_.SourceBillNo))) {
                this._SourceBillNo = reader.GetString(_.SourceBillNo);
            }
            if ((false == reader.IsDBNull(_.SourceGuid))) {
                this._SourceGuid = reader.GetGuid(_.SourceGuid);
            }
            if ((false == reader.IsDBNull(_.ExpName))) {
                this._ExpName = reader.GetString(_.ExpName);
            }
            if ((false == reader.IsDBNull(_.OpEmpID))) {
                this._OpEmpID = reader.GetInt32(_.OpEmpID);
            }
            if ((false == reader.IsDBNull(_.OpEmpName))) {
                this._OpEmpName = reader.GetString(_.OpEmpName);
            }
            if ((false == reader.IsDBNull(_.OpDate))) {
                this._OpDate = reader.GetDateTime(_.OpDate);
            }
            if ((false == reader.IsDBNull(_.Amount))) {
                this._Amount = reader.GetDecimal(_.Amount);
            }
            if ((false == reader.IsDBNull(_.ChkAmount))) {
                this._ChkAmount = reader.GetDecimal(_.ChkAmount);
            }
            if ((false == reader.IsDBNull(_.Remark))) {
                this._Remark = reader.GetString(_.Remark);
            }
            if ((false == reader.IsDBNull(_.ApproveStatus))) {
                this._ApproveStatus = reader.GetString(_.ApproveStatus);
            }
            if ((false == reader.IsDBNull(_.Status))) {
                this._Status = reader.GetString(_.Status);
            }
            if ((false == reader.IsDBNull(_.CreatedTime))) {
                this._CreatedTime = reader.GetDateTime(_.CreatedTime);
            }
            if ((false == reader.IsDBNull(_.CreatedEmpID))) {
                this._CreatedEmpID = reader.GetInt32(_.CreatedEmpID);
            }
            if ((false == reader.IsDBNull(_.CreatedEmpName))) {
                this._CreatedEmpName = reader.GetString(_.CreatedEmpName);
            }
            if ((false == reader.IsDBNull(_.UpdatedTime))) {
                this._UpdatedTime = reader.GetDateTime(_.UpdatedTime);
            }
            if ((false == reader.IsDBNull(_.UpdatedEmpID))) {
                this._UpdatedEmpID = reader.GetInt32(_.UpdatedEmpID);
            }
            if ((false == reader.IsDBNull(_.UpdatedEmpName))) {
                this._UpdatedEmpName = reader.GetString(_.UpdatedEmpName);
            }
            if ((false == reader.IsDBNull(_.IsDeleted))) {
                this._IsDeleted = reader.GetBoolean(_.IsDeleted);
            }
		}
		
	    public override int GetHashCode() {
            return base.GetHashCode();
        }
        
        public override bool Equals(object obj) {
            if ((obj == null)) {
                return false;
            }
            if ((false == typeof(FIN_SubmitExpense).IsAssignableFrom(obj.GetType()))) {
                return false;
            }
            if ((((object)(this)) == ((object)(obj)))) {
                return true;
            }
            return false;
        }
		
        public class _ {
                
            /// <summary>
            /// 表示选择所有列，与*等同
            /// </summary>
            public static AllField All = new AllField< FIN_SubmitExpense >();
			
		    /// <summary>
            ///  - 字段名：ExpID - 数据类型：Int32?
            /// </summary>
            public static Field ExpID = new Field< FIN_SubmitExpense >("ExpID");
		    /// <summary>
            ///  - 字段名：ExpGuID - 数据类型：Guid?
            /// </summary>
            public static Field ExpGuID = new Field< FIN_SubmitExpense >("ExpGuID");
		    /// <summary>
            /// 注册客户Guid - 字段名：GCompanyGuID - 数据类型：Guid?
            /// </summary>
            public static Field GCompanyGuID = new Field< FIN_SubmitExpense >("GCompanyGuID");
		    /// <summary>
            ///  - 字段名：OrgID - 数据类型：Int32?
            /// </summary>
            public static Field OrgID = new Field< FIN_SubmitExpense >("OrgID");
		    /// <summary>
            /// 单号 - 字段名：BillNo - 数据类型：String
            /// </summary>
            public static Field BillNo = new Field< FIN_SubmitExpense >("BillNo");
		    /// <summary>
            /// 关联单号 - 字段名：SourceBillNo - 数据类型：String
            /// </summary>
            public static Field SourceBillNo = new Field< FIN_SubmitExpense >("SourceBillNo");
		    /// <summary>
            /// 关联GUID - 字段名：SourceGuid - 数据类型：Guid?
            /// </summary>
            public static Field SourceGuid = new Field< FIN_SubmitExpense >("SourceGuid");
		    /// <summary>
            /// 报销标题 - 字段名：ExpName - 数据类型：String
            /// </summary>
            public static Field ExpName = new Field< FIN_SubmitExpense >("ExpName");
		    /// <summary>
            /// 所属人员ID - 字段名：OpEmpID - 数据类型：Int32?
            /// </summary>
            public static Field OpEmpID = new Field< FIN_SubmitExpense >("OpEmpID");
		    /// <summary>
            /// 处理原因 - 字段名：OpEmpName - 数据类型：String
            /// </summary>
            public static Field OpEmpName = new Field< FIN_SubmitExpense >("OpEmpName");
		    /// <summary>
            ///  - 字段名：OpDate - 数据类型：DateTime?
            /// </summary>
            public static Field OpDate = new Field< FIN_SubmitExpense >("OpDate");
		    /// <summary>
            /// 报销金额 - 字段名：Amount - 数据类型：Decimal?
            /// </summary>
            public static Field Amount = new Field< FIN_SubmitExpense >("Amount");
		    /// <summary>
            /// 已受理金额 - 字段名：ChkAmount - 数据类型：Decimal?
            /// </summary>
            public static Field ChkAmount = new Field< FIN_SubmitExpense >("ChkAmount");
		    /// <summary>
            /// 报销备注 - 字段名：Remark - 数据类型：String
            /// </summary>
            public static Field Remark = new Field< FIN_SubmitExpense >("Remark");
		    /// <summary>
            /// 审核状态 - 字段名：ApproveStatus - 数据类型：String
            /// </summary>
            public static Field ApproveStatus = new Field< FIN_SubmitExpense >("ApproveStatus");
		    /// <summary>
            /// 状态 - 字段名：Status - 数据类型：String
            /// </summary>
            public static Field Status = new Field< FIN_SubmitExpense >("Status");
		    /// <summary>
            ///  - 字段名：CreatedTime - 数据类型：DateTime?
            /// </summary>
            public static Field CreatedTime = new Field< FIN_SubmitExpense >("CreatedTime");
		    /// <summary>
            ///  - 字段名：CreatedEmpID - 数据类型：Int32?
            /// </summary>
            public static Field CreatedEmpID = new Field< FIN_SubmitExpense >("CreatedEmpID");
		    /// <summary>
            ///  - 字段名：CreatedEmpName - 数据类型：String
            /// </summary>
            public static Field CreatedEmpName = new Field< FIN_SubmitExpense >("CreatedEmpName");
		    /// <summary>
            ///  - 字段名：UpdatedTime - 数据类型：DateTime?
            /// </summary>
            public static Field UpdatedTime = new Field< FIN_SubmitExpense >("UpdatedTime");
		    /// <summary>
            ///  - 字段名：UpdatedEmpID - 数据类型：Int32?
            /// </summary>
            public static Field UpdatedEmpID = new Field< FIN_SubmitExpense >("UpdatedEmpID");
		    /// <summary>
            ///  - 字段名：UpdatedEmpName - 数据类型：String
            /// </summary>
            public static Field UpdatedEmpName = new Field< FIN_SubmitExpense >("UpdatedEmpName");
		    /// <summary>
            /// 是否删除(0:正常,1:已删除) - 字段名：IsDeleted - 数据类型：Boolean?
            /// </summary>
            public static Field IsDeleted = new Field< FIN_SubmitExpense >("IsDeleted");
		}
	}
}
