//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by CodeSmith Template.
//
//     Creater: Administrator
//     Date:    2015/1/16
//     Time:    19:17
//     Version: 4.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

/// <summary>
/// CodeSmith自动生成的实体
/// </summary>
namespace ZNLCRM.Entity.DBModel
{
    using System;
    using MySoft.Data;
    using ZNLCRM.Utility;
    using ZNLFrame.Entity;
    /// <summary>
    /// 表名：Sys_EmpDataRight 主键列：SysEmpRoleID
    /// </summary>
    [SerializableAttribute()]
    public partial class Sys_EmpDataRight : BaseEntity
    {
        #region Private Properties

        private Int32 _SysEmpRoleID;
        private Guid? _GCompanyID;
        private Int32? _EmpID;
        private String _RoleIDs;
        private String _RoleNames;
        private String _ReadOrgIDs;
        private String _EditOrgIDs;
        private String _ReadDeptIDs;
        private String _EditDeptIDs;
        private String _ReadEmpIDs;
        private String _EditEmpIDs;
        private Boolean? _IsDeleted;

        #endregion

        #region Public Properties

        /// <summary>
        /// .
        /// </summary>
        public Int32 SysEmpRoleID
        {
            get
            {
                return _SysEmpRoleID;
            }
            set
            {
                this.OnPropertyValueChange(_.SysEmpRoleID, _SysEmpRoleID, value);
                this._SysEmpRoleID = value;
            }
        }

        /// <summary>
        /// 为空表示最基础数据.
        /// </summary>
        public Guid? GCompanyID
        {
            get
            {
                return this._GCompanyID;
            }
            set
            {
                this.OnPropertyValueChange(_.GCompanyID, _GCompanyID, value);
                this._GCompanyID = value;
            }
        }

        /// <summary>
        /// .
        /// </summary>
        public Int32? EmpID
        {
            get
            {
                return this._EmpID;
            }
            set
            {
                this.OnPropertyValueChange(_.EmpID, _EmpID, value);
                this._EmpID = value;
            }
        }

        /// <summary>
        /// .
        /// </summary>
        public String RoleIDs
        {
            get
            {
                return this._RoleIDs;
            }
            set
            {
                this.OnPropertyValueChange(_.RoleIDs, _RoleIDs, value);
                this._RoleIDs = value.SubStr(1000);
            }
        }

        /// <summary>
        /// .
        /// </summary>
        public String RoleNames
        {
            get
            {
                return this._RoleNames;
            }
            set
            {
                this.OnPropertyValueChange(_.RoleNames, _RoleNames, value);
                this._RoleNames = value.SubStr(3000);
            }
        }

        /// <summary>
        /// .
        /// </summary>
        public String ReadOrgIDs
        {
            get
            {
                return this._ReadOrgIDs;
            }
            set
            {
                this.OnPropertyValueChange(_.ReadOrgIDs, _ReadOrgIDs, value);
                this._ReadOrgIDs = value.SubStr(3000);
            }
        }

        /// <summary>
        /// .
        /// </summary>
        public String EditOrgIDs
        {
            get
            {
                return this._EditOrgIDs;
            }
            set
            {
                this.OnPropertyValueChange(_.EditOrgIDs, _EditOrgIDs, value);
                this._EditOrgIDs = value.SubStr(3000);
            }
        }

        /// <summary>
        /// 可查哪些部门的数据.
        /// </summary>
        public String ReadDeptIDs
        {
            get
            {
                return this._ReadDeptIDs;
            }
            set
            {
                this.OnPropertyValueChange(_.ReadDeptIDs, _ReadDeptIDs, value);
                this._ReadDeptIDs = value.SubStr(3000);
            }
        }

        /// <summary>
        /// 可编辑哪些部门的数据.
        /// </summary>
        public String EditDeptIDs
        {
            get
            {
                return this._EditDeptIDs;
            }
            set
            {
                this.OnPropertyValueChange(_.EditDeptIDs, _EditDeptIDs, value);
                this._EditDeptIDs = value.SubStr(3000);
            }
        }

        /// <summary>
        /// 可读哪些员工的数据.
        /// </summary>
        public String ReadEmpIDs
        {
            get
            {
                return this._ReadEmpIDs;
            }
            set
            {
                this.OnPropertyValueChange(_.ReadEmpIDs, _ReadEmpIDs, value);
                this._ReadEmpIDs = value.SubStr(3000);
            }
        }

        /// <summary>
        /// 可编辑哪些员工的数据.
        /// </summary>
        public String EditEmpIDs
        {
            get
            {
                return this._EditEmpIDs;
            }
            set
            {
                this.OnPropertyValueChange(_.EditEmpIDs, _EditEmpIDs, value);
                this._EditEmpIDs = value.SubStr(3000);
            }
        }

        /// <summary>
        /// 删除标识.
        /// </summary>
        public Boolean? IsDeleted
        {
            get
            {
                return this._IsDeleted;
            }
            set
            {
                this.OnPropertyValueChange(_.IsDeleted, _IsDeleted, value);
                this._IsDeleted = value;
            }
        }

        #endregion
        /// <summary>
        /// 获取实体对应的表名
        /// </summary>
        protected override Table GetTable()
        {
            return new Table<Sys_EmpDataRight>("Sys_EmpDataRight");
        }

        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        protected override Field GetIdentityField()
        {
            return _.SysEmpRoleID;
        }

        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        protected override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.SysEmpRoleID
			};
        }

        /// <summary>
        /// 获取列信息
        /// </summary>
        protected override Field[] GetFields()
        {
            return new Field[] {
				_.SysEmpRoleID,		
				_.GCompanyID,		
				_.EmpID,		
				_.RoleIDs,		
				_.RoleNames,		
				_.ReadOrgIDs,		
				_.EditOrgIDs,		
				_.ReadDeptIDs,		
				_.EditDeptIDs,		
				_.ReadEmpIDs,		
				_.EditEmpIDs,		
				_.IsDeleted		
			};
        }

        /// <summary>
        /// 获取列数据
        /// </summary>
        protected override object[] GetValues()
        {
            return new object[] {
				this._SysEmpRoleID,		
				this._GCompanyID,		
				this._EmpID,		
				this._RoleIDs,		
				this._RoleNames,		
				this._ReadOrgIDs,		
				this._EditOrgIDs,		
				this._ReadDeptIDs,		
				this._EditDeptIDs,		
				this._ReadEmpIDs,		
				this._EditEmpIDs,		
				this._IsDeleted		
			};
        }

        /// <summary>
        /// 给当前实体赋值
        /// </summary>
        protected override void SetValues(IRowReader reader)
        {
            if ((false == reader.IsDBNull(_.SysEmpRoleID)))
            {
                this._SysEmpRoleID = reader.GetInt32(_.SysEmpRoleID);
            }
            if ((false == reader.IsDBNull(_.GCompanyID)))
            {
                this._GCompanyID = reader.GetGuid(_.GCompanyID);
            }
            if ((false == reader.IsDBNull(_.EmpID)))
            {
                this._EmpID = reader.GetInt32(_.EmpID);
            }
            if ((false == reader.IsDBNull(_.RoleIDs)))
            {
                this._RoleIDs = reader.GetString(_.RoleIDs);
            }
            if ((false == reader.IsDBNull(_.RoleNames)))
            {
                this._RoleNames = reader.GetString(_.RoleNames);
            }
            if ((false == reader.IsDBNull(_.ReadOrgIDs)))
            {
                this._ReadOrgIDs = reader.GetString(_.ReadOrgIDs);
            }
            if ((false == reader.IsDBNull(_.EditOrgIDs)))
            {
                this._EditOrgIDs = reader.GetString(_.EditOrgIDs);
            }
            if ((false == reader.IsDBNull(_.ReadDeptIDs)))
            {
                this._ReadDeptIDs = reader.GetString(_.ReadDeptIDs);
            }
            if ((false == reader.IsDBNull(_.EditDeptIDs)))
            {
                this._EditDeptIDs = reader.GetString(_.EditDeptIDs);
            }
            if ((false == reader.IsDBNull(_.ReadEmpIDs)))
            {
                this._ReadEmpIDs = reader.GetString(_.ReadEmpIDs);
            }
            if ((false == reader.IsDBNull(_.EditEmpIDs)))
            {
                this._EditEmpIDs = reader.GetString(_.EditEmpIDs);
            }
            if ((false == reader.IsDBNull(_.IsDeleted)))
            {
                this._IsDeleted = reader.GetBoolean(_.IsDeleted);
            }
        }

        public override int GetHashCode()
        {
            return base.GetHashCode();
        }

        public override bool Equals(object obj)
        {
            if ((obj == null))
            {
                return false;
            }
            if ((false == typeof(Sys_EmpDataRight).IsAssignableFrom(obj.GetType())))
            {
                return false;
            }
            if ((((object)(this)) == ((object)(obj))))
            {
                return true;
            }
            return false;
        }

        public class _
        {

            /// <summary>
            /// 表示选择所有列，与*等同
            /// </summary>
            public static AllField All = new AllField<Sys_EmpDataRight>();

            /// <summary>
            ///  - 字段名：SysEmpRoleID - 数据类型：Int32?
            /// </summary>
            public static Field SysEmpRoleID = new Field<Sys_EmpDataRight>("SysEmpRoleID");
            /// <summary>
            /// 为空表示最基础数据 - 字段名：GCompanyID - 数据类型：Guid?
            /// </summary>
            public static Field GCompanyID = new Field<Sys_EmpDataRight>("GCompanyID");
            /// <summary>
            ///  - 字段名：EmpID - 数据类型：Int32?
            /// </summary>
            public static Field EmpID = new Field<Sys_EmpDataRight>("EmpID");
            /// <summary>
            ///  - 字段名：RoleIDs - 数据类型：String
            /// </summary>
            public static Field RoleIDs = new Field<Sys_EmpDataRight>("RoleIDs");
            /// <summary>
            ///  - 字段名：RoleNames - 数据类型：String
            /// </summary>
            public static Field RoleNames = new Field<Sys_EmpDataRight>("RoleNames");
            /// <summary>
            ///  - 字段名：ReadOrgIDs - 数据类型：String
            /// </summary>
            public static Field ReadOrgIDs = new Field<Sys_EmpDataRight>("ReadOrgIDs");
            /// <summary>
            ///  - 字段名：EditOrgIDs - 数据类型：String
            /// </summary>
            public static Field EditOrgIDs = new Field<Sys_EmpDataRight>("EditOrgIDs");
            /// <summary>
            /// 可查哪些部门的数据 - 字段名：ReadDeptIDs - 数据类型：String
            /// </summary>
            public static Field ReadDeptIDs = new Field<Sys_EmpDataRight>("ReadDeptIDs");
            /// <summary>
            /// 可编辑哪些部门的数据 - 字段名：EditDeptIDs - 数据类型：String
            /// </summary>
            public static Field EditDeptIDs = new Field<Sys_EmpDataRight>("EditDeptIDs");
            /// <summary>
            /// 可读哪些员工的数据 - 字段名：ReadEmpIDs - 数据类型：String
            /// </summary>
            public static Field ReadEmpIDs = new Field<Sys_EmpDataRight>("ReadEmpIDs");
            /// <summary>
            /// 可编辑哪些员工的数据 - 字段名：EditEmpIDs - 数据类型：String
            /// </summary>
            public static Field EditEmpIDs = new Field<Sys_EmpDataRight>("EditEmpIDs");
            /// <summary>
            /// 删除标识 - 字段名：IsDeleted - 数据类型：Boolean?
            /// </summary>
            public static Field IsDeleted = new Field<Sys_EmpDataRight>("IsDeleted");
        }
    }
}
