//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by CodeSmith Template.
//
//     Creater: David
//     Date:    2014/12/11
//     Time:    18:06
//     Version: 4.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

/// <summary>
/// CodeSmith自动生成的实体
/// </summary>
namespace ZNLCRM.Entity.DBModel
{
    using System;
    using MySoft.Data;
    using ZNLCRM.Utility;
    using ZNLFrame.Entity;
    /// <summary>
    /// 表名：SYS_Currency 主键列：RateTaxID
    /// </summary>
    [SerializableAttribute()]
    public partial class SYS_Currency : BaseEntity
    {
        #region Private Properties

        private Int32 _RateTaxID;
        private Guid? _RateTaxGuid;
        private Guid? _GCompanyID;
        private String _CurrencyCode;
        private Decimal? _ExchangeRate;
        private DateTime? _RateDate;
        private String _Remark;
        private Int32? _CreatedEmpID;
        private String _CreatedEmpName;
        private DateTime? _CreatedTime;
        private Int32? _UpdatedEmpID;
        private String _UpdatedEmpName;
        private DateTime? _UpdatedTime;
        private Boolean? _IsDeleted;

        #endregion

        #region Public Properties

        /// <summary>
        /// 自增ID.
        /// </summary>
        public Int32 RateTaxID
        {
            get
            {
                return _RateTaxID;
            }
            set
            {
                this.OnPropertyValueChange(_.RateTaxID, _RateTaxID, value);
                this._RateTaxID = value;
            }
        }

        /// <summary>
        /// Guid.
        /// </summary>
        public Guid? RateTaxGuid
        {
            get
            {
                return this._RateTaxGuid;
            }
            set
            {
                this.OnPropertyValueChange(_.RateTaxGuid, _RateTaxGuid, value);
                this._RateTaxGuid = value;
            }
        }

        /// <summary>
        /// 所属公司guid.
        /// </summary>
        public Guid? GCompanyID
        {
            get
            {
                return this._GCompanyID;
            }
            set
            {
                this.OnPropertyValueChange(_.GCompanyID, _GCompanyID, value);
                this._GCompanyID = value;
            }
        }

        /// <summary>
        /// 币种.
        /// </summary>
        public String CurrencyCode
        {
            get
            {
                return this._CurrencyCode;
            }
            set
            {
                this.OnPropertyValueChange(_.CurrencyCode, _CurrencyCode, value);
                this._CurrencyCode = value.SubStr(10);
            }
        }

        /// <summary>
        /// 汇率.
        /// </summary>
        public Decimal? ExchangeRate
        {
            get
            {
                return this._ExchangeRate;
            }
            set
            {
                this.OnPropertyValueChange(_.ExchangeRate, _ExchangeRate, value);
                this._ExchangeRate = value;
            }
        }

        /// <summary>
        /// 汇率日期.
        /// </summary>
        public DateTime? RateDate
        {
            get
            {
                return this._RateDate;
            }
            set
            {
                this.OnPropertyValueChange(_.RateDate, _RateDate, value);
                this._RateDate = value;
            }
        }

        /// <summary>
        /// 备注.
        /// </summary>
        public String Remark
        {
            get
            {
                return this._Remark;
            }
            set
            {
                this.OnPropertyValueChange(_.Remark, _Remark, value);
                this._Remark = value.SubStr(200);
            }
        }

        /// <summary>
        /// 录入人ID.
        /// </summary>
        public Int32? CreatedEmpID
        {
            get
            {
                return this._CreatedEmpID;
            }
            set
            {
                this.OnPropertyValueChange(_.CreatedEmpID, _CreatedEmpID, value);
                this._CreatedEmpID = value;
            }
        }

        /// <summary>
        /// 录入人.
        /// </summary>
        public String CreatedEmpName
        {
            get
            {
                return this._CreatedEmpName;
            }
            set
            {
                this.OnPropertyValueChange(_.CreatedEmpName, _CreatedEmpName, value);
                this._CreatedEmpName = value.SubStr(50);
            }
        }

        /// <summary>
        /// 录入时间.
        /// </summary>
        public DateTime? CreatedTime
        {
            get
            {
                return this._CreatedTime;
            }
            set
            {
                this.OnPropertyValueChange(_.CreatedTime, _CreatedTime, value);
                this._CreatedTime = value;
            }
        }

        /// <summary>
        /// 更新人ID.
        /// </summary>
        public Int32? UpdatedEmpID
        {
            get
            {
                return this._UpdatedEmpID;
            }
            set
            {
                this.OnPropertyValueChange(_.UpdatedEmpID, _UpdatedEmpID, value);
                this._UpdatedEmpID = value;
            }
        }

        /// <summary>
        /// 更新人.
        /// </summary>
        public String UpdatedEmpName
        {
            get
            {
                return this._UpdatedEmpName;
            }
            set
            {
                this.OnPropertyValueChange(_.UpdatedEmpName, _UpdatedEmpName, value);
                this._UpdatedEmpName = value.SubStr(50);
            }
        }

        /// <summary>
        /// 更新时间.
        /// </summary>
        public DateTime? UpdatedTime
        {
            get
            {
                return this._UpdatedTime;
            }
            set
            {
                this.OnPropertyValueChange(_.UpdatedTime, _UpdatedTime, value);
                this._UpdatedTime = value;
            }
        }

        /// <summary>
        /// .
        /// </summary>
        public Boolean? IsDeleted
        {
            get
            {
                return this._IsDeleted;
            }
            set
            {
                this.OnPropertyValueChange(_.IsDeleted, _IsDeleted, value);
                this._IsDeleted = value;
            }
        }

        #endregion
        /// <summary>
        /// 获取实体对应的表名
        /// </summary>
        protected override Table GetTable()
        {
            return new Table<SYS_Currency>("SYS_Currency");
        }

        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        protected override Field GetIdentityField()
        {
            return _.RateTaxID;
        }

        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        protected override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.RateTaxID
			};
        }

        /// <summary>
        /// 获取列信息
        /// </summary>
        protected override Field[] GetFields()
        {
            return new Field[] {
				_.RateTaxID,		
				_.RateTaxGuid,		
				_.GCompanyID,		
				_.CurrencyCode,		
				_.ExchangeRate,		
				_.RateDate,		
				_.Remark,		
				_.CreatedEmpID,		
				_.CreatedEmpName,		
				_.CreatedTime,		
				_.UpdatedEmpID,		
				_.UpdatedEmpName,		
				_.UpdatedTime,		
				_.IsDeleted		
			};
        }

        /// <summary>
        /// 获取列数据
        /// </summary>
        protected override object[] GetValues()
        {
            return new object[] {
				this._RateTaxID,		
				this._RateTaxGuid,		
				this._GCompanyID,		
				this._CurrencyCode,		
				this._ExchangeRate,		
				this._RateDate,		
				this._Remark,		
				this._CreatedEmpID,		
				this._CreatedEmpName,		
				this._CreatedTime,		
				this._UpdatedEmpID,		
				this._UpdatedEmpName,		
				this._UpdatedTime,		
				this._IsDeleted		
			};
        }

        /// <summary>
        /// 给当前实体赋值
        /// </summary>
        protected override void SetValues(IRowReader reader)
        {
            if ((false == reader.IsDBNull(_.RateTaxID)))
            {
                this._RateTaxID = reader.GetInt32(_.RateTaxID);
            }
            if ((false == reader.IsDBNull(_.RateTaxGuid)))
            {
                this._RateTaxGuid = reader.GetGuid(_.RateTaxGuid);
            }
            if ((false == reader.IsDBNull(_.GCompanyID)))
            {
                this._GCompanyID = reader.GetGuid(_.GCompanyID);
            }
            if ((false == reader.IsDBNull(_.CurrencyCode)))
            {
                this._CurrencyCode = reader.GetString(_.CurrencyCode);
            }
            if ((false == reader.IsDBNull(_.ExchangeRate)))
            {
                this._ExchangeRate = reader.GetDecimal(_.ExchangeRate);
            }
            if ((false == reader.IsDBNull(_.RateDate)))
            {
                this._RateDate = reader.GetDateTime(_.RateDate);
            }
            if ((false == reader.IsDBNull(_.Remark)))
            {
                this._Remark = reader.GetString(_.Remark);
            }
            if ((false == reader.IsDBNull(_.CreatedEmpID)))
            {
                this._CreatedEmpID = reader.GetInt32(_.CreatedEmpID);
            }
            if ((false == reader.IsDBNull(_.CreatedEmpName)))
            {
                this._CreatedEmpName = reader.GetString(_.CreatedEmpName);
            }
            if ((false == reader.IsDBNull(_.CreatedTime)))
            {
                this._CreatedTime = reader.GetDateTime(_.CreatedTime);
            }
            if ((false == reader.IsDBNull(_.UpdatedEmpID)))
            {
                this._UpdatedEmpID = reader.GetInt32(_.UpdatedEmpID);
            }
            if ((false == reader.IsDBNull(_.UpdatedEmpName)))
            {
                this._UpdatedEmpName = reader.GetString(_.UpdatedEmpName);
            }
            if ((false == reader.IsDBNull(_.UpdatedTime)))
            {
                this._UpdatedTime = reader.GetDateTime(_.UpdatedTime);
            }
            if ((false == reader.IsDBNull(_.IsDeleted)))
            {
                this._IsDeleted = reader.GetBoolean(_.IsDeleted);
            }
        }

        public override int GetHashCode()
        {
            return base.GetHashCode();
        }

        public override bool Equals(object obj)
        {
            if ((obj == null))
            {
                return false;
            }
            if ((false == typeof(SYS_Currency).IsAssignableFrom(obj.GetType())))
            {
                return false;
            }
            if ((((object)(this)) == ((object)(obj))))
            {
                return true;
            }
            return false;
        }

        public class _
        {

            /// <summary>
            /// 表示选择所有列，与*等同
            /// </summary>
            public static AllField All = new AllField<SYS_Currency>();

            /// <summary>
            /// 自增ID - 字段名：RateTaxID - 数据类型：Int32?
            /// </summary>
            public static Field RateTaxID = new Field<SYS_Currency>("RateTaxID");
            /// <summary>
            /// Guid - 字段名：RateTaxGuid - 数据类型：Guid?
            /// </summary>
            public static Field RateTaxGuid = new Field<SYS_Currency>("RateTaxGuid");
            /// <summary>
            /// 所属公司guid - 字段名：GCompanyID - 数据类型：Guid?
            /// </summary>
            public static Field GCompanyID = new Field<SYS_Currency>("GCompanyID");
            /// <summary>
            /// 币种 - 字段名：CurrencyCode - 数据类型：String
            /// </summary>
            public static Field CurrencyCode = new Field<SYS_Currency>("CurrencyCode");
            /// <summary>
            /// 汇率 - 字段名：ExchangeRate - 数据类型：Decimal?
            /// </summary>
            public static Field ExchangeRate = new Field<SYS_Currency>("ExchangeRate");
            /// <summary>
            /// 汇率日期 - 字段名：RateDate - 数据类型：DateTime?
            /// </summary>
            public static Field RateDate = new Field<SYS_Currency>("RateDate");
            /// <summary>
            /// 备注 - 字段名：Remark - 数据类型：String
            /// </summary>
            public static Field Remark = new Field<SYS_Currency>("Remark");
            /// <summary>
            /// 录入人ID - 字段名：CreatedEmpID - 数据类型：Int32?
            /// </summary>
            public static Field CreatedEmpID = new Field<SYS_Currency>("CreatedEmpID");
            /// <summary>
            /// 录入人 - 字段名：CreatedEmpName - 数据类型：String
            /// </summary>
            public static Field CreatedEmpName = new Field<SYS_Currency>("CreatedEmpName");
            /// <summary>
            /// 录入时间 - 字段名：CreatedTime - 数据类型：DateTime?
            /// </summary>
            public static Field CreatedTime = new Field<SYS_Currency>("CreatedTime");
            /// <summary>
            /// 更新人ID - 字段名：UpdatedEmpID - 数据类型：Int32?
            /// </summary>
            public static Field UpdatedEmpID = new Field<SYS_Currency>("UpdatedEmpID");
            /// <summary>
            /// 更新人 - 字段名：UpdatedEmpName - 数据类型：String
            /// </summary>
            public static Field UpdatedEmpName = new Field<SYS_Currency>("UpdatedEmpName");
            /// <summary>
            /// 更新时间 - 字段名：UpdatedTime - 数据类型：DateTime?
            /// </summary>
            public static Field UpdatedTime = new Field<SYS_Currency>("UpdatedTime");
            /// <summary>
            ///  - 字段名：IsDeleted - 数据类型：Boolean?
            /// </summary>
            public static Field IsDeleted = new Field<SYS_Currency>("IsDeleted");
        }
    }
}
