//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by CodeSmith Template.
//
//     Creater: Administrator
//     Date:    2015/1/6
//     Time:    10:07
//     Version: 4.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

/// <summary>
/// CodeSmith自动生成的实体
/// </summary>
namespace ZNLCRM.Entity.DBModel
{
    using System;
    using MySoft.Data;
    using ZNLCRM.Utility;
    using ZNLFrame.Entity;
    /// <summary>
    /// 表名：WF_AuditBill 主键列：WFAuditID
    /// </summary>
    [SerializableAttribute()]
    public partial class WF_AuditBill : BaseEntity
    {
        #region Private Properties

        private Int32 _WFAuditID;
        private Guid? _WFAuditGuid;
        private Guid? _GCompanyID;
        private String _TableName;
        private String _WFNamae;
        private Int32? _CreatedEmpID;
        private String _CreatedEmpName;
        private DateTime? _CreatedTime;
        private Int32? _UpdatedEmpID;
        private String _UpdatedEmpName;
        private DateTime? _UpdatedTime;
        private Boolean? _IsStop;
        private Boolean? _IsDeleted;

        #endregion

        #region Public Properties

        /// <summary>
        /// .
        /// </summary>
        public Int32 WFAuditID
        {
            get
            {
                return _WFAuditID;
            }
            set
            {
                this.OnPropertyValueChange(_.WFAuditID, _WFAuditID, value);
                this._WFAuditID = value;
            }
        }

        /// <summary>
        /// .
        /// </summary>
        public Guid? WFAuditGuid
        {
            get
            {
                return this._WFAuditGuid;
            }
            set
            {
                this.OnPropertyValueChange(_.WFAuditGuid, _WFAuditGuid, value);
                this._WFAuditGuid = value;
            }
        }

        /// <summary>
        /// .
        /// </summary>
        public Guid? GCompanyID
        {
            get
            {
                return this._GCompanyID;
            }
            set
            {
                this.OnPropertyValueChange(_.GCompanyID, _GCompanyID, value);
                this._GCompanyID = value;
            }
        }

        /// <summary>
        /// .
        /// </summary>
        public String TableName
        {
            get
            {
                return this._TableName;
            }
            set
            {
                this.OnPropertyValueChange(_.TableName, _TableName, value);
                this._TableName = value.SubStr(100);
            }
        }

        /// <summary>
        /// .
        /// </summary>
        public String WFNamae
        {
            get
            {
                return this._WFNamae;
            }
            set
            {
                this.OnPropertyValueChange(_.WFNamae, _WFNamae, value);
                this._WFNamae = value.SubStr(200);
            }
        }

        /// <summary>
        /// 创建人.
        /// </summary>
        public Int32? CreatedEmpID
        {
            get
            {
                return this._CreatedEmpID;
            }
            set
            {
                this.OnPropertyValueChange(_.CreatedEmpID, _CreatedEmpID, value);
                this._CreatedEmpID = value;
            }
        }

        /// <summary>
        /// 创建人姓名.
        /// </summary>
        public String CreatedEmpName
        {
            get
            {
                return this._CreatedEmpName;
            }
            set
            {
                this.OnPropertyValueChange(_.CreatedEmpName, _CreatedEmpName, value);
                this._CreatedEmpName = value.SubStr(50);
            }
        }

        /// <summary>
        /// 创建时间.
        /// </summary>
        public DateTime? CreatedTime
        {
            get
            {
                return this._CreatedTime;
            }
            set
            {
                this.OnPropertyValueChange(_.CreatedTime, _CreatedTime, value);
                this._CreatedTime = value;
            }
        }

        /// <summary>
        /// 更新人.
        /// </summary>
        public Int32? UpdatedEmpID
        {
            get
            {
                return this._UpdatedEmpID;
            }
            set
            {
                this.OnPropertyValueChange(_.UpdatedEmpID, _UpdatedEmpID, value);
                this._UpdatedEmpID = value;
            }
        }

        /// <summary>
        /// 更新人.
        /// </summary>
        public String UpdatedEmpName
        {
            get
            {
                return this._UpdatedEmpName;
            }
            set
            {
                this.OnPropertyValueChange(_.UpdatedEmpName, _UpdatedEmpName, value);
                this._UpdatedEmpName = value.SubStr(50);
            }
        }

        /// <summary>
        /// 更新时间.
        /// </summary>
        public DateTime? UpdatedTime
        {
            get
            {
                return this._UpdatedTime;
            }
            set
            {
                this.OnPropertyValueChange(_.UpdatedTime, _UpdatedTime, value);
                this._UpdatedTime = value;
            }
        }

        /// <summary>
        /// 是否停止.
        /// </summary>
        public Boolean? IsStop
        {
            get
            {
                return this._IsStop;
            }
            set
            {
                this.OnPropertyValueChange(_.IsStop, _IsStop, value);
                this._IsStop = value;
            }
        }

        /// <summary>
        /// 是否删除.
        /// </summary>
        public Boolean? IsDeleted
        {
            get
            {
                return this._IsDeleted;
            }
            set
            {
                this.OnPropertyValueChange(_.IsDeleted, _IsDeleted, value);
                this._IsDeleted = value;
            }
        }

        #endregion
        /// <summary>
        /// 获取实体对应的表名
        /// </summary>
        protected override Table GetTable()
        {
            return new Table<WF_AuditBill>("WF_AuditBill");
        }

        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        protected override Field GetIdentityField()
        {
            return _.WFAuditID;
        }

        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        protected override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.WFAuditID
			};
        }

        /// <summary>
        /// 获取列信息
        /// </summary>
        protected override Field[] GetFields()
        {
            return new Field[] {
				_.WFAuditID,		
				_.WFAuditGuid,		
				_.GCompanyID,		
				_.TableName,		
				_.WFNamae,		
				_.CreatedEmpID,		
				_.CreatedEmpName,		
				_.CreatedTime,		
				_.UpdatedEmpID,		
				_.UpdatedEmpName,		
				_.UpdatedTime,		
				_.IsStop,		
				_.IsDeleted		
			};
        }

        /// <summary>
        /// 获取列数据
        /// </summary>
        protected override object[] GetValues()
        {
            return new object[] {
				this._WFAuditID,		
				this._WFAuditGuid,		
				this._GCompanyID,		
				this._TableName,		
				this._WFNamae,		
				this._CreatedEmpID,		
				this._CreatedEmpName,		
				this._CreatedTime,		
				this._UpdatedEmpID,		
				this._UpdatedEmpName,		
				this._UpdatedTime,		
				this._IsStop,		
				this._IsDeleted		
			};
        }

        /// <summary>
        /// 给当前实体赋值
        /// </summary>
        protected override void SetValues(IRowReader reader)
        {
            if ((false == reader.IsDBNull(_.WFAuditID)))
            {
                this._WFAuditID = reader.GetInt32(_.WFAuditID);
            }
            if ((false == reader.IsDBNull(_.WFAuditGuid)))
            {
                this._WFAuditGuid = reader.GetGuid(_.WFAuditGuid);
            }
            if ((false == reader.IsDBNull(_.GCompanyID)))
            {
                this._GCompanyID = reader.GetGuid(_.GCompanyID);
            }
            if ((false == reader.IsDBNull(_.TableName)))
            {
                this._TableName = reader.GetString(_.TableName);
            }
            if ((false == reader.IsDBNull(_.WFNamae)))
            {
                this._WFNamae = reader.GetString(_.WFNamae);
            }
            if ((false == reader.IsDBNull(_.CreatedEmpID)))
            {
                this._CreatedEmpID = reader.GetInt32(_.CreatedEmpID);
            }
            if ((false == reader.IsDBNull(_.CreatedEmpName)))
            {
                this._CreatedEmpName = reader.GetString(_.CreatedEmpName);
            }
            if ((false == reader.IsDBNull(_.CreatedTime)))
            {
                this._CreatedTime = reader.GetDateTime(_.CreatedTime);
            }
            if ((false == reader.IsDBNull(_.UpdatedEmpID)))
            {
                this._UpdatedEmpID = reader.GetInt32(_.UpdatedEmpID);
            }
            if ((false == reader.IsDBNull(_.UpdatedEmpName)))
            {
                this._UpdatedEmpName = reader.GetString(_.UpdatedEmpName);
            }
            if ((false == reader.IsDBNull(_.UpdatedTime)))
            {
                this._UpdatedTime = reader.GetDateTime(_.UpdatedTime);
            }
            if ((false == reader.IsDBNull(_.IsStop)))
            {
                this._IsStop = reader.GetBoolean(_.IsStop);
            }
            if ((false == reader.IsDBNull(_.IsDeleted)))
            {
                this._IsDeleted = reader.GetBoolean(_.IsDeleted);
            }
        }

        public override int GetHashCode()
        {
            return base.GetHashCode();
        }

        public override bool Equals(object obj)
        {
            if ((obj == null))
            {
                return false;
            }
            if ((false == typeof(WF_AuditBill).IsAssignableFrom(obj.GetType())))
            {
                return false;
            }
            if ((((object)(this)) == ((object)(obj))))
            {
                return true;
            }
            return false;
        }

        public class _
        {

            /// <summary>
            /// 表示选择所有列，与*等同
            /// </summary>
            public static AllField All = new AllField<WF_AuditBill>();

            /// <summary>
            ///  - 字段名：WFAuditID - 数据类型：Int32?
            /// </summary>
            public static Field WFAuditID = new Field<WF_AuditBill>("WFAuditID");
            /// <summary>
            ///  - 字段名：WFAuditGuid - 数据类型：Guid?
            /// </summary>
            public static Field WFAuditGuid = new Field<WF_AuditBill>("WFAuditGuid");
            /// <summary>
            ///  - 字段名：GCompanyID - 数据类型：Guid?
            /// </summary>
            public static Field GCompanyID = new Field<WF_AuditBill>("GCompanyID");
            /// <summary>
            ///  - 字段名：TableName - 数据类型：String
            /// </summary>
            public static Field TableName = new Field<WF_AuditBill>("TableName");
            /// <summary>
            ///  - 字段名：WFNamae - 数据类型：String
            /// </summary>
            public static Field WFNamae = new Field<WF_AuditBill>("WFNamae");
            /// <summary>
            /// 创建人 - 字段名：CreatedEmpID - 数据类型：Int32?
            /// </summary>
            public static Field CreatedEmpID = new Field<WF_AuditBill>("CreatedEmpID");
            /// <summary>
            /// 创建人姓名 - 字段名：CreatedEmpName - 数据类型：String
            /// </summary>
            public static Field CreatedEmpName = new Field<WF_AuditBill>("CreatedEmpName");
            /// <summary>
            /// 创建时间 - 字段名：CreatedTime - 数据类型：DateTime?
            /// </summary>
            public static Field CreatedTime = new Field<WF_AuditBill>("CreatedTime");
            /// <summary>
            /// 更新人 - 字段名：UpdatedEmpID - 数据类型：Int32?
            /// </summary>
            public static Field UpdatedEmpID = new Field<WF_AuditBill>("UpdatedEmpID");
            /// <summary>
            /// 更新人 - 字段名：UpdatedEmpName - 数据类型：String
            /// </summary>
            public static Field UpdatedEmpName = new Field<WF_AuditBill>("UpdatedEmpName");
            /// <summary>
            /// 更新时间 - 字段名：UpdatedTime - 数据类型：DateTime?
            /// </summary>
            public static Field UpdatedTime = new Field<WF_AuditBill>("UpdatedTime");
            /// <summary>
            /// 是否停止 - 字段名：IsStop - 数据类型：Boolean?
            /// </summary>
            public static Field IsStop = new Field<WF_AuditBill>("IsStop");
            /// <summary>
            /// 是否删除 - 字段名：IsDeleted - 数据类型：Boolean?
            /// </summary>
            public static Field IsDeleted = new Field<WF_AuditBill>("IsDeleted");
        }
    }
}
