//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by CodeSmith Template.
//
//     Creater: Administrator
//     Date:    2015/1/6
//     Time:    19:37
//     Version: 4.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

/// <summary>
/// CodeSmith自动生成的实体
/// </summary>
namespace ZNLCRM.Entity.DBModel
{
    using System;
    using MySoft.Data;
    using ZNLCRM.Utility;
    using ZNLFrame.Entity;
    /// <summary>
    /// 表名：WF_TableFields 主键列：WF_TableFieldID
    /// </summary>
    [SerializableAttribute()]
    public partial class WF_TableFields : BaseEntity
    {
        #region Private Properties

        private Int32 _WF_TableFieldID;
        private Int32? _WF_TableID;
        private String _WF_FieldChsName;
        private String _WF_FieldEngName;
        private String _WF_FieldType;
        private Boolean? _IsKeyGuid;
        private Int32? _CreatedEmpID;
        private String _CreatedEmpName;
        private DateTime? _CreatedTime;
        private Int32? _UpdatedEmpID;
        private String _UpdatedEmpName;
        private DateTime? _UpdatedTime;
        private Boolean? _IsDeleted;

        #endregion

        #region Public Properties

        /// <summary>
        /// 流程表字段ID.
        /// </summary>
        public Int32 WF_TableFieldID
        {
            get
            {
                return _WF_TableFieldID;
            }
            set
            {
                this.OnPropertyValueChange(_.WF_TableFieldID, _WF_TableFieldID, value);
                this._WF_TableFieldID = value;
            }
        }

        /// <summary>
        /// 流程表关表名ID.
        /// </summary>
        public Int32? WF_TableID
        {
            get
            {
                return this._WF_TableID;
            }
            set
            {
                this.OnPropertyValueChange(_.WF_TableID, _WF_TableID, value);
                this._WF_TableID = value;
            }
        }

        /// <summary>
        /// 表字段中文名.
        /// </summary>
        public String WF_FieldChsName
        {
            get
            {
                return this._WF_FieldChsName;
            }
            set
            {
                this.OnPropertyValueChange(_.WF_FieldChsName, _WF_FieldChsName, value);
                this._WF_FieldChsName = value.SubStr(120);
            }
        }

        /// <summary>
        /// 表字段英文名.
        /// </summary>
        public String WF_FieldEngName
        {
            get
            {
                return this._WF_FieldEngName;
            }
            set
            {
                this.OnPropertyValueChange(_.WF_FieldEngName, _WF_FieldEngName, value);
                this._WF_FieldEngName = value.SubStr(120);
            }
        }

        /// <summary>
        /// 字段类型.
        /// </summary>
        public String WF_FieldType
        {
            get
            {
                return this._WF_FieldType;
            }
            set
            {
                this.OnPropertyValueChange(_.WF_FieldType, _WF_FieldType, value);
                this._WF_FieldType = value.SubStr(20);
            }
        }

        /// <summary>
        /// .
        /// </summary>
        public Boolean? IsKeyGuid
        {
            get
            {
                return this._IsKeyGuid;
            }
            set
            {
                this.OnPropertyValueChange(_.IsKeyGuid, _IsKeyGuid, value);
                this._IsKeyGuid = value;
            }
        }

        /// <summary>
        /// 创建人.
        /// </summary>
        public Int32? CreatedEmpID
        {
            get
            {
                return this._CreatedEmpID;
            }
            set
            {
                this.OnPropertyValueChange(_.CreatedEmpID, _CreatedEmpID, value);
                this._CreatedEmpID = value;
            }
        }

        /// <summary>
        /// 创建人姓名.
        /// </summary>
        public String CreatedEmpName
        {
            get
            {
                return this._CreatedEmpName;
            }
            set
            {
                this.OnPropertyValueChange(_.CreatedEmpName, _CreatedEmpName, value);
                this._CreatedEmpName = value.SubStr(50);
            }
        }

        /// <summary>
        /// 创建时间.
        /// </summary>
        public DateTime? CreatedTime
        {
            get
            {
                return this._CreatedTime;
            }
            set
            {
                this.OnPropertyValueChange(_.CreatedTime, _CreatedTime, value);
                this._CreatedTime = value;
            }
        }

        /// <summary>
        /// 更新人.
        /// </summary>
        public Int32? UpdatedEmpID
        {
            get
            {
                return this._UpdatedEmpID;
            }
            set
            {
                this.OnPropertyValueChange(_.UpdatedEmpID, _UpdatedEmpID, value);
                this._UpdatedEmpID = value;
            }
        }

        /// <summary>
        /// 更新人.
        /// </summary>
        public String UpdatedEmpName
        {
            get
            {
                return this._UpdatedEmpName;
            }
            set
            {
                this.OnPropertyValueChange(_.UpdatedEmpName, _UpdatedEmpName, value);
                this._UpdatedEmpName = value.SubStr(50);
            }
        }

        /// <summary>
        /// 更新时间.
        /// </summary>
        public DateTime? UpdatedTime
        {
            get
            {
                return this._UpdatedTime;
            }
            set
            {
                this.OnPropertyValueChange(_.UpdatedTime, _UpdatedTime, value);
                this._UpdatedTime = value;
            }
        }

        /// <summary>
        /// 是否删除.
        /// </summary>
        public Boolean? IsDeleted
        {
            get
            {
                return this._IsDeleted;
            }
            set
            {
                this.OnPropertyValueChange(_.IsDeleted, _IsDeleted, value);
                this._IsDeleted = value;
            }
        }

        #endregion
        /// <summary>
        /// 获取实体对应的表名
        /// </summary>
        protected override Table GetTable()
        {
            return new Table<WF_TableFields>("WF_TableFields");
        }

        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        protected override Field GetIdentityField()
        {
            return _.WF_TableFieldID;
        }

        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        protected override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.WF_TableFieldID
			};
        }

        /// <summary>
        /// 获取列信息
        /// </summary>
        protected override Field[] GetFields()
        {
            return new Field[] {
				_.WF_TableFieldID,		
				_.WF_TableID,		
				_.WF_FieldChsName,		
				_.WF_FieldEngName,		
				_.WF_FieldType,		
				_.IsKeyGuid,		
				_.CreatedEmpID,		
				_.CreatedEmpName,		
				_.CreatedTime,		
				_.UpdatedEmpID,		
				_.UpdatedEmpName,		
				_.UpdatedTime,		
				_.IsDeleted		
			};
        }

        /// <summary>
        /// 获取列数据
        /// </summary>
        protected override object[] GetValues()
        {
            return new object[] {
				this._WF_TableFieldID,		
				this._WF_TableID,		
				this._WF_FieldChsName,		
				this._WF_FieldEngName,		
				this._WF_FieldType,		
				this._IsKeyGuid,		
				this._CreatedEmpID,		
				this._CreatedEmpName,		
				this._CreatedTime,		
				this._UpdatedEmpID,		
				this._UpdatedEmpName,		
				this._UpdatedTime,		
				this._IsDeleted		
			};
        }

        /// <summary>
        /// 给当前实体赋值
        /// </summary>
        protected override void SetValues(IRowReader reader)
        {
            if ((false == reader.IsDBNull(_.WF_TableFieldID)))
            {
                this._WF_TableFieldID = reader.GetInt32(_.WF_TableFieldID);
            }
            if ((false == reader.IsDBNull(_.WF_TableID)))
            {
                this._WF_TableID = reader.GetInt32(_.WF_TableID);
            }
            if ((false == reader.IsDBNull(_.WF_FieldChsName)))
            {
                this._WF_FieldChsName = reader.GetString(_.WF_FieldChsName);
            }
            if ((false == reader.IsDBNull(_.WF_FieldEngName)))
            {
                this._WF_FieldEngName = reader.GetString(_.WF_FieldEngName);
            }
            if ((false == reader.IsDBNull(_.WF_FieldType)))
            {
                this._WF_FieldType = reader.GetString(_.WF_FieldType);
            }
            if ((false == reader.IsDBNull(_.IsKeyGuid)))
            {
                this._IsKeyGuid = reader.GetBoolean(_.IsKeyGuid);
            }
            if ((false == reader.IsDBNull(_.CreatedEmpID)))
            {
                this._CreatedEmpID = reader.GetInt32(_.CreatedEmpID);
            }
            if ((false == reader.IsDBNull(_.CreatedEmpName)))
            {
                this._CreatedEmpName = reader.GetString(_.CreatedEmpName);
            }
            if ((false == reader.IsDBNull(_.CreatedTime)))
            {
                this._CreatedTime = reader.GetDateTime(_.CreatedTime);
            }
            if ((false == reader.IsDBNull(_.UpdatedEmpID)))
            {
                this._UpdatedEmpID = reader.GetInt32(_.UpdatedEmpID);
            }
            if ((false == reader.IsDBNull(_.UpdatedEmpName)))
            {
                this._UpdatedEmpName = reader.GetString(_.UpdatedEmpName);
            }
            if ((false == reader.IsDBNull(_.UpdatedTime)))
            {
                this._UpdatedTime = reader.GetDateTime(_.UpdatedTime);
            }
            if ((false == reader.IsDBNull(_.IsDeleted)))
            {
                this._IsDeleted = reader.GetBoolean(_.IsDeleted);
            }
        }

        public override int GetHashCode()
        {
            return base.GetHashCode();
        }

        public override bool Equals(object obj)
        {
            if ((obj == null))
            {
                return false;
            }
            if ((false == typeof(WF_TableFields).IsAssignableFrom(obj.GetType())))
            {
                return false;
            }
            if ((((object)(this)) == ((object)(obj))))
            {
                return true;
            }
            return false;
        }

        public class _
        {

            /// <summary>
            /// 表示选择所有列，与*等同
            /// </summary>
            public static AllField All = new AllField<WF_TableFields>();

            /// <summary>
            /// 流程表字段ID - 字段名：WF_TableFieldID - 数据类型：Int32?
            /// </summary>
            public static Field WF_TableFieldID = new Field<WF_TableFields>("WF_TableFieldID");
            /// <summary>
            /// 流程表关表名ID - 字段名：WF_TableID - 数据类型：Int32?
            /// </summary>
            public static Field WF_TableID = new Field<WF_TableFields>("WF_TableID");
            /// <summary>
            /// 表字段中文名 - 字段名：WF_FieldChsName - 数据类型：String
            /// </summary>
            public static Field WF_FieldChsName = new Field<WF_TableFields>("WF_FieldChsName");
            /// <summary>
            /// 表字段英文名 - 字段名：WF_FieldEngName - 数据类型：String
            /// </summary>
            public static Field WF_FieldEngName = new Field<WF_TableFields>("WF_FieldEngName");
            /// <summary>
            /// 字段类型 - 字段名：WF_FieldType - 数据类型：String
            /// </summary>
            public static Field WF_FieldType = new Field<WF_TableFields>("WF_FieldType");
            /// <summary>
            ///  - 字段名：IsKeyGuid - 数据类型：Boolean?
            /// </summary>
            public static Field IsKeyGuid = new Field<WF_TableFields>("IsKeyGuid");
            /// <summary>
            /// 创建人 - 字段名：CreatedEmpID - 数据类型：Int32?
            /// </summary>
            public static Field CreatedEmpID = new Field<WF_TableFields>("CreatedEmpID");
            /// <summary>
            /// 创建人姓名 - 字段名：CreatedEmpName - 数据类型：String
            /// </summary>
            public static Field CreatedEmpName = new Field<WF_TableFields>("CreatedEmpName");
            /// <summary>
            /// 创建时间 - 字段名：CreatedTime - 数据类型：DateTime?
            /// </summary>
            public static Field CreatedTime = new Field<WF_TableFields>("CreatedTime");
            /// <summary>
            /// 更新人 - 字段名：UpdatedEmpID - 数据类型：Int32?
            /// </summary>
            public static Field UpdatedEmpID = new Field<WF_TableFields>("UpdatedEmpID");
            /// <summary>
            /// 更新人 - 字段名：UpdatedEmpName - 数据类型：String
            /// </summary>
            public static Field UpdatedEmpName = new Field<WF_TableFields>("UpdatedEmpName");
            /// <summary>
            /// 更新时间 - 字段名：UpdatedTime - 数据类型：DateTime?
            /// </summary>
            public static Field UpdatedTime = new Field<WF_TableFields>("UpdatedTime");
            /// <summary>
            /// 是否删除 - 字段名：IsDeleted - 数据类型：Boolean?
            /// </summary>
            public static Field IsDeleted = new Field<WF_TableFields>("IsDeleted");
        }
    }
}
